<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Di</name>
   <tag></tag>
   <elementGuidId>6f399529-b1c3-43fc-81db-5ead15d28c32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe_response']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe_response</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5a9a6638-7919-4daa-b157-86fba90487e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe_response</value>
      <webElementGuid>59ecb013-1939-45a7-9ac5-6c8089e340e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://girley.herokuapp.com/search?origin=http://desa.olva.com.pe:8080</value>
      <webElementGuid>a10b3574-e99c-4f24-b271-5416d29e2ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe_response&quot;)</value>
      <webElementGuid>bdac9c7e-6cd5-43a9-b0cb-80a758d79f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inicio/Page_Principal - Olva Courier/iframe_Re</value>
      <webElementGuid>cc5f5f78-89e7-412d-9e7b-ae172061a017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe_response']</value>
      <webElementGuid>7f870710-cd6a-498f-b428-50e2b42b12a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDireccionEntrega']/iframe</value>
      <webElementGuid>1c27b702-5203-4f93-8776-fe4b0747d4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ab8045c6-cf3f-4310-a389-b748a481eb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe_response' and @src = 'https://girley.herokuapp.com/search?origin=http://desa.olva.com.pe:8080']</value>
      <webElementGuid>d123c67b-743c-421e-ad6b-110350ad79e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
