<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Rep</name>
   <tag></tag>
   <elementGuidId>ffa92a46-b4dc-4e41-8cce-7923035a05a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>feae17ec-5f23-41bb-813d-e2d3abc2989d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>a576725a-34dc-45b8-accf-efbaff2a5362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>5ac2a692-5801-4c8e-bc73-86bd61496caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NzAxMDQwNSwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNTUzYjQ0MzAtMTQ5NC00Y2UzLWFhMjctY2Q1M2E1M2IyNDc1IiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.kvSCidUR6YhfwC78e-stDVi-jBpLvHNrum7AD-_Pkvc</value>
      <webElementGuid>e8caf7c5-7c3f-4cf1-9656-800d25246b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>a1a82d8b-1667-4759-873c-9f3f8bb6f999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>1c7f6cb3-9ab1-4dc1-ab19-0473c0d5d6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>9f8caadd-56c5-4baf-8f96-e320595fa826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>15ea9381-0f47-411f-8df3-f5b97f541e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NzAxMDQwNSwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNTUzYjQ0MzAtMTQ5NC00Y2UzLWFhMjctY2Q1M2E1M2IyNDc1IiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.kvSCidUR6YhfwC78e-stDVi-jBpLvHNrum7AD-_Pkvc']</value>
      <webElementGuid>8bd6bc70-89e7-4ced-8316-6c4c35825f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
