<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_clave_seguridad2</name>
   <tag></tag>
   <elementGuidId>3b3be1d9-219c-4ab4-9b90-77d60be49688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmCDS:txt_clave_seguridad2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a795f4e3-135e-4081-bca8-e26ffb44d592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmCDS:txt_clave_seguridad2</value>
      <webElementGuid>8b7ca715-995c-4bf9-b64c-cf88e10ac3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmCDS:txt_clave_seguridad2</value>
      <webElementGuid>b58382ee-4cdb-400c-863d-8266332fb658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>052b8979-de06-475e-a82d-3ef936e582e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-password ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>426082fd-2ef2-4eda-9180-b0dd87af0d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc05c490-d3d3-4b31-8797-fe58a87adc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2abff2af-9177-43c8-b9e8-74752a01d579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>118d92ab-147b-4c78-b2db-6b3d152eb56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode !== 13) {                                                     javascript: var valor = soloNumerosEnteros(event); return valor;                                                  }</value>
      <webElementGuid>ca5ee366-d800-488e-8615-261a93c2dc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3009b3ec-7443-4948-8d53-d4ba0d80593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>017d5534-23fe-4226-a1ea-3788bbfcb04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>86de142b-4d6f-40c1-8928-f8f3bb702090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCDS:txt_clave_seguridad2&quot;)</value>
      <webElementGuid>f27647e7-fb6b-4c8b-8af4-205188c127b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inicio/Page_Principal - Olva Courier/iframe_Report</value>
      <webElementGuid>fd1cee54-0eae-49fa-92d3-e1b6ea0c0fe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmCDS:txt_clave_seguridad2']</value>
      <webElementGuid>94a7769e-b3a3-4a5d-be2e-d765e784315d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmCDS:pnlCDS_content']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>fb14a9c8-5bce-4108-9cee-b0aa50cfca37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div[2]/form/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>44d95bba-2718-4959-923c-1aefdf7cc7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmCDS:txt_clave_seguridad2' and @name = 'frmCDS:txt_clave_seguridad2' and @type = 'password']</value>
      <webElementGuid>3ff76d81-7d32-425b-b9e2-f3bf5d4b910b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
