<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_23 - 00005177</name>
   <tag></tag>
   <elementGuidId>37b7e5fb-5ada-4744-a630-a9c24c569ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;div_container&quot;]/form/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-warning.mt-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>066ce2ce-ef3f-4c3a-a6e6-5192d3154c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bd5f9ee4-cf35-4021-a551-e5a83c71060f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mt-10</value>
      <webElementGuid>ac1c5b9a-9f4b-45aa-902c-12f9e0f2c8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formtarget</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>fbad554b-4ca0-494a-b88b-2e257408e990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23 - 00005177 </value>
      <webElementGuid>82f94779-c0fe-4e4a-8eae-eb2099d64acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/form[1]/button[@class=&quot;btn btn-warning mt-10&quot;]</value>
      <webElementGuid>b4b370b8-5fd6-4a32-9c18-4f9c005a94e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>366f40fc-18d1-4f88-95d4-3effc709c83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nro de tracking'])[1]/following::button[1]</value>
      <webElementGuid>9d27dede-4505-4420-a529-6dd186a2c475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡COMPRA EXITOSA!'])[1]/following::button[1]</value>
      <webElementGuid>32e67756-6799-44ee-940b-dc57faa11e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡MUCHAS GRACIAS POR CONFIAR EN NOSOTROS!'])[1]/preceding::button[1]</value>
      <webElementGuid>fbaf0a4c-9bad-4997-9f2e-5b0c601067a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::button[1]</value>
      <webElementGuid>855860c4-a8be-420b-9923-2c95e5448131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='23 - 00005177']/parent::*</value>
      <webElementGuid>6b82d9db-a1e2-47ea-8921-f3ae4c545bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a0f89089-5244-42c9-ba6a-cf6238509e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '23 - 00005177 ' or . = '23 - 00005177 ')]</value>
      <webElementGuid>0a502d5b-3d34-474c-a07c-06fd3b8ee826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
