<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CODIGO DE BARRAS_frmAsignaciontxtCodi_2f39f3</name>
   <tag></tag>
   <elementGuidId>f15975e0-3b8b-4498-9b8d-bc57c38ae1e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'frmAsignacion:txtCodigoBarras')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>786d5d9c-4925-4e31-bb6c-613b15b633a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAsignacion:txtCodigoBarras</value>
      <webElementGuid>2bd90bf0-e651-4973-820e-7c0a10934acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmAsignacion:txtCodigoBarras</value>
      <webElementGuid>7b5a82a1-6caa-434d-a2d0-94783d47f0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec062335-bc66-4bde-a527-2d5ef4ea519d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7dbbfdca-cc86-4676-8540-a07a5d966728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>62f77451-64db-4941-a482-774dc17f879c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                                                                  if (this.value === '') {                                                                      PF('growlFrmAsignacionMsg').renderMessage({'summary': '', 'detail': 'INGRESE VALOR.', 'severity': 'warn'});                                                                  } else {                                                                      if (!isRemitoAsignado(this.value)) {                                                                          sendCodBarras(this.value, '1');                                                                      } else {                                                                          if(checkAsignarAuto){                                                                             sendCodBarras(this.value, '1');                                                                          }else{                                                                             PF('growlFrmAsignacionMsg').renderMessage({'summary': '', 'detail': 'EL ENVIO YA FUE ASIGNADO.', 'severity': 'warn'});                                                                          }                                                                      }                                                                      $('#frmAsignacion\\:ihnValueCodigoBarras').val(this.value);                                                                      this.value = '';                                                                      console.log('remito oculto: '+$('#frmAsignacion\\:ihnValueCodigoBarras').val());                                                                  }                                                                  return false;                                                              }</value>
      <webElementGuid>52e1551c-3601-4001-9dbe-6dfb6f144b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all codigoDeBarras ui-state-focus ui-state-hover</value>
      <webElementGuid>21c26971-eba0-42af-9da7-f761375e5310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c2f44e25-1d93-4f7f-9ef8-e20eedbf2936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06f176f2-bd31-4b7d-b383-d7405a084e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11c4ad8b-ceef-415e-814e-1403f2cb5b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAsignacion:txtCodigoBarras&quot;)</value>
      <webElementGuid>efc7f115-ae0d-4382-a9d7-2282e72e19f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Distribucion/Distribucion/iframe_Reporte Destajo por Operador_iframeP_aa3353</value>
      <webElementGuid>ed4a5647-b888-40fc-a254-d87a9416a5ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmAsignacion:txtCodigoBarras']</value>
      <webElementGuid>d45d949d-ef78-4559-bf1e-c146acb7628e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmAsignacion:j_idt14']/tbody/tr/td/table/tbody/tr[3]/th[2]/input</value>
      <webElementGuid>7205d6ca-9862-4cd4-bbf2-af20000a7ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th[2]/input</value>
      <webElementGuid>03b9d2e3-9bfe-4074-803c-f32457bd50b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmAsignacion:txtCodigoBarras' and @name = 'frmAsignacion:txtCodigoBarras' and @type = 'text']</value>
      <webElementGuid>9aec2c1a-0d0c-452f-b13c-6e4c98ce6fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
