<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin de Entrega_direccion_new</name>
   <tag></tag>
   <elementGuidId>d4889eeb-6163-4108-9aff-36d1003201b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#direccion_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='direccion_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf06a0e8-4a71-499a-99ad-af03e62af8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direccion_new</value>
      <webElementGuid>69b4bd33-7816-461d-9a6f-9137e02305ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aabee4ac-0da7-400c-aa23-79e80794567d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd9ece76-a0cf-4ec3-aab1-aed907d82ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa una dirección</value>
      <webElementGuid>331183e7-f30c-4880-afc5-188ae0189c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>79fab981-19f5-41bd-a977-a1b73c1fec0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direccion_new&quot;)</value>
      <webElementGuid>ece2df33-489c-43e5-b332-b45278a48a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inicio/Page_Atencin al Cliente/Page_Olva Courier  Datos Personales/iframe_Cerrar_iframe_response_1</value>
      <webElementGuid>20bbc26d-bf1d-4386-8444-aa2e526b330d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='direccion_new']</value>
      <webElementGuid>27c6b47b-5bae-4e51-b4b7-89e6ccc66a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__568482___BV___']/div/input</value>
      <webElementGuid>139e3640-a062-40b5-aefc-0d9cf45233a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>438ed2c4-8d60-4a5c-96a2-8a92b9cebaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'direccion_new' and @type = 'text' and @placeholder = 'Ingresa una dirección']</value>
      <webElementGuid>202a2cf9-4bc1-4e62-bbef-23d2b7d62a21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
