<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nombres_receptor</name>
   <tag></tag>
   <elementGuidId>e1cf9d0e-0ebf-4727-bfd2-838fe9fdd935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_consignado_nombres</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_consignado_nombres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5cac58e-70e3-4fb5-af6e-d6f0a05f9246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c7115a60-062d-4b61-9b87-1f5ab03b9c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa6ed28e-0d1d-4446-bbb9-1e2338ad5d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_consignado_nombres</value>
      <webElementGuid>3d222f6e-9844-4cec-9045-57576ae9ee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombres y Apellidos</value>
      <webElementGuid>38210558-4721-47e0-b80b-9cb0089cc42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>91394f19-93b1-43b0-955b-fdadb405c1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado</value>
      <webElementGuid>c4e97d44-2eee-4aae-9563-bbb78840f96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>012ced29-fc76-46c7-a37f-8a2787dae847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_consignado_nombres</value>
      <webElementGuid>afeaded7-83d1-4f88-86d7-29e78d6ac0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>5c2a955f-5384-4451-a1d0-9b107afa3da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_consignado_nombres&quot;)</value>
      <webElementGuid>7f68a605-32be-4d39-be1a-0598f54aa86e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_consignado_nombres']</value>
      <webElementGuid>87ceb83d-cf7d-4a00-8e9b-899458c75861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_recibe']/div[3]/div[2]/input</value>
      <webElementGuid>ed8f12ac-63e6-4df8-a96c-c44914fcda0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div[2]/input</value>
      <webElementGuid>6bd2305f-e0ee-406a-97d9-91367290ba49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_consignado_nombres' and @placeholder = 'Nombres y Apellidos' and @id = 'txt_consignado_nombres' and @title = '.']</value>
      <webElementGuid>b84b9220-d4d7-49ee-9355-8102d0fa7382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
