<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CODIGO DE BARRAS_frmLiquidaciontxtCodi_2</name>
   <tag></tag>
   <elementGuidId>b5324482-8738-4a14-9b15-8139f2d6bf79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'frmLiquidacionEnvio:codigoBarras')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28146a34-e06b-442e-84cf-fab252864f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAsignacion:txtCodigoBarras</value>
      <webElementGuid>4e2c1e80-5aca-4020-a315-e2b39573b7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmAsignacion:txtCodigoBarras</value>
      <webElementGuid>2798c499-4dd2-4a68-9569-053da5644d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc8e7175-db01-4391-9933-d6241a6154c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84683733-db9d-4932-b393-324177dd545d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>47e9d597-573e-41b3-a33d-0e33b028cf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                                                                  if (this.value === '') {                                                                      PF('growlFrmAsignacionMsg').renderMessage({'summary': '', 'detail': 'INGRESE VALOR.', 'severity': 'warn'});                                                                  } else {                                                                      if (!isRemitoAsignado(this.value)) {                                                                          sendCodBarras(this.value, '1');                                                                      } else {                                                                          if(checkAsignarAuto){                                                                             sendCodBarras(this.value, '1');                                                                          }else{                                                                             PF('growlFrmAsignacionMsg').renderMessage({'summary': '', 'detail': 'EL ENVIO YA FUE ASIGNADO.', 'severity': 'warn'});                                                                          }                                                                      }                                                                      $('#frmAsignacion\\:ihnValueCodigoBarras').val(this.value);                                                                      this.value = '';                                                                      console.log('remito oculto: '+$('#frmAsignacion\\:ihnValueCodigoBarras').val());                                                                  }                                                                  return false;                                                              }</value>
      <webElementGuid>4d778abf-e577-4f8d-a74f-16d342f6304d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all codigoDeBarras ui-state-focus ui-state-hover</value>
      <webElementGuid>9c86447f-25a7-4ccd-bdcc-f077017b671f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5b52142a-6d60-48be-bc67-faebb593a7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a102b49d-21eb-4dde-ade7-388eb25340cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09f3984e-30bf-467c-8619-e61746766f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAsignacion:txtCodigoBarras&quot;)</value>
      <webElementGuid>774e2ae3-ffb9-4447-8bbd-bf03238b20eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Distribucion/iframe_Reporte Destajo por Operador_iframeP_aa3353</value>
      <webElementGuid>b040784d-3810-4920-b4a1-a61b42e7da8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmAsignacion:txtCodigoBarras']</value>
      <webElementGuid>ec6f1169-7f03-452f-b501-a7cf951557c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmAsignacion:j_idt14']/tbody/tr/td/table/tbody/tr[3]/th[2]/input</value>
      <webElementGuid>73c10f9f-0c32-4f9f-9142-eb0469fcdbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th[2]/input</value>
      <webElementGuid>ef884af8-9d58-44de-9b4d-59d83fb1e0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmAsignacion:txtCodigoBarras' and @name = 'frmAsignacion:txtCodigoBarras' and @type = 'text']</value>
      <webElementGuid>92ab734a-b206-4ed0-9b34-2c68d844cff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
