<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Georreferenciacin</name>
   <tag></tag>
   <elementGuidId>0f83a1f1-a04e-4c6f-8c76-5b6ba17ea6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d84f8b42-7b91-40f4-a8bf-05bccc563731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>a0f2c069-4c9d-428f-9df9-a8ea68e28827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>04c023dc-684d-448c-92d3-afa6daa43549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/despacho/digitacion/nuevaVentaDigitacion.xhtml?nodeTree=Digitacion Creditos&amp;codeTree=0311&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3MjE5ODczNiwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiM2ZiOTE3ZmEtNGVmOC00ZTMzLWIwNTktNDhkOWFmZjIwOTAzIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.ChiOSNQ6WkTTFBaIXd6ftD0Jf_7zEWDDzHdy0fgK6wM</value>
      <webElementGuid>02d71e9b-30cf-4110-a398-9adf5cc12436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>e3dcf7db-3960-4655-8a50-82dbe81ac23d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>788314c7-30d2-424e-a83a-5ae063471613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>affd46bf-c4f3-4744-b1e5-b58ab049d146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>589e3070-b074-4df1-b63c-373f59191776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/despacho/digitacion/nuevaVentaDigitacion.xhtml?nodeTree=Digitacion Creditos&amp;codeTree=0311&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3MjE5ODczNiwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiM2ZiOTE3ZmEtNGVmOC00ZTMzLWIwNTktNDhkOWFmZjIwOTAzIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.ChiOSNQ6WkTTFBaIXd6ftD0Jf_7zEWDDzHdy0fgK6wM']</value>
      <webElementGuid>460018f8-2e41-419d-b502-3eaca9ea2267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
