<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>9eb8d574-ff6a-4f4b-b88e-cdae4bdf214b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>16f0c338-e170-443c-abc9-a6992ba15b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>7565ad21-4686-41b4-8662-a4492c179737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>93bbcf83-e395-4899-9f6e-89064abdcdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiRVJOIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NjY4NjU0NzQsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6ImNhODQ3NzVmLTI2MDItNGUxNi1iY2QyLTM2YjVhNzcyYmFlNiIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.QNjFeNLGSqoWJjwQ61wxsu4neKyniR1RuOYeMxJaEbc</value>
      <webElementGuid>dd33d9de-1bcf-4ce6-9430-12ee6765e020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>efe90a3b-de36-4b24-bfac-507009837f9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>12a0307d-f015-4058-878e-8975e92750cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>d8074c9c-fca5-483a-b9de-8c230b6576cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a2c78093-2fbf-4559-b350-58dc25a8a2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiRVJOIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NjY4NjU0NzQsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6ImNhODQ3NzVmLTI2MDItNGUxNi1iY2QyLTM2YjVhNzcyYmFlNiIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.QNjFeNLGSqoWJjwQ61wxsu4neKyniR1RuOYeMxJaEbc']</value>
      <webElementGuid>d21098d4-d177-494c-82e1-2750a5941627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
