<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Procesar</name>
   <tag></tag>
   <elementGuidId>d1f9a507-cb00-42bb-9f43-7ccccf15ae44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_enviar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@id,'enviar')][@name='btn_enviar'][contains(.,'Procesar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9833e6a3-3a5f-49b8-b430-b01abe570fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_enviar</value>
      <webElementGuid>6f772843-b812-4b2a-8a0d-27d94f1a5077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_enviar</value>
      <webElementGuid>13e8107a-33b2-4159-9709-5a218269a245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>be9fd713-63ad-4ea9-bf7e-7a16728135f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-small</value>
      <webElementGuid>7a85caeb-dc61-44b6-8011-c117c7eaa5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                         Procesar

                                                    </value>
      <webElementGuid>605170ba-59b3-448e-8b2f-b2678e5feefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_enviar&quot;)</value>
      <webElementGuid>32be56d4-d6c9-4b75-8751-3a0500300264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_enviar']</value>
      <webElementGuid>4edb130d-e774-4c6d-a067-29d95cdf99d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div/div[7]/button</value>
      <webElementGuid>a92c3eb5-173e-4d1a-8fc9-025c6dcf2ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*) 48 horas'])[1]/preceding::button[1]</value>
      <webElementGuid>7becb2c6-5daa-4676-a3c1-b1e96eb721f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excluir Cliente:'])[1]/preceding::button[1]</value>
      <webElementGuid>65f91901-7c1e-4353-befe-7fd95935e830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Procesar']/parent::*</value>
      <webElementGuid>4ac9f1d1-13bc-4110-b38c-f73be7636ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>bad0c8c7-08e4-4def-b1d3-8c715ef0e6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_enviar' and @name = 'btn_enviar' and (text() = '
                                                         Procesar

                                                    ' or . = '
                                                         Procesar

                                                    ')]</value>
      <webElementGuid>b5f4df34-7ac9-4a33-98d4-f9ba6c6d7976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
