<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Con Licitacion_licitacion</name>
   <tag></tag>
   <elementGuidId>1387fd52-3e3a-4965-8747-27eee661fabb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licitacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#licitacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>121ccdba-7aa9-4666-bbf7-0fdf4f751d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>licitacion</value>
      <webElementGuid>81a6e647-b2d0-4eb7-a43b-090c3adfcf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bf1a8fec-7650-4180-b82f-a87a6e023dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licitacion</value>
      <webElementGuid>5ee74760-cb99-4566-a894-ea7f607108fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1e2ca0a5-584e-411f-82a2-58f853af1225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licitacion&quot;)</value>
      <webElementGuid>355ba314-25fa-4db7-a7bb-a2b0287d342c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licitacion']</value>
      <webElementGuid>5b7278c3-d433-4e1e-abb4-595eb07fd1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div[2]/div[2]/div/div[2]/span[12]/input</value>
      <webElementGuid>57bf5fe8-5fc2-473d-860b-a749fbfd9355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[12]/input</value>
      <webElementGuid>45286e2b-93b8-4575-9f7e-c745d4204aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'licitacion' and @type = 'checkbox' and @id = 'licitacion']</value>
      <webElementGuid>cfc66f74-cd61-445e-84da-9cdb2ba5c948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
