<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Juridico_juridico</name>
   <tag></tag>
   <elementGuidId>312c149e-7cb2-4b37-a680-669b10517adf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='juridico']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#juridico</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ce19b6a-a6cf-44fe-835a-9d8554e69d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>juridico</value>
      <webElementGuid>3dfe707a-00fe-42e9-91a5-56a303068375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>01a6c74e-79e9-4fc3-8769-d8e24bea8624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>juridico</value>
      <webElementGuid>6fb7394b-d19e-4b5a-a201-aeeb59d93dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>455102c9-143f-48e0-87e8-2fe30d1efced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;juridico&quot;)</value>
      <webElementGuid>39abbc85-e87e-437e-add1-e2bb921c71cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='juridico']</value>
      <webElementGuid>083775dc-3710-4ebd-84e1-b511adaa3f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div[2]/div[2]/div/div[2]/span[10]/input</value>
      <webElementGuid>5f641b32-643c-4b2e-8feb-7ab429479fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[10]/input</value>
      <webElementGuid>4990ac94-4974-4f12-a60f-7176c98e3df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'juridico' and @type = 'checkbox' and @id = 'juridico']</value>
      <webElementGuid>e3351e76-f644-4d44-9513-bb96644cc2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
