<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mz, Lote o Referencia_reference</name>
   <tag></tag>
   <elementGuidId>f8ca2571-1bf6-452e-be77-4da1f0a42440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4b43c67-1610-4e70-86cd-a271c41e44e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>e3f444a6-6072-4917-a083-1fd61fd3e722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>978c2813-d182-4d0d-a6d9-8305013d1706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb65eb0d-4710-41e1-9d0d-e26d93f2d7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ejem: Entre Av. Argentina y Av. Universitaria</value>
      <webElementGuid>0bdd68e4-3498-4ce3-b578-0ec33b414a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference&quot;)</value>
      <webElementGuid>ad2fe684-0473-415b-8fe5-c29bdf2bfd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Negativo/Page_Olva Courier  Datos Personales/iframe_Cerrar_iframe_response</value>
      <webElementGuid>bc5cebe6-9172-4161-b48f-9290bd29c187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference']</value>
      <webElementGuid>4646d719-b713-41f6-ba17-bd227a02abda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__498141___BV___']/div/input</value>
      <webElementGuid>2b934211-f329-43eb-8665-bd706d02e416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f608721b-56b4-4e94-b1d8-07118348356e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference' and @type = 'text' and @placeholder = 'Ejem: Entre Av. Argentina y Av. Universitaria']</value>
      <webElementGuid>f7ca687a-d367-4bb1-acb0-987bba18fef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
