<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ACCESORIOS Y EQUIPOS ELEC</name>
   <tag></tag>
   <elementGuidId>4bb235ad-a6a3-45cd-b708-2654ec0b4c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;div_articulo&quot;]/div/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc2f4db0-8092-4554-b99b-fc77490ae562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7081f18d-ca8a-4538-acfd-8fe98683232e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UTILES DE OFICINA</value>
      <webElementGuid>57c67503-f5b9-491f-8e30-d5a5ed337a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_articulo&quot;)/div[@class=&quot;btn-group bootstrap-select form-control msg_alert_tt dropup open&quot;]/div[@class=&quot;dropdown-menu open&quot;]/ul[@class=&quot;dropdown-menu inner selectpicker&quot;]/li[21]/a[1]/span[@class=&quot;text&quot;]</value>
      <webElementGuid>af932288-5085-4535-ab85-0ed6a574cb86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_articulo']/div/div/ul/li[21]/a/span</value>
      <webElementGuid>100df024-97ce-4367-a1b8-86d54f49d00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILES DE ESCRITORIO'])[3]/following::span[2]</value>
      <webElementGuid>d1bc6485-ffd4-4d55-97e9-f2ffaff2994a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIJA-DOCUMENTOS'])[2]/following::span[4]</value>
      <webElementGuid>28dd7207-236c-4718-a203-1a2d4de7dde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cm'])[1]/preceding::span[2]</value>
      <webElementGuid>c863385f-a9d1-44af-92ed-8bd7804b60fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cm'])[2]/preceding::span[3]</value>
      <webElementGuid>7f59bf6e-79e0-4f72-af94-8359c68c1d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div/ul/li[21]/a/span</value>
      <webElementGuid>e0dd6a73-76b8-4441-a956-637e3b3226bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'UTILES DE OFICINA' or . = 'UTILES DE OFICINA')]</value>
      <webElementGuid>bf8833ed-4c7e-4e42-8c2b-5d9fd5f5f90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
