<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Precinto_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>fe9f23c1-626f-4d27-9790-1aeda12c7a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5a2bec25-f8d2-45e5-9f51-0ed80c958d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>77f66574-76e5-4da0-8106-ccf43ee90c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>da7e4db2-8a9e-4706-8219-84f4d8234347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/host/gestion.xhtml?nodeTree=Host&amp;codeTree=0205&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDM1NDI3NywiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNWZjNWViNWUtNmRiYy00ZDlkLWE1MTctNmI5OGVlMGFmYzllIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.vlsdMXVTcqQ_alctleYKTmjD7yAifI4kh_gs-a0C3EE</value>
      <webElementGuid>274b9e81-d89a-4eb7-8343-bd163d5c0246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>45997765-9b71-4365-bb49-e2dcde532c15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>f20408f6-3919-47e6-a1e3-7a74d3f9f15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>f7d6f308-4f33-45ca-a13f-a04d323b2dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>db7dac58-9862-4594-95c3-359d63dc86b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/host/gestion.xhtml?nodeTree=Host&amp;codeTree=0205&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDM1NDI3NywiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNWZjNWViNWUtNmRiYy00ZDlkLWE1MTctNmI5OGVlMGFmYzllIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.vlsdMXVTcqQ_alctleYKTmjD7yAifI4kh_gs-a0C3EE']</value>
      <webElementGuid>c118b57d-fa89-4a9e-a6c0-f5d21f91a7fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
