<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_P. CONSIGNADO_ui-button-icon-left ui-i_91eb9f</name>
   <tag></tag>
   <elementGuidId>b4ed42be-348d-4327-a731-010c67b2939c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmNewEnvio:btnSaveArt']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b48926d6-d66c-4053-b4f6-d1c75a66de5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left ui-icon ui-c ui-icon-plus</value>
      <webElementGuid>876857ab-52cb-4a08-8f89-a5d202df5228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewEnvio:btnSaveArt&quot;)/span[@class=&quot;ui-button-icon-left ui-icon ui-c ui-icon-plus&quot;]</value>
      <webElementGuid>1483fa4e-9800-41bd-8391-fbb94c9a9784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>76a198db-adf1-4079-8742-8c19bedf8a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Distribucion/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>aa74d6a2-755a-4d2f-86d8-dc5b87b2c59d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmNewEnvio:btnSaveArt']/span</value>
      <webElementGuid>1357a409-9d7b-43d9-9c70-58ace87846d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/button/span</value>
      <webElementGuid>93016185-6800-4305-b98d-60434fe93961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
