<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>e23e88bf-10c7-4cd9-b2e8-9921753f46d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b6b57edb-8da6-4677-824c-865bc65fe7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>858c366e-e361-4261-8457-7a494a24ebd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>3c9b1247-c18b-4115-80c5-788c789ce48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiRVJOIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NjY4NjU0NzQsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6ImNhODQ3NzVmLTI2MDItNGUxNi1iY2QyLTM2YjVhNzcyYmFlNiIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.QNjFeNLGSqoWJjwQ61wxsu4neKyniR1RuOYeMxJaEbc</value>
      <webElementGuid>6e9b5422-0ff4-4ee1-9563-248cea39c5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>62b59819-092f-4c07-8c21-5b0060443361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>a05452e6-6015-4ef8-8e56-5087df18d3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>fd5210bd-9661-4946-b62e-efeb86ca4b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8d155609-7107-4e82-bedd-0f2a3cd8f307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiRVJOIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NjY4NjU0NzQsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6ImNhODQ3NzVmLTI2MDItNGUxNi1iY2QyLTM2YjVhNzcyYmFlNiIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.QNjFeNLGSqoWJjwQ61wxsu4neKyniR1RuOYeMxJaEbc']</value>
      <webElementGuid>e8a4dd96-3733-43c4-a623-ddf85719ed5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
