<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Rep</name>
   <tag></tag>
   <elementGuidId>c795c669-88a0-429e-bdb2-eda6ba2ce7bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4d25ab39-d4e7-4579-b4ab-c203331636a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>fe45d8ca-b6c4-4a0d-86a5-bc991de99004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>a7d67e76-4419-4b30-81d9-a3c043bafc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NzI2OTc1NywiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZGYzMmU3ZjAtMTlkNy00YWRhLWI1ZjktNDc3Yjk2YjYxMTRlIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.1Kmo5EoH5ONLAICqgk1CLIKjbflmu5F3Z-bqbiExZ9s</value>
      <webElementGuid>77242eba-84f8-454f-a873-58b1b7fc10c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>8f114f69-e3d9-43a8-b389-c52ff0312db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>028fe703-1f88-424c-a473-4b2de865acd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>697932d9-ca84-4ac1-9656-2fdbcde16d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6764a817-8b95-46eb-aecb-cee860494af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NzI2OTc1NywiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZGYzMmU3ZjAtMTlkNy00YWRhLWI1ZjktNDc3Yjk2YjYxMTRlIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.1Kmo5EoH5ONLAICqgk1CLIKjbflmu5F3Z-bqbiExZ9s']</value>
      <webElementGuid>a546f831-c72f-430d-be43-e105ed010a9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
