<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NUMERO DE PEDIDO_frmPreventaBusctxtNroPedido</name>
   <tag></tag>
   <elementGuidId>181cacf6-e8ae-4abf-a928-d6a0a715a641</elementGuidId>
   <imagePath>C:\Users\roasa\OneDrive\Escritorio\Screenshot_2.jpg</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'frmPreventaBusc:txtNroPedido' and @name = 'frmPreventaBusc:txtNroPedido' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\roasa\OneDrive\Escritorio\Screenshot_2.jpg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8d164a0-4c91-4c0c-9eb9-f06cc4ac1a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPreventaBusc:txtNroPedido</value>
      <webElementGuid>3b0fa57e-a6e8-4072-87ff-7fd8f4312e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPreventaBusc:txtNroPedido</value>
      <webElementGuid>bc00b6ea-a8e8-4142-9462-c4677081dfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>440dbb5c-12d5-4ca2-8af7-27dcb31a71a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>24dc49bd-bf0f-4571-ae48-882480348868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode === 13){                                           rcEnviarCodigo();                                           this.value = '';                                           return false;                                      }</value>
      <webElementGuid>1dd37028-e1b9-4052-b592-e4c1b951990d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>0d71e54b-ae11-40b2-89e4-b12f647e3858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>45f8cafd-cc90-4d23-8b1e-c0da8d1ad8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c735e7e4-45b9-4442-a31f-bc3701d31e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>008dc7ad-b71a-41ae-96ac-5835dd3e3e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPreventaBusc:txtNroPedido&quot;)</value>
      <webElementGuid>5edd2f34-3c65-47b3-8e25-09724a3f6643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Distribucion/Distribucion/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal_1</value>
      <webElementGuid>f851356b-dec2-440e-8493-f2745321ea5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inicio/Page_Atencin al Cliente/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal_1</value>
      <webElementGuid>ef15db7a-d0a4-416d-9374-f35728577150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPreventaBusc:txtNroPedido']</value>
      <webElementGuid>98906f12-56b8-467e-a675-c6c3fe818177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmPreventaBusc:pnlGrdEnviosPistoleados']/tbody/tr/td/input</value>
      <webElementGuid>9c4718d0-637a-4d57-b1ed-d17bca924d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/input</value>
      <webElementGuid>1613cecd-ac35-4396-9bf3-921bd3f02e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPreventaBusc:txtNroPedido' and @name = 'frmPreventaBusc:txtNroPedido' and @type = 'text']</value>
      <webElementGuid>ca98b6f5-9c8c-442f-b3db-9bee15131315</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
