<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NroLote_frmDireccionmz</name>
   <tag></tag>
   <elementGuidId>4b15a909-6188-4cf9-a889-e4f7bdbf079e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmDireccion:mz']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8bc8667-22e8-46c6-ad24-22b74d8fbb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDireccion:mz</value>
      <webElementGuid>146748c6-c566-403e-86f7-b96d4ebb12ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmDireccion:mz</value>
      <webElementGuid>366276a0-db96-4df5-b30f-4f939510dbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>642a14b4-5c04-405a-bf68-b7b2c3b8c209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b2126765-c047-46b6-b520-8c8ee11fc09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>81522157-5196-464d-b525-a5bc5ed7e176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>direc.manzana</value>
      <webElementGuid>69a2be1e-243c-407f-af00-e0b7def3ba42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                                              focusChange('#frmDireccion\\:nroDireccion');                                              btnFltDirec();                                              return false;                                          } else if (event.keyCode === 38 || event.keyCode === 40) {                                              btnSelectTbl();                                          }</value>
      <webElementGuid>e5d2df5a-e863-4458-9927-05c6ac3c81bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase()</value>
      <webElementGuid>6076d19b-dbd8-47c9-bbd9-f54983627e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all txtUppercase ui-state-hover ui-state-focus</value>
      <webElementGuid>88637fb2-f0db-41cb-8fae-f4b35f8f0bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>49b61d7b-4842-4dc1-948d-e80a3afa75e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8c67c098-8a58-44c2-a51f-019a1d96929f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8bcd42f-87aa-4939-baa6-0feb6922a34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDireccion:mz&quot;)</value>
      <webElementGuid>9bae0dc4-9915-4988-8a28-e6d67b8c9bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>5b3ba056-d790-4147-bb05-89017a141c0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmDireccion:mz']</value>
      <webElementGuid>d2d6dd97-4d15-4cbf-8b65-2998f7340470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmDireccion:pnlSearch']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>63268838-3ce5-4f5e-89f9-4646c51d50a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>79506fe3-ae5c-41e7-9e32-9fb913ee7510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmDireccion:mz' and @name = 'frmDireccion:mz' and @type = 'text']</value>
      <webElementGuid>4cb5cbcc-0516-44ab-a320-bdf16c7c38a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
