<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Tiendas provincias</name>
   <tag></tag>
   <elementGuidId>fb1cd6e2-0873-494f-a4e3-effb9f42f6ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>451202fa-af0f-4a7b-a539-dc84c38a26c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c7474cb9-42fd-47c3-9174-8b8dfab3220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiendas provincias</value>
      <webElementGuid>5b134553-444b-439b-b8e8-e775e8138fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;page_title transparent&quot;]/div[@class=&quot;container&quot;]/h1[@class=&quot;h2&quot;]</value>
      <webElementGuid>dfd269b5-8beb-42cb-82aa-53e3f374c525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/h1</value>
      <webElementGuid>58b1be13-2bff-45d2-9327-30ca017e1ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención al Cliente'])[2]/following::h1[1]</value>
      <webElementGuid>2d22951b-663b-42b7-b2a9-74cfb723eb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona de Clientes'])[2]/following::h1[1]</value>
      <webElementGuid>a909ecb3-b4b2-495c-bf7f-0002e4e974f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver tiendas'])[1]/preceding::h1[1]</value>
      <webElementGuid>b4dd6402-0244-427f-bb22-481cfdf97208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noticias Recientes'])[1]/preceding::h1[1]</value>
      <webElementGuid>19dcfc93-9fc9-4815-8a6c-4e756a60b878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tiendas provincias']/parent::*</value>
      <webElementGuid>ca0c040c-1a6a-41ab-89df-fe393f46184d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7310c7f7-c59f-4db1-bb43-2735bf60972a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Tiendas provincias' or . = 'Tiendas provincias')]</value>
      <webElementGuid>47287f8c-fcdf-4d3c-a7a7-8222485a6de3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
