<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Consulta Envio_iframeConsultaEnvio</name>
   <tag></tag>
   <elementGuidId>ca8053cf-636d-4f3f-a878-aa570eacf151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeConsultaEnvio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeConsultaEnvio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c22bf58d-017f-4c32-8a21-46f4af0151f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeConsultaEnvio</value>
      <webElementGuid>07b35348-f1df-4cb8-9a15-108a371d8a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>9a885777-eeb2-49c6-a2cb-49f76c15e805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>popup/maestroWeb/consultaEnvio.xhtml</value>
      <webElementGuid>fd0c0253-7a07-4c0d-b615-ce06413a7f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeConsultaEnvio&quot;)</value>
      <webElementGuid>80d6a1bd-5fa7-44cb-8ca1-beb7602f12b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeConsultaEnvio']</value>
      <webElementGuid>f9881d2b-be38-47ec-8634-e2f150f67c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgConsultaEnvio']/div[2]/iframe</value>
      <webElementGuid>3a693a81-0d0d-4373-834b-7e9376e24a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>3d1ad9dc-4a0f-4493-87b0-b6f488994a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeConsultaEnvio' and @src = 'popup/maestroWeb/consultaEnvio.xhtml']</value>
      <webElementGuid>b20b907a-62c4-44c7-93ec-7d57fc97b18c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
