<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Razn Social_txt_razon_social</name>
   <tag></tag>
   <elementGuidId>493dfe25-156a-45ed-8811-3107730c5070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_razon_social</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_razon_social']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b52c62b9-c106-400f-b805-4482fbb2b824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e0724ec-e305-4028-bda4-41b6a070fd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputRE</value>
      <webElementGuid>c1fe970c-6f13-49f7-9d31-8bdba6060033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_razon_social</value>
      <webElementGuid>0e683cdb-80dd-42d2-b085-9ba2d21ce392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RAZÓN SOCIAL</value>
      <webElementGuid>4bc5a26f-8618-4166-bac9-05244a9ee694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_razon_social&quot;)</value>
      <webElementGuid>f7ed7a9b-c230-47a4-afeb-d7fd908247ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_razon_social']</value>
      <webElementGuid>99d6cd95-df0d-4564-aa16-5c962d47e1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoCliente']/div/div/div[2]/div[7]/div/input</value>
      <webElementGuid>72902a56-d4a6-49be-8379-271e62b1752d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>4f18a0dc-9147-425b-8cb4-504bb28e9d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_razon_social' and @placeholder = 'RAZÓN SOCIAL']</value>
      <webElementGuid>696b5284-ccfe-4e85-9fae-42dc807274fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
