<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S_frmVentaContadotblEnvio0j_idt105</name>
   <tag></tag>
   <elementGuidId>5096c47f-8479-4cee-84c4-bfe1e5087bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@src='/OlvaERP-Maestro-web/img/icon/editPencil.png']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a49db7b9-6811-458f-9da9-01b47909b3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmVentaContado:tblEnvio:0:j_idt105</value>
      <webElementGuid>d4b2bbf4-1ce4-4f42-9348-8e37d32466b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>4040bae2-3002-4e91-967e-930327e29ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/img/icon/editPencil.png</value>
      <webElementGuid>6e9906ec-dffa-42bb-863e-deb56c6ebdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmVentaContado:tblEnvio:0:j_idt105</value>
      <webElementGuid>b248655b-e154-49e5-9f0b-0910440a8f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>editar</value>
      <webElementGuid>1a86f3ae-329e-45ff-9656-fc6918942eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;action&quot;,p:&quot;frmVentaContado:tblEnvio:0:j_idt105&quot;,u:&quot;frmNewEnvio:tooltip-content-wrapper frmNewEnvio:articuloTbl frmFocus:fcNewEnvio frmNewEnvio:servicio frmNewEnvio:somDirecOfi frmNewEnvio:volumen&quot;,onco:function(xhr,status,args){change(xhr, status, args); PF('dialogNewEnvio').show();;}});;return false</value>
      <webElementGuid>6d4baba7-bf3c-4d3b-bd26-9fe71c8877cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmVentaContado:tblEnvio:0:j_idt105&quot;)</value>
      <webElementGuid>51688569-d1f0-42e4-bada-bf085a49223a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Negativo/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal_1</value>
      <webElementGuid>ad26dd34-dea2-4674-aac8-2af1cca3283b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmVentaContado:tblEnvio:0:j_idt105']</value>
      <webElementGuid>b924070f-de1a-4f5a-8f68-0a9e64996f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='frmVentaContado:tblEnvio_data']/tr/td[2]/input</value>
      <webElementGuid>bef2ca90-2764-4695-8bd3-0c03c7acf857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>aeebbfe1-01b4-45dc-a8f9-7c631d65f689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmVentaContado:tblEnvio:0:j_idt105' and @type = 'image' and @src = '/OlvaERP-Maestro-web/img/icon/editPencil.png' and @name = 'frmVentaContado:tblEnvio:0:j_idt105' and @title = 'editar']</value>
      <webElementGuid>7623257b-4bb4-423f-ae4d-da22d585f4d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
