<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EFECTIVO_frmTipoComprobanteefectivo</name>
   <tag></tag>
   <elementGuidId>e9a0f6c9-7800-45c2-a2f9-b137e4065631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'frmTipoComprobante:efectivo' and @name = 'frmTipoComprobante:efectivo' and @type = 'text' and @placeholder = 'S/. ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce05d194-7c9f-466e-9c82-a2b2d22347e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmTipoComprobante:efectivo</value>
      <webElementGuid>b8c03808-ee00-48d4-b672-dd4a95008b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmTipoComprobante:efectivo</value>
      <webElementGuid>8e210e8e-01f6-4ade-bc62-ce64dd18f475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3da92be-5e9e-4b3c-b394-1cc6941590ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>S/. </value>
      <webElementGuid>50030156-4a6f-4c33-81a2-138a2283d85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                                                          btnEfectivo();                                                          focusChange('#frmTipoComprobante\\:cbtnGrabarVenta');                                                          return false;                                                      }</value>
      <webElementGuid>a685b9b7-e4bd-4080-be86-b45567afb323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>btnEfectivo();</value>
      <webElementGuid>6ee702f9-4763-47b7-8fe4-cd7fce626053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>d3a8c02b-98c1-46a0-ac01-d4d799fb3e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e5a4e629-d86c-4bec-865d-0d6274b39bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d7ea1df9-7655-41ce-9731-f3fbfeead36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05d4c281-4e8f-480d-ae62-5298a79d0ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmTipoComprobante:efectivo&quot;)</value>
      <webElementGuid>7697aeef-75d0-4a89-bcb6-e5ffcf33043c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Distribucion/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>2ba2ba4d-db5e-4542-a685-9971926b1d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Negativo/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal (3)</value>
      <webElementGuid>7e375eda-c42a-4db7-abb9-a97adf8ebb5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmTipoComprobante:efectivo']</value>
      <webElementGuid>f55346c1-bc14-4650-a226-9abf1b4714ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmTipoComprobante:pnlEfectivo_content']/table/tbody/tr/td[3]/input</value>
      <webElementGuid>7eac8eca-2d37-4d64-bd99-947518336205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td[3]/input</value>
      <webElementGuid>801aa105-2c58-4047-b542-7b8e1a63ecda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmTipoComprobante:efectivo' and @name = 'frmTipoComprobante:efectivo' and @type = 'text' and @placeholder = 'S/. ']</value>
      <webElementGuid>054cb873-008a-4841-a67f-3a70c3db88e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
