<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Zona Clientes</name>
   <tag></tag>
   <elementGuidId>9ede9df8-88af-4f90-8480-a7becbd5388e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.client-zone-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Regístrate aquí'])[1]/following::span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a95434fd-8e16-4e1e-a9c2-b4a20b9204e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>client-zone-txt</value>
      <webElementGuid>8391bbc4-f713-4ae6-8e05-98a6b060c78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zona Clientes</value>
      <webElementGuid>3046c844-9eaa-4bee-b7e3-6fe65cad942c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrap&quot;]/div[@class=&quot;client-zone&quot;]/span[@class=&quot;client-zone-txt&quot;]</value>
      <webElementGuid>7178ef25-a6f3-4cc9-aff2-a0d76ea8e04c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regístrate aquí'])[1]/following::span[3]</value>
      <webElementGuid>baa6fce1-c5d8-46eb-bfae-8b99736538a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_left'])[1]/preceding::span[1]</value>
      <webElementGuid>b417ed65-cb0d-44d6-a759-2351553c8e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ir a Olva'])[1]/preceding::span[1]</value>
      <webElementGuid>fff622a8-8f7a-443e-b508-64091e342a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zona Clientes']/parent::*</value>
      <webElementGuid>967db993-6f7d-48a0-88ba-7483e4d57548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>c32adf27-8b60-4500-adc6-ac121cccbb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Zona Clientes' or . = 'Zona Clientes')]</value>
      <webElementGuid>be4cf13c-ddd6-4395-9691-958ead5a81fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
