<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Name  QA1Automation1Log outISBN  9_94a850</name>
   <tag></tag>
   <elementGuidId>e4a9ca66-106a-43c4-82dd-9f8ee1974097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.books-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>220fa38a-374d-4e00-a81e-64f2a4eee29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>books-wrapper</value>
      <webElementGuid>70172547-6d1c-4a7b-a122-c48b484dc817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name : QA1Automation1Log outISBN : 9781449325862Title : Git Pocket GuideSub Title : A Working IntroductionAuthor : Richard E. SilvermanPublisher : O'Reilly MediaTotal Pages : 234Description : This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git expWebsite : http://chimera.labs.oreilly.com/books/1230000000561/index.htmlBack To Book StoreAdd To Your Collection</value>
      <webElementGuid>dbbb778b-9c52-4ff5-ae4b-964cbe40552a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;container playgound-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mt-4 col-md-6&quot;]/div[@class=&quot;books-wrapper&quot;]</value>
      <webElementGuid>788e565b-277d-43b2-a1a3-bcca03d6f927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>61254d58-8691-4cc9-846d-4971cb6dd5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[4]</value>
      <webElementGuid>7be80d02-639a-428c-b451-8286fda5eda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[4]</value>
      <webElementGuid>75d02e75-1c1c-48fb-bc00-2732f05a4b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>b0ab712c-1007-4305-b6d8-df77ee820f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;User Name : QA1Automation1Log outISBN : 9781449325862Title : Git Pocket GuideSub Title : A Working IntroductionAuthor : Richard E. SilvermanPublisher : O&quot; , &quot;'&quot; , &quot;Reilly MediaTotal Pages : 234Description : This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git expWebsite : http://chimera.labs.oreilly.com/books/1230000000561/index.htmlBack To Book StoreAdd To Your Collection&quot;) or . = concat(&quot;User Name : QA1Automation1Log outISBN : 9781449325862Title : Git Pocket GuideSub Title : A Working IntroductionAuthor : Richard E. SilvermanPublisher : O&quot; , &quot;'&quot; , &quot;Reilly MediaTotal Pages : 234Description : This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git expWebsite : http://chimera.labs.oreilly.com/books/1230000000561/index.htmlBack To Book StoreAdd To Your Collection&quot;))]</value>
      <webElementGuid>dbc867ee-2e56-41cb-9f29-60dbe3d0b886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
