<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Area_reg</name>
   <tag></tag>
   <elementGuidId>9165d3c9-f514-42af-9a86-46a4262f7232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@value,'REGULAR')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4917d995-9fd2-4ff6-a0d6-53ee0169b4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConsultaEnvio:panelEnvio:base</value>
      <webElementGuid>b6a6683e-3ece-4e87-8b32-90e89dbd666e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6,19</value>
      <webElementGuid>eaae3ac8-a4d7-49b1-a51c-d8bb1ed74497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConsultaEnvio:panelEnvio:base&quot;)</value>
      <webElementGuid>7c0c09ce-de84-4596-b0e4-45f77c0f8fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Page_Principal - Olva Courier/iframe_Consulta Envio_iframeConsultaEnvio</value>
      <webElementGuid>1fa2c025-bfcd-4f7c-95cd-3f8268c79b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmConsultaEnvio:panelEnvio:base']</value>
      <webElementGuid>0fd304aa-d1d4-40da-aa5b-9d8e53bc617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='frmConsultaEnvio:panelEnvio:j_idt385']/div/table/tbody/tr/td[3]/span</value>
      <webElementGuid>672537ec-283f-4cb1-afd9-c09f01956be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[1]/following::span[1]</value>
      <webElementGuid>5071183f-5de3-4185-a072-7d3f5e21aab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BASE:'])[1]/following::span[2]</value>
      <webElementGuid>b4c93ea9-1b1b-4413-818a-4b34e18d5f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXCESO:'])[1]/preceding::span[1]</value>
      <webElementGuid>db1b3ffe-6d83-4eb6-bbbb-ce264ad98da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[2]/preceding::span[1]</value>
      <webElementGuid>e352760a-1d2d-48c3-a356-89f8c0d01b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6,19']/parent::*</value>
      <webElementGuid>2b7bda6a-9e44-45ff-92ce-990396190395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[3]/span</value>
      <webElementGuid>817054de-0612-456f-9fbf-a9ef3d0187ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmConsultaEnvio:panelEnvio:base' and (text() = '6,19' or . = '6,19')]</value>
      <webElementGuid>9cd29e7e-8dc8-4dc4-b87d-664b04949606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
