<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Pago con tarjeta de crdito, dbito y yape</name>
   <tag></tag>
   <elementGuidId>813804f4-04ad-465c-9a92-33484aba14e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pago1&quot;]/div[1]/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pago2 > div.col-md-12 > i.fa.fa-circle-o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>916377d6-10d9-4860-b7f0-6c242ea800cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-circle-o</value>
      <webElementGuid>392652f5-4d92-415d-aa7a-7c66a2f8005a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pago2&quot;)/div[@class=&quot;col-md-12&quot;]/i[@class=&quot;fa fa-circle-o&quot;]</value>
      <webElementGuid>e17c760e-df5f-4143-9393-83cd30a947f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pago2']/div/i</value>
      <webElementGuid>fd845cd2-7b7d-49e1-a676-146ec6227ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/i</value>
      <webElementGuid>bc7a453a-69c5-4b9d-91f7-eecddc8825eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
