<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clientes</name>
   <tag></tag>
   <elementGuidId>23e470bc-e1c8-4bd3-96a3-b7b5716f29de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ui-menuitem-link.ui-corner-all.modelLayoutHeadItem.blockable.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=concat('PrimeFaces.ab({s:&quot;frmPrincipal:model&quot;,u:&quot;frmPrincipal:tree frmPrincipal:centerContentPanel&quot;,g:false,onst:function(cfg){PF(',&quot;'blockUIWidget1').block();},onco:function(xhr,status,args){PF('blockUIWidget1').unblock();},pa:[{name:&quot;,'&quot;idCodFormMod&quot;,value:&quot;06&quot;},{name:&quot;frmPrincipal:model_menuid&quot;,value:&quot;5&quot;}],f:&quot;frmPrincipal&quot;});return false;')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e7ae3f9-8b35-4015-a6b9-260f7021a994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6670d110-bb24-4832-a038-3b48b30de77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menuitem-link ui-corner-all modelLayoutHeadItem blockable ui-state-hover</value>
      <webElementGuid>0c86023a-89bb-4ba0-89df-e795ccf5e0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>30961b12-b95f-4491-876a-349372773624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmPrincipal:model&quot;,u:&quot;frmPrincipal:tree frmPrincipal:centerContentPanel&quot;,g:false,onst:function(cfg){PF('blockUIWidget1').block();},onco:function(xhr,status,args){PF('blockUIWidget1').unblock();},pa:[{name:&quot;idCodFormMod&quot;,value:&quot;06&quot;},{name:&quot;frmPrincipal:model_menuid&quot;,value:&quot;5&quot;}],f:&quot;frmPrincipal&quot;});return false;</value>
      <webElementGuid>310dd846-64a1-43f1-86dc-f466ec9082ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clientes</value>
      <webElementGuid>25d12aab-6fae-4661-be98-6b15ca36da40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:model&quot;)/ul[@class=&quot;ui-menu-list ui-helper-reset&quot;]/li[@class=&quot;ui-menuitem ui-widget ui-corner-all ui-menuitem-active&quot;]/a[@class=&quot;ui-menuitem-link ui-corner-all modelLayoutHeadItem blockable ui-state-hover&quot;]</value>
      <webElementGuid>2669bbb0-220e-4f03-83e9-708b73d885ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=concat('PrimeFaces.ab({s:&quot;frmPrincipal:model&quot;,u:&quot;frmPrincipal:tree frmPrincipal:centerContentPanel&quot;,g:false,onst:function(cfg){PF(',&quot;'blockUIWidget1').block();},onco:function(xhr,status,args){PF('blockUIWidget1').unblock();},pa:[{name:&quot;,'&quot;idCodFormMod&quot;,value:&quot;06&quot;},{name:&quot;frmPrincipal:model_menuid&quot;,value:&quot;5&quot;}],f:&quot;frmPrincipal&quot;});return false;')]</value>
      <webElementGuid>257f36e1-aa22-47a3-8320-56156b270fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPrincipal:model']/ul/li[6]/a</value>
      <webElementGuid>a1abec8b-a351-4f3f-af3d-d860389eca03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cobranzas'])[1]/following::a[1]</value>
      <webElementGuid>2a958541-1599-4f02-8845-1cc10864b5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distribucion'])[1]/following::a[2]</value>
      <webElementGuid>4c2e8233-e4a3-4b73-85ea-6b090d01fa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención Cliente'])[1]/preceding::a[1]</value>
      <webElementGuid>3e2c3e8a-5ac1-458e-aea4-e5775c854881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>a6f80f6b-54f5-4378-8779-aaa4b4ecb839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>85fdcb73-586b-4e0c-865f-d78c255fb585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Clientes' or . = 'Clientes')]</value>
      <webElementGuid>93d5d7ca-cb19-4203-b707-12d8a646028d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
