<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Listar (6)</name>
   <tag></tag>
   <elementGuidId>afd8d85f-5f14-48b8-a72c-472be616fbd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71fede72-d558-4b2d-a6aa-378552e77357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn waves-effect waves-light search-button</value>
      <webElementGuid>6280244d-86c8-4763-ae52-cd7811ea418f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>379f5737-5d50-495d-a978-603b54d56cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>sendFormStatistics(document.querySelector('#statisticsform'))</value>
      <webElementGuid>5682270f-cbe4-4da7-a929-eb28807cf353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listar
                            </value>
      <webElementGuid>2610ca83-5194-4869-85a7-d0e84fc078b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statisticsform&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col s12 m12 l12&quot;]/div[@class=&quot;col s12 m3 l2&quot;]/div[@class=&quot;input-field&quot;]/a[@class=&quot;btn waves-effect waves-light search-button&quot;]</value>
      <webElementGuid>afbb437c-d292-4c23-a423-ea575621989d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='action']</value>
      <webElementGuid>e5a01638-e102-408b-96ee-a3367df03c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='statisticsform']/div/div/div[8]/div/a</value>
      <webElementGuid>31766dfc-9147-4c94-8860-343adc0b27a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Listar')]</value>
      <webElementGuid>35a3b5f4-0a01-4b8a-b865-f6cb9621d5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Reporte'])[1]/following::a[1]</value>
      <webElementGuid>cfb46e09-fb30-4a95-950f-090177c9e101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incluir Motivos Cliente'])[1]/following::a[1]</value>
      <webElementGuid>ba38e829-ad6b-4329-9dad-f45ec59f3e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/preceding::a[1]</value>
      <webElementGuid>c7407855-02c7-48a0-a36b-fdf7ebe26c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad'])[1]/preceding::a[1]</value>
      <webElementGuid>3bcd23cb-ebb3-4393-a7a7-84a85a116a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Listar']/parent::*</value>
      <webElementGuid>3432a1ab-5454-40c6-8fa3-355a7d7f49cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/a</value>
      <webElementGuid>cf2ba786-66b8-4dd9-9b08-72a6d8216bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'action' and (text() = 'Listar
                            ' or . = 'Listar
                            ')]</value>
      <webElementGuid>93080dad-12f3-4824-8976-2fc7ea14c700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
