<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Listar (3)</name>
   <tag></tag>
   <elementGuidId>db963d5a-1978-4924-9822-d5b1d255b867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5452f576-f6a0-4211-ae4b-acd8b12e0363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn waves-effect waves-light search-button</value>
      <webElementGuid>371fd08c-a11e-4cf2-8d86-0684385c03b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>9e1dc2c7-495d-4495-86d7-b04c470aac67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>validateSearchPick(document.querySelector('#historyform'))</value>
      <webElementGuid>aa9a03a5-5152-48ee-8c80-5f51be915ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listar
                        </value>
      <webElementGuid>d1d34a55-ec47-4baf-a9b2-18139b183cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historyform&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col s12 m6 l6&quot;]/div[@class=&quot;input-field&quot;]/a[@class=&quot;btn waves-effect waves-light search-button&quot;]</value>
      <webElementGuid>e2039eb5-8d21-4959-9357-3936deb1e961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='action']</value>
      <webElementGuid>30fc5a13-28de-4bbe-a918-fd287b176cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='historyform']/div/div[2]/div/a</value>
      <webElementGuid>77549100-881b-4517-a1ed-fdfb007fd970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Listar')]</value>
      <webElementGuid>cfa35a9c-b0fc-4349-8514-b96ed11e9389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='date_range'])[3]/following::a[1]</value>
      <webElementGuid>e070e8d5-9265-43dd-89f4-bee5530c3956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='id'])[1]/preceding::a[1]</value>
      <webElementGuid>351a32df-bdf6-44d1-8d4b-63470e6e871e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Registro'])[1]/preceding::a[1]</value>
      <webElementGuid>5b196029-d21e-44de-bb57-84c0ad35c325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Listar']/parent::*</value>
      <webElementGuid>7771b7ef-663a-4b9d-b10c-8dcfb7af3698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/a</value>
      <webElementGuid>3cc0e959-99d4-48f9-a6e5-807c2a1f1d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'action' and (text() = 'Listar
                        ' or . = 'Listar
                        ')]</value>
      <webElementGuid>e17ae865-e4a0-440e-8a6e-5353e534068c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
