<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Yape</name>
   <tag></tag>
   <elementGuidId>be24d307-d344-48b7-a224-fbfd65691e5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='../assets/img/yape.jpeg'][contains(@id,'yape')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>e34bfd68-f504-414d-a63d-1e621fb25189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yape</value>
      <webElementGuid>b6281852-d121-4810-a916-1dbd5a22d7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldset_paso6&quot;)/div[@class=&quot;row&quot;]/h4[1]/div[1]/b[2]</value>
      <webElementGuid>a68d73f9-3124-4213-979e-43ac0e871bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso6']/div/h4/div/b[2]</value>
      <webElementGuid>102d66cb-5d50-4905-8fd8-ed14cae0ca01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pago de la diferencia'])[1]/following::b[1]</value>
      <webElementGuid>9dba73d3-ec36-4616-8a04-c4e0b7a1b289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[2]/preceding::b[1]</value>
      <webElementGuid>7afd828f-8b15-4316-a9d7-e95207f9968e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yape']/parent::*</value>
      <webElementGuid>5de731ed-32e4-4bd4-a9f2-455730f911cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b[2]</value>
      <webElementGuid>fb43a7fb-4f14-42b7-a5bd-0cb1c99a8543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Yape' or . = 'Yape')]</value>
      <webElementGuid>5df13bf8-b65d-4728-b257-7c6589fe0a16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
