<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Entrar (23)</name>
   <tag></tag>
   <elementGuidId>c767bb8b-d9b2-41f5-9f32-80a98f7f7b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='login-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64491696-5735-48ac-91c8-1587139080b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-button</value>
      <webElementGuid>0bed492b-4b4c-4d63-a352-0f315be94515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-btn</value>
      <webElementGuid>bf437358-8829-4090-b67d-8b4ee2a0b643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4cf1d206-bf24-471b-ab5f-9fb12483b36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrar</value>
      <webElementGuid>4e882db9-f95e-447a-9b44-1fe2071d1f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-btn&quot;)</value>
      <webElementGuid>9cda4eed-b601-4479-8162-7a873aca34ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='login-btn']</value>
      <webElementGuid>795342db-8955-42e6-aed3-34b846c7d0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZONA CLIENTES'])[1]/following::button[1]</value>
      <webElementGuid>156d2971-f371-4b0a-a139-37ac172f2592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrar envío'])[1]/following::button[1]</value>
      <webElementGuid>2ab1bbcb-1ff2-4b65-921c-f5e205cb36b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Olvidé mi contraseña'])[1]/preceding::button[1]</value>
      <webElementGuid>903dbd71-4a6d-4cd0-834c-81033a43012b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar']/parent::*</value>
      <webElementGuid>437c9119-6ea6-4698-a1b8-b7de35a6eac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/button</value>
      <webElementGuid>e5081b97-4875-4a78-9559-65767c856015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'login-btn' and @type = 'submit' and (text() = 'Entrar' or . = 'Entrar')]</value>
      <webElementGuid>90c7942d-4881-4d88-840c-4f3452e05957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
