<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PROVINCIA (1)</name>
   <tag></tag>
   <elementGuidId>cf474e25-7fa7-4fdc-8ca0-ce9f44815a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_provincia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_provincia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05922bde-3502-48ab-8d37-2ee98bd42581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-size</value>
      <webElementGuid>1564cadc-9b76-4fb2-af3c-73fa24310176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_provincia</value>
      <webElementGuid>54825036-0f23-4396-8721-d93218b0e070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROVINCIA</value>
      <webElementGuid>53b52ad1-7afa-4dbc-b171-d49e59592019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_provincia&quot;)</value>
      <webElementGuid>0204f2cf-2b1f-4c60-91f8-2ccd451ba4eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_provincia']</value>
      <webElementGuid>c0ec6c37-71d0-42ea-b8bc-a2ea8fbcaf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_buttons']/button[2]</value>
      <webElementGuid>5f6640a8-bd1e-485a-afc6-59348e9f9dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA'])[1]/following::button[1]</value>
      <webElementGuid>3e7e7db8-7848-49db-baa6-15e70d040216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Dónde te encuentras?'])[1]/following::button[2]</value>
      <webElementGuid>62696187-c5f1-4326-b723-9d79167ce45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[2]/preceding::button[1]</value>
      <webElementGuid>8d911430-f21b-42e8-b0fc-022b3a348d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[3]/preceding::button[2]</value>
      <webElementGuid>3295c2ab-27f5-4781-9830-53d6dbf7335c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROVINCIA']/parent::*</value>
      <webElementGuid>e2489dd2-0a56-4910-8817-749997a674d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>0b002e7a-aade-48e2-8783-d291978697f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_provincia' and (text() = 'PROVINCIA' or . = 'PROVINCIA')]</value>
      <webElementGuid>b40b0f37-7f8f-45c6-b846-ecd90011b4fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
