<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Programa tu recojo (8)</name>
   <tag></tag>
   <elementGuidId>09f1dfd5-0aa7-474c-8044-f58ebc6518af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-service</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-service']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c961384-e9f4-449a-89a5-ed0656e45909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-service</value>
      <webElementGuid>b320a55f-9c97-4a11-a11d-e483b2b03abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3be43fb2-3a6c-45d0-9177-d6712bfb482c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn v-step-16 btn-success has-tooltip v-tooltip-open</value>
      <webElementGuid>03c1417f-50f8-4d0c-9403-40472f94eac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip_766krkqdng</value>
      <webElementGuid>c8ce02ce-345e-45c9-b913-65ae225e7389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programa tu recojo</value>
      <webElementGuid>7cef42dc-3e72-4e8b-ad1e-77b9688ceca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-service&quot;)</value>
      <webElementGuid>9ae726c7-6d8e-49b2-9cc9-9818aa463144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-service']</value>
      <webElementGuid>93fe3f1b-be09-4f64-b492-2f8f86e7382b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-form-vue']/div/form/button[2]</value>
      <webElementGuid>a0c0688a-66be-45f9-814f-bebd7acc6ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/following::button[1]</value>
      <webElementGuid>afb3633d-b32e-45e6-b74a-8f8d0b9097de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor del recojo'])[1]/following::button[2]</value>
      <webElementGuid>e690b469-8647-48e3-87ed-0d56b6e05b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::button[1]</value>
      <webElementGuid>8fe2c868-7b04-4959-89f4-1804b9d1dbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Programa tu recojo']/parent::*</value>
      <webElementGuid>72df97af-5c6d-49a5-a1a7-fad225ff4551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>515dee6b-374e-4050-a4a3-9aad694096dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-service' and @type = 'submit' and (text() = 'Programa tu recojo' or . = 'Programa tu recojo')]</value>
      <webElementGuid>2f1c0ae5-e452-45b8-9311-6d85d60622ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
