<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_IR A PAGAR S 14.42</name>
   <tag></tag>
   <elementGuidId>fbabc57f-4048-42fd-a351-a7afe4bba316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-listar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar-listar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec2c7123-eca1-4c3f-bd2e-fce5f77328b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-listar</value>
      <webElementGuid>74668dc3-8bf6-4628-94ad-7ee9405b5d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>14.42</value>
      <webElementGuid>6d4ce69b-9e04-4ac6-a407-d5c43ffc9297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0a3a23e-a752-4d0d-949a-8f6ae9be5b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>ef25ff0d-675b-4c3d-b6fb-c54aad369a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IR A PAGAR S/ 14.42</value>
      <webElementGuid>ca0caafb-e645-49cc-b655-d2f10f6ab0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-listar&quot;)</value>
      <webElementGuid>c8439124-3a27-4e0c-8575-7235da2de666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-listar']</value>
      <webElementGuid>b8655f7f-6f7d-4465-b3cd-347c3c299b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_pagar']/button</value>
      <webElementGuid>643d4324-ae3f-47ed-9e10-43a8a4abf8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/following::button[1]</value>
      <webElementGuid>ce7fb9b8-9c75-4832-a939-ac9fd39fcd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/following::button[1]</value>
      <webElementGuid>8d306e06-cb73-456e-b80d-94a575b808d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿A dónde retornamos el cargo adjunto ?'])[1]/preceding::button[2]</value>
      <webElementGuid>711e1ee7-1d3e-4ad4-9b85-003fab01b408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de entrega'])[3]/preceding::button[2]</value>
      <webElementGuid>3e7c0493-954b-4112-bed9-73c431d87970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IR A PAGAR S/ 14.42']/parent::*</value>
      <webElementGuid>2d53f3d4-6f83-4700-abba-17e776017c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>67817d08-81c8-4617-81c9-0c0f73f6a9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-listar' and @type = 'button' and (text() = 'IR A PAGAR S/ 14.42' or . = 'IR A PAGAR S/ 14.42')]</value>
      <webElementGuid>49af9942-81b6-4bb0-9a62-02cd6d210055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
