<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Validar (1)</name>
   <tag></tag>
   <elementGuidId>34acac5f-22f0-4ae9-9321-3f484cb4e066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_validar_digitor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_validar_digitor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2362b928-e75a-4a40-ad89-488097eb04f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a7b4b03-475d-4673-ba0c-beb7dc78de54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_validar_digitor</value>
      <webElementGuid>0320e36c-9497-4cb1-9d0c-c917511c7048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>83cdd459-ad70-4dcc-a6b9-ca359357f30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Validar</value>
      <webElementGuid>9de79319-acce-49fe-8d10-a1282c5a38f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_validar_digitor&quot;)</value>
      <webElementGuid>c61c6fe7-7bb5-40d5-a877-9e08c32d5fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_validar_digitor']</value>
      <webElementGuid>d89978c2-a3f1-4b67-9ed0-85d48133a185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoDigitoVerificador']/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>b97fe06a-4f82-4d3f-af94-3cb3c8ecd0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::button[1]</value>
      <webElementGuid>f70da22e-5417-4b75-821c-fd1e182527c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El apellido ingresado debe ser igual al registrado en su DNI'])[1]/following::button[2]</value>
      <webElementGuid>9eebf7bd-9379-4369-b294-d58c8a38f0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente Nuevo'])[1]/preceding::button[1]</value>
      <webElementGuid>f74a674e-5397-4741-8052-c9f46ec47305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Persona'])[1]/preceding::button[2]</value>
      <webElementGuid>e421d8d0-eccb-4897-90fd-79b8e1daa54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Validar']/parent::*</value>
      <webElementGuid>0aeb3967-a25d-415e-a6cb-5e5fd936f3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>3417513b-2180-4760-ac99-324369a67514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_validar_digitor' and (text() = ' Validar' or . = ' Validar')]</value>
      <webElementGuid>b6d8df9e-929f-47c7-8adf-c1deed6a684e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
