<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Guardar</name>
   <tag></tag>
   <elementGuidId>976bd1a5-b541-4e35-b367-30607ccabf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-button-profile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#save-button-profile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40a17aea-edbf-4328-b825-113686d50c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7ec638b-d6d8-4407-9280-60b40ff5bf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt10 btn waves-effect waves-light</value>
      <webElementGuid>0ddfc780-a6cb-4922-bd1f-ef89cc64e90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-button-profile</value>
      <webElementGuid>a7870e3b-d9e5-4e28-967f-d218b232e685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>b31b9f0c-2d5a-46ad-8d17-73e33eaddfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-button-profile&quot;)</value>
      <webElementGuid>542098f5-efa9-46bd-ba76-93e2ead64d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-button-profile']</value>
      <webElementGuid>72813ae7-52e2-42d9-a47f-27cc4b9bae97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefono:'])[1]/following::button[1]</value>
      <webElementGuid>b017650a-d64d-40aa-8b5f-1d5707f6ebfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTADO'])[1]/following::button[1]</value>
      <webElementGuid>c5b971e3-b96c-4920-a318-dece8c3a3f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'save-button-profile', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>d412edbe-574c-4216-b16c-1e1b5820e704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar']/parent::*</value>
      <webElementGuid>c0c9d80f-3172-4be6-934b-7ea86f8f48d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>db994b20-caee-4f6c-8b94-ad75d37e33f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'save-button-profile' and (text() = 'Guardar' or . = 'Guardar')]</value>
      <webElementGuid>c718ee92-225d-4f1f-a6b9-ae57bed181ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
