<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_14</name>
   <tag></tag>
   <elementGuidId>67b3b38b-ea46-4c59-93de-3bb0d374f356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[52]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66ce06b5-b486-4300-97a9-3918c7356a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-day-button</value>
      <webElementGuid>36d08dda-c1e1-4e65-b735-3da0e09237c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fed6e97-027c-4efc-84f9-1d05a59ecb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-year</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>14d987c5-6e6c-412b-bb4f-c82642fe4bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-month</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0746ac68-93d0-466a-9e67-f12dc78cebb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-day</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0886967f-0705-44ec-ad62-fdad6c235f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>e6ffbcdc-1c8d-4c4b-b0c0-88934cad37ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-af7b80a0-e4ed-c220-f7cb-b646bdc15e78&quot;)/div[@class=&quot;modal-content datepicker-container&quot;]/div[@class=&quot;datepicker-calendar-container&quot;]/div[@class=&quot;datepicker-calendar&quot;]/div[@class=&quot;datepicker-table-wrapper&quot;]/table[@class=&quot;datepicker-table&quot;]/tbody[1]/tr[@class=&quot;datepicker-row&quot;]/td[3]/button[@class=&quot;datepicker-day-button&quot;]</value>
      <webElementGuid>dac78998-088a-46b6-80d2-008cccf32263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[52]</value>
      <webElementGuid>969e3d95-641c-4a1c-8d78-6e84e08ab2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-af7b80a0-e4ed-c220-f7cb-b646bdc15e78']/div/div[2]/div/div[2]/table/tbody/tr[3]/td[3]/button</value>
      <webElementGuid>a7395813-1c57-4656-a325-c73b215a600b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[2]/following::button[14]</value>
      <webElementGuid>4e532697-5d05-41ba-ae02-20d6ba89a321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::button[14]</value>
      <webElementGuid>db51e973-db95-4df4-92f7-83770e816879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/preceding::button[18]</value>
      <webElementGuid>80c6e6e1-4a87-487c-9aff-0cf501fddc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[2]/preceding::button[19]</value>
      <webElementGuid>70f0e0bd-d786-4d5c-8c79-18d31539509e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[3]/td[3]/button</value>
      <webElementGuid>1429590a-76bb-4152-837d-a598ac1fae43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '14' or . = '14')]</value>
      <webElementGuid>c1f84f72-3e9d-4810-97a9-a07e6a170115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
