<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Per, Santiago de Surco, Avenida Los _7b1755</name>
   <tag></tag>
   <elementGuidId>5bb5fa0b-8194-4f1c-8091-6b84333c7905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c75d0b14-33b0-4619-ab57-3d82e8c273b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action addressListDetail</value>
      <webElementGuid>297f5811-8a2d-419d-8d4c-6e759ab82e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb8018ac-0ad6-49bc-bc46-83262b24d98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perú, Santiago de Surco, Avenida Los Próceres Cuadra 4</value>
      <webElementGuid>7543dab4-19a0-48a8-ab26-1d5b2a22c175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__220841___BV___&quot;)/div[1]/div[@class=&quot;list-group addressList mt-2&quot;]/button[@class=&quot;list-group-item list-group-item-action addressListDetail&quot;]</value>
      <webElementGuid>c9a0bfba-013e-42fc-82f9-1aed5bdb3ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Aceptar_iframe_response</value>
      <webElementGuid>daa88709-5798-4a0b-b033-9609e0ce13ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>d0cbc725-d01c-4aed-950d-b7580678e1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__220841___BV___']/div/div/button[5]</value>
      <webElementGuid>f32ec92e-061c-4179-87a8-68f934b1a1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fija la dirección en el mapa'])[1]/preceding::button[1]</value>
      <webElementGuid>ce3d1f5d-2d92-48f0-aabd-d3cef6e0e5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perú, Santiago de Surco, Avenida Los Próceres Cuadra 4']/parent::*</value>
      <webElementGuid>cf08e4d1-dd6f-4bae-afa7-e552ac3f5683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>1e16f6c2-123c-45ac-8f33-5e9917fa4474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Perú, Santiago de Surco, Avenida Los Próceres Cuadra 4' or . = 'Perú, Santiago de Surco, Avenida Los Próceres Cuadra 4')]</value>
      <webElementGuid>38d02866-4d28-465f-8a55-a9054552daab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
