<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Programa tu recojo (4)</name>
   <tag></tag>
   <elementGuidId>728cb3d9-147d-40ed-8b04-9028768ad581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-service']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#save-service</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7233bc6d-2400-4b9c-a3ae-4894ed17d1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-service</value>
      <webElementGuid>a77dbfc2-0c0f-4d15-8f0a-53053e077686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>24e29276-6806-4e92-9ec2-f11871625ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn v-step-16 btn-success has-tooltip v-tooltip-open</value>
      <webElementGuid>6cf029fa-a3d5-4864-89ae-4d8e744a9cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip_dsn007czfq</value>
      <webElementGuid>7d460e65-171d-4ad1-ac3b-204e21cdf530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programa tu recojo</value>
      <webElementGuid>68849279-a48a-4b5c-8c66-2b7dfe4e94d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-service&quot;)</value>
      <webElementGuid>658ca1ad-063d-4769-9e2b-be0b1e2e3bac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-service']</value>
      <webElementGuid>bf8d8643-0139-42c9-9f25-bac967d5a4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-form-vue']/div/form/button[2]</value>
      <webElementGuid>2a93b20f-9dbe-4a4a-a5ed-3c7cfcf42a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/following::button[1]</value>
      <webElementGuid>5ca099e2-6efd-4f0a-b7d0-851c75e597d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor del recojo'])[1]/following::button[2]</value>
      <webElementGuid>f1d53772-13c1-48de-80af-de7a81578c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::button[1]</value>
      <webElementGuid>974a4dd6-9edb-46b4-8d2e-ae2e2430132c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Programa tu recojo']/parent::*</value>
      <webElementGuid>46fb46fc-b07d-4d32-a835-6962c8ccea6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7e8de0b2-4882-40e7-9eb6-d75449fa3eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-service' and @type = 'submit' and (text() = 'Programa tu recojo' or . = 'Programa tu recojo')]</value>
      <webElementGuid>a9082ae8-f6ac-4f36-adb0-1f65c6baa8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
