<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PROVINCIA</name>
   <tag></tag>
   <elementGuidId>469ddf4f-c923-49b0-bb03-d663ba7a3498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_provincia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_provincia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>326c63b7-3edc-4f19-a2d3-98abe14b77bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-size</value>
      <webElementGuid>d5051850-687a-465d-a76f-3c7235bf8d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_provincia</value>
      <webElementGuid>64fcee37-f3bf-4997-ac89-31a55da1e639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROVINCIA</value>
      <webElementGuid>83306b46-03d7-4cd9-a2d9-32bdfb1dd6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_provincia&quot;)</value>
      <webElementGuid>6509ce54-3046-4432-aae5-30c2a2c8726b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_provincia']</value>
      <webElementGuid>78432db6-1b9d-4dad-9c3b-607474a9f090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_buttons']/button[2]</value>
      <webElementGuid>10ddcddf-9412-47d4-9acb-44f48614e4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA'])[1]/following::button[1]</value>
      <webElementGuid>9c4fd853-25ec-4f28-87f7-3d3ed84e1de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Dónde te encuentras?'])[1]/following::button[2]</value>
      <webElementGuid>0973ede3-296f-43d0-b4c1-06a74ad4fd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[2]/preceding::button[1]</value>
      <webElementGuid>75173d5d-2b2b-47f0-aefb-cbfd4b9a1160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[3]/preceding::button[2]</value>
      <webElementGuid>cb0c86d6-8355-45f6-901e-a3eb2c89c200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROVINCIA']/parent::*</value>
      <webElementGuid>52edfe83-9932-4445-80e4-cfce78e636a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>8c3fa5aa-45ef-4b62-881d-949e0e7dc827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_provincia' and (text() = 'PROVINCIA' or . = 'PROVINCIA')]</value>
      <webElementGuid>f51897df-ab52-40e3-a633-7d340129c484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
