<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Programa tu recojo (7)</name>
   <tag></tag>
   <elementGuidId>bee1eb78-a7d8-4077-815f-677e8fa6475c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-service</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-service']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de2a39ce-fa95-47c0-a62f-39e6059ecbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-service</value>
      <webElementGuid>58563bfd-7da3-4d9e-8a8a-da19d8c1a456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>612f7865-6092-4905-b7c0-77380c7c03ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn v-step-16 btn-success has-tooltip v-tooltip-open</value>
      <webElementGuid>cee23993-2f49-47d2-9d24-e935291e6fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip_hpwt3waf54</value>
      <webElementGuid>13d11aa8-efab-41d5-94f9-ca7e2e1c7d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programa tu recojo</value>
      <webElementGuid>3b7f3ca8-1f14-42b6-bb50-d18943a9bf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-service&quot;)</value>
      <webElementGuid>804281aa-daad-4be7-a105-d70dd95a5bd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-service']</value>
      <webElementGuid>754842b8-ad4b-42a7-9aaa-9bfbfda35087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-form-vue']/div/form/button[2]</value>
      <webElementGuid>fcf0eb22-6347-48d8-be72-1b100a2892ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/following::button[1]</value>
      <webElementGuid>8aaeba8b-1c26-4281-823a-d3f64dc6ff2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor del recojo'])[1]/following::button[2]</value>
      <webElementGuid>0fecfd2c-ed6a-4823-96d4-1dca0906f391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::button[1]</value>
      <webElementGuid>4b5d0deb-4543-4966-ba49-d473d307a91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Programa tu recojo']/parent::*</value>
      <webElementGuid>cd4bda99-659f-4fa6-ba06-7d597f2d98c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6ab21f07-d3a1-4ae3-af85-2a7fb38035a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-service' and @type = 'submit' and (text() = 'Programa tu recojo' or . = 'Programa tu recojo')]</value>
      <webElementGuid>7ae8abfb-d53e-4c27-a35a-7075c7df67cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
