<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Programa tu recojo (2)</name>
   <tag></tag>
   <elementGuidId>58181ef1-a372-48b2-85ee-c5400dbd9d52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-service</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-service']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a21cba8-3882-4211-990c-1b0456ce3117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-service</value>
      <webElementGuid>773890ad-d15a-4334-9ee8-cda91bc75207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>57f6d54d-3300-4b10-8364-9c83491f64a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn v-step-16 btn-success has-tooltip v-tooltip-open</value>
      <webElementGuid>7064053b-b335-4bdc-a755-639732e66c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip_4xb5bc7gz0</value>
      <webElementGuid>f98751b4-998d-4fce-b2e1-fe9c62947cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programa tu recojo</value>
      <webElementGuid>ad015f0c-4b68-47c2-b16c-10ed69dc9875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-service&quot;)</value>
      <webElementGuid>44793f7f-cdd9-48d5-9104-d4fb862afefe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-service']</value>
      <webElementGuid>194572c3-b8bd-4c30-bbc6-f6476d7cba79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-form-vue']/div/form/button[2]</value>
      <webElementGuid>1cf0a653-1143-4611-b2e3-93b7a070a35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/following::button[1]</value>
      <webElementGuid>873641d6-8d7b-4e44-9c5e-83dcfe5ace43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar envío'])[1]/following::button[2]</value>
      <webElementGuid>1b4d74a5-9b70-4367-bf65-c3d3cebebfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::button[1]</value>
      <webElementGuid>79e8ffb3-000e-4f9f-8479-cf1cda692d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Programa tu recojo']/parent::*</value>
      <webElementGuid>1de6601a-11b1-4af3-87bf-c0732ae11ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>47c893b6-b9f5-4db1-8b51-626b1f943402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-service' and @type = 'submit' and (text() = 'Programa tu recojo' or . = 'Programa tu recojo')]</value>
      <webElementGuid>70ab24da-d41b-406d-b5e8-129db52d1510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
