<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR_1_2 (2)</name>
   <tag></tag>
   <elementGuidId>58c21080-b4e7-4bc3-bb0d-7da67daa8bec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_destino']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_destino</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07a74980-54dc-47cb-a490-1502b6a770ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_destino</value>
      <webElementGuid>9498abb2-7b66-4a2b-a7da-810193d2a33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>d72daf77-3aba-450a-9428-44cf9195bab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mt-10</value>
      <webElementGuid>66ee1790-b3a3-4d18-89d7-bd521a00fa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>cd536c60-ee62-43d7-8257-3cd5514a7ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_destino&quot;)</value>
      <webElementGuid>2dec438d-6333-4d50-9b6f-5dfcb7106cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_destino']</value>
      <webElementGuid>acb9cdd3-eafb-4c36-9088-7d1ea25f181c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_destino']/button</value>
      <webElementGuid>30314d37-2abc-4415-a769-28973a47de2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/following::button[1]</value>
      <webElementGuid>7f9561f6-83e6-4925-8f07-ba75fe29c84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/following::button[1]</value>
      <webElementGuid>7211e9cc-9d5e-45ac-bc86-709c323b9030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validación del primer apellido'])[1]/preceding::button[1]</value>
      <webElementGuid>88d40a46-2bb4-48ca-a904-96ecb038eac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El apellido ingresado debe ser igual al registrado en su DNI'])[1]/preceding::button[2]</value>
      <webElementGuid>0d859c8c-3189-41c7-b4f1-689190bacc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUAR']/parent::*</value>
      <webElementGuid>43f55f40-5702-4b0c-86d2-a4865aabad57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>1c992a14-a2a2-4e0e-8ae9-7731596d6c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_destino' and @type = 'bottom' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>880e08bc-72d5-4b2e-8db5-4bbf6b5716f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
