<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_IR A PAGAR S 43.13</name>
   <tag></tag>
   <elementGuidId>9ec1eaaf-f43d-4889-9289-aff3bb5e9e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar-listar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-listar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab2d0d9d-bca2-4c96-aeda-1b19ca75211d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-listar</value>
      <webElementGuid>cd8611d8-c168-4167-aa13-306e09863a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>43.13</value>
      <webElementGuid>e7c59729-f7f7-4ef7-9c6d-01cf69398789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e97bb89-bdb4-4cde-9b43-4447c2938d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>810c2491-b1a3-433e-aab9-5ba7cf53ff06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IR A PAGAR S/ 43.13</value>
      <webElementGuid>04f19520-ca13-4803-87c1-2ad46a707560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-listar&quot;)</value>
      <webElementGuid>073c5b56-5224-4f67-99ad-d4d50ef696dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-listar']</value>
      <webElementGuid>93ef57fb-8974-4dec-bf74-fcc387c75422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_pagar']/button</value>
      <webElementGuid>265f0668-6d4c-4afa-8002-5bb8e1d599a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/following::button[1]</value>
      <webElementGuid>166abd10-bfd1-4730-abba-9c0cc85ba169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/following::button[1]</value>
      <webElementGuid>0a579ecf-b6ad-4ed6-aacf-604504684a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿A dónde retornamos el cargo adjunto ?'])[1]/preceding::button[2]</value>
      <webElementGuid>afe026c1-1d01-4943-adaf-d33ec545b505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de entrega'])[3]/preceding::button[2]</value>
      <webElementGuid>d2259c9a-7d0d-44a0-8341-e35be41b1b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IR A PAGAR S/ 43.13']/parent::*</value>
      <webElementGuid>9f4d9b0b-3640-4a1e-9470-74b29a31cb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>bae7c5ac-782f-4efc-94a2-9415d62121a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-listar' and @type = 'button' and (text() = 'IR A PAGAR S/ 43.13' or . = 'IR A PAGAR S/ 43.13')]</value>
      <webElementGuid>a8b227f4-907f-4519-b7a4-05e8e42ff6bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
