<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SOBRE (4)</name>
   <tag></tag>
   <elementGuidId>7e397f41-0789-46f9-85a7-b423e8ab5a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu.visible > div.item.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='__BVID__31']/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d8ee3a7e-c860-4b3f-9544-23138d9907c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item selected</value>
      <webElementGuid>26ea272d-37c0-4e3f-8a3e-2d38251a498b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      SOBRE
    </value>
      <webElementGuid>0f46ace4-8b54-41e3-830f-49157be41cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__31&quot;)/div[@class=&quot;bv-no-focus-ring&quot;]/div[@class=&quot;ui fluid search selection dropdown active visible&quot;]/div[@class=&quot;menu visible&quot;]/div[@class=&quot;item selected&quot;]</value>
      <webElementGuid>375ee368-12a8-4ae6-89d6-5d77a85dcbb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__31']/div/div/div[2]/div</value>
      <webElementGuid>df71a12e-dfbb-4002-9cb9-12d4e6eda2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contenedor*'])[1]/following::div[2]</value>
      <webElementGuid>548c19ab-58c8-45c1-b99c-08cd8f47c858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Fragil?'])[1]/following::div[11]</value>
      <webElementGuid>80fb2853-cce0-4b7a-86b8-6e8c60f93eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAQUETE'])[1]/preceding::div[1]</value>
      <webElementGuid>ac4e3126-e486-4f17-9963-e529756fdf71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículo*'])[1]/preceding::div[2]</value>
      <webElementGuid>4ec92ea0-8dfc-43c2-adc9-40467a053995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SOBRE']/parent::*</value>
      <webElementGuid>c3c5a5bc-49ff-46ce-898a-d96b368f8f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/fieldset/div/div/div[2]/div</value>
      <webElementGuid>edfa8d13-1af8-4a5e-b132-ce1cb81e5a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
      SOBRE
    ' or . = '
      SOBRE
    ')]</value>
      <webElementGuid>59f5f68c-468a-4fae-b6ce-b91eb4117608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
