<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Elige tu medio de pago_fa fa-circle-o (2)</name>
   <tag></tag>
   <elementGuidId>c08e6e1a-b280-4a13-b17f-594c90025022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pago1']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-circle-o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1c9ead58-b8a0-47b3-bfe4-b61dcee4c0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-circle-o</value>
      <webElementGuid>e4450f18-550d-43c5-8eaf-8bd6312f6742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pago1&quot;)/div[@class=&quot;col-md-12&quot;]/i[@class=&quot;fa fa-circle-o&quot;]</value>
      <webElementGuid>611ce208-2e9b-4ce3-988c-537ed07b4f67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pago1']/div/i</value>
      <webElementGuid>4256e2a0-4907-422e-80ab-d62759f77991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/i</value>
      <webElementGuid>9417763f-1cc2-41aa-aa65-4f98dd115a66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
