<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aceptar_iframe_response</name>
   <tag></tag>
   <elementGuidId>d3dd3ef7-c2e0-440c-b5e8-fd6497aae9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe_response']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe_response</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>329c3f4a-3279-4645-9503-972afe60f6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe_response</value>
      <webElementGuid>f7372fac-a44b-4164-bcdf-a96671db42fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b986025b-745a-4dcf-946b-c4ee7eb90528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://geo.olvaexpress.pe?origin=https://registro.olvacourier.com/registrar_envios_cajas/girley-map&amp;montoValor=undefined</value>
      <webElementGuid>e5bad63e-c02d-428d-b4df-215f9957ec43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e50f22a6-9679-4354-a66b-c6b82c9f48d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe_response&quot;)</value>
      <webElementGuid>3c305b33-2787-45cf-a4c3-4528330e4633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe_response']</value>
      <webElementGuid>91505254-aab7-4189-a8cc-6b406a48a689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-body-geo']/iframe</value>
      <webElementGuid>0f9dae09-cbc3-4f3f-b6ce-f17ce0f56d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[4]/following::iframe[1]</value>
      <webElementGuid>17d2ed38-4b7a-4565-9813-7b532a3e42bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar'])[2]/following::iframe[1]</value>
      <webElementGuid>73cce574-4309-47e1-87e4-0dcdfe93feb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::iframe[1]</value>
      <webElementGuid>dc523980-4b5c-4331-8343-792aa44b7c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'iframe_response', '&quot;', ')')])[1]/preceding::iframe[1]</value>
      <webElementGuid>3932aa23-eeb8-4a23-bdf2-3d7a8e9e1b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7fdd6fb9-af7e-4a0c-a322-38f49f3c60cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe_response' and @src = 'https://geo.olvaexpress.pe?origin=https://registro.olvacourier.com/registrar_envios_cajas/girley-map&amp;montoValor=undefined']</value>
      <webElementGuid>e133ce86-7bae-4438-9d20-58c1a2e316c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
