<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aceptar_visaNetJS</name>
   <tag></tag>
   <elementGuidId>5f0796aa-cf4f-4124-be2c-8b6930100431</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visaNetJS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='visaNetJS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>18dc27f4-d7de-4b50-b45d-cac06a5cc41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visaNetJS</value>
      <webElementGuid>78e15c71-fec9-46c8-86a7-f3361ee0c958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fe35faff-128a-47d7-8591-10ebc264f312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9670aea6-d9cf-4a1e-9f44-adae78c04031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-content-qas.vnforapps.com/v2/visanet.html?0.9274168213416534&amp;qa=true</value>
      <webElementGuid>9a9b5b1c-34fa-4d88-9035-afc1f0060782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visaNetJS&quot;)</value>
      <webElementGuid>7e3de907-7be4-42c0-9848-534deca812d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='visaNetJS']</value>
      <webElementGuid>855df53a-ba91-4a59-b504-6071fd2bd421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visaNetWrapper']/iframe</value>
      <webElementGuid>8ca64b32-442a-4cfa-be9c-cdadf1f87c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>efd32efb-e752-4b96-b52c-ccfa4ea665c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'visaNetJS' and @src = 'https://static-content-qas.vnforapps.com/v2/visanet.html?0.9274168213416534&amp;qa=true']</value>
      <webElementGuid>32746ae3-1d15-4ffc-866d-d73e93b010a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
