<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal (1)</name>
   <tag></tag>
   <elementGuidId>27f8873b-0a38-4f66-8fc3-327bd4b842ef</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9f8e4ac3-1e62-4fd4-afc1-9949d8f11fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>47128318-877c-4d02-8d54-0f5ce67b41e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>1ad00389-0866-418a-a307-f5ef03749509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=error_token_null</value>
      <webElementGuid>1efcb875-5576-4b0e-858a-44a9a2e0a371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>8dd5fcad-2e32-4fed-9fe6-b102816ac276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>7d22f63e-156a-4c0a-952b-dc1fbf222c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>41707b5e-5475-4a90-b988-240e904d0d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>68858774-ee51-4322-bbec-6c36bdd64d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=error_token_null']</value>
      <webElementGuid>a83fe3cd-ed4d-4cc9-88de-9cfbe1a9e729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
