<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Precinto_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>41b8f307-7eef-4065-a2ec-57b68db96677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9863a940-7718-4034-8f26-2078089b1aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>73bcaf1f-1da6-462f-abe1-ff75224a693a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>3a728092-b1ef-4d91-beb4-a0e83548eebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/host/gestion.xhtml?nodeTree=Host&amp;codeTree=0205&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiSlNSSU9TIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NzEyNDk0OTksImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6IjA5MDY4ZTFjLTIwNTAtNDIwYi1iODIyLTcwMDYxMTQ3MWY3MSIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.e-7eAX92GLpZHNpU172C-mClLPDbY2a8shoJDmVP5eE</value>
      <webElementGuid>2b27aa56-3b74-42a1-b86b-1daec8e9753b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>52e7a488-f0be-46da-87f3-8ac9a65453b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>c3a5af64-b49a-4601-ab2b-f52af0d271a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>5f5e2206-7e05-4908-b26e-c1f8798cb1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b37da4e4-13db-4e86-b7c1-8e3464ac108d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/host/gestion.xhtml?nodeTree=Host&amp;codeTree=0205&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiSlNSSU9TIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NzEyNDk0OTksImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6IjA5MDY4ZTFjLTIwNTAtNDIwYi1iODIyLTcwMDYxMTQ3MWY3MSIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.e-7eAX92GLpZHNpU172C-mClLPDbY2a8shoJDmVP5eE']</value>
      <webElementGuid>a4dbf29e-e0f4-4117-8638-52b1783211f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
