<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Precinto_iframePrincipal (1)</name>
   <tag></tag>
   <elementGuidId>55410389-3f3a-43bf-976b-7f6a8cb52b93</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3449c9b1-b500-4c7b-a616-e32d9746597b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>3fd000f3-a155-42af-847f-67406483fa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>29f5f762-6eb0-4f01-9c8e-2999c0d1db1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/host/gestion.xhtml?nodeTree=Host&amp;codeTree=0205&amp;access_token=error_token_null</value>
      <webElementGuid>9005ac7e-5911-42f1-a602-641b694051ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>74ae1008-927a-47fa-be2a-c8d60e40907c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>4866ddba-5b23-4c17-a584-93436ef5b413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>3ecbc37a-249d-4c71-ac44-3ba5f5f1d7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a41bfcea-bb96-4b63-9daf-578769db33da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/host/gestion.xhtml?nodeTree=Host&amp;codeTree=0205&amp;access_token=error_token_null']</value>
      <webElementGuid>93624bac-3ae3-4bf6-945c-e0c55904641a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
