<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>cc81d14d-7b5a-41e5-aae7-809e714d5400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>33fde9e8-0689-4c8e-9a01-b732c4b4433f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>93f66fa7-8b67-41a3-84c3-56026e4df61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>ad52f65d-445c-43ba-ac66-9d2d9a5aba1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiSlNSSU9TIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NzEyNDk0OTksImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6IjA5MDY4ZTFjLTIwNTAtNDIwYi1iODIyLTcwMDYxMTQ3MWY3MSIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.e-7eAX92GLpZHNpU172C-mClLPDbY2a8shoJDmVP5eE</value>
      <webElementGuid>e6e39b87-c382-4ad0-8029-bf8c3a9ca9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>6393d95c-48b0-4734-ba37-320c7ae5ebf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>461e3cd8-4a38-431b-a012-a0e67fabfffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>e350211e-b704-4d29-aaa1-b8c3931c4e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>dc826bbd-5a80-4305-b85b-4f64a5789b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiSlNSSU9TIiwic2NvcGUiOlsicmVhZCx3cml0ZSJdLCJleHAiOjE2NzEyNDk0OTksImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6IjA5MDY4ZTFjLTIwNTAtNDIwYi1iODIyLTcwMDYxMTQ3MWY3MSIsImNsaWVudF9pZCI6ImF1dGhvcml6YXRpb24ifQ.e-7eAX92GLpZHNpU172C-mClLPDbY2a8shoJDmVP5eE']</value>
      <webElementGuid>576f1057-7bae-471e-b65b-3536bd0a317e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
