<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Qu deseas realizar hoy_img_paquete</name>
   <tag></tag>
   <elementGuidId>5092c744-f4a0-45ab-a36e-3de36ae24b6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_paquete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_paquete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65d76cbe-89b7-4745-af97-c554bf6d2bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_paquete</value>
      <webElementGuid>e928d580-1f10-437b-bdad-11c6f5093247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://registro.olvacourier.com/registrar_envios_test/assets/img/paquete_v3.png</value>
      <webElementGuid>b4df3f90-347f-4f55-9199-a017dd6c01e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>b19cdf05-9554-4349-ace7-b83714576ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>6479cd07-1cc0-47bb-83cf-a65da2220aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>d576ab16-a989-48f3-a57f-cb831e67151f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_paquete&quot;)</value>
      <webElementGuid>cbadefdd-249f-47da-928c-f3447dae0efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_paquete']</value>
      <webElementGuid>d1d68b33-74e3-4958-b76d-1a4e8497c5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_paquete']/img</value>
      <webElementGuid>cb89653f-47a8-4a64-a204-e1df514c2675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://registro.olvacourier.com/registrar_envios_test/assets/img/paquete_v3.png')]</value>
      <webElementGuid>2f8a64f7-3ea3-4de1-bb71-a37bd5995549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>bb90352a-5741-4629-b923-d34a2feaac84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_paquete' and @src = 'https://registro.olvacourier.com/registrar_envios_test/assets/img/paquete_v3.png']</value>
      <webElementGuid>6b4ea2bc-f6f4-46b8-b342-724f8faf115f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
