<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de documentoscon un peso mximo de__8aba39 (1)</name>
   <tag></tag>
   <elementGuidId>10a61208-759d-4c86-8c99-bac542e2008d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_caja']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_caja</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c6a9addb-8dd7-4436-9837-965e8cdf1941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_caja</value>
      <webElementGuid>6071c229-41a4-4645-9ebc-b9c2a1e4f9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png</value>
      <webElementGuid>4ed0bbc7-c156-45d8-bd27-57b901306b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>71dee757-ec93-4d54-a083-93f0f2212329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>07975938-f5b7-422d-bde9-ef03ff628036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>d7614ce3-6d28-4604-89a6-ee9863b6fc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_caja&quot;)</value>
      <webElementGuid>27cdd9fb-5ce6-4423-82d6-22b1ae0271e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_caja']</value>
      <webElementGuid>ccd9aeda-208d-4a54-900e-c482b0aff858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_caja']/img</value>
      <webElementGuid>e24177cf-c9ea-4d2c-9dd8-2d64cdc0368c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png')]</value>
      <webElementGuid>cbe513ea-79cd-41ed-8399-c85cc931d387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/div/figure/img</value>
      <webElementGuid>5d434e39-a0e8-48e2-b672-3aeadee7b36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_caja' and @src = 'https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png']</value>
      <webElementGuid>89e4fe36-cb90-4191-8235-83e09b24e9aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
