<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Qu deseas realizar hoy_img_paquete (1)</name>
   <tag></tag>
   <elementGuidId>c57860e6-68da-4870-8717-1a4b84473a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_paquete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;img_paquete&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>446535bb-8fd6-4de0-9f83-1c8abc5185fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_paquete</value>
      <webElementGuid>d692c1af-6d2c-4cac-8498-4ae2bef7abdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://registro.olvacourier.com/registrar_envios_lima/assets/img/paquete_v3.png</value>
      <webElementGuid>98dc8ff2-e630-4d4b-b9fa-309762652afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>16bdcb3a-2b82-4385-b743-c933b01b356e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>397a0589-f5d8-472f-a0b1-6a921c8a8dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>6d2d23e4-590b-4d61-bb18-bddb690d01ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_paquete&quot;)</value>
      <webElementGuid>a204a3d6-7496-4b79-b2da-11cb4cec5928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_paquete']</value>
      <webElementGuid>941ca2d9-d759-4676-9c1f-9e0440c73d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_paquete']/img</value>
      <webElementGuid>5be71ba0-98a1-4f76-a83c-38b80c1ea5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://registro.olvacourier.com/registrar_envios_lima/assets/img/paquete_v3.png')]</value>
      <webElementGuid>43c8f1a7-f0e8-446f-8c3b-752cb27cc865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>fc249feb-3697-40ea-a3bd-0571c0290702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_paquete' and @src = 'https://registro.olvacourier.com/registrar_envios_lima/assets/img/paquete_v3.png']</value>
      <webElementGuid>d2222039-1623-4ad1-8376-42ab980fed65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
