<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de documentoscon un peso mximo de__8aba39 (2)</name>
   <tag></tag>
   <elementGuidId>f54c494d-e04d-4486-b107-29a786de34b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_caja']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_caja</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3eddf073-dfa0-434f-aeeb-48f3fefa4d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_caja</value>
      <webElementGuid>f00db206-9cc2-4f75-86b7-0b4883a100e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png</value>
      <webElementGuid>dad98ef8-10e0-47e5-b108-61aee901cfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>3bcd7cfd-71ba-4eb1-a6ab-6787207b4f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>d6df898e-958e-47a0-8034-f584eac278ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>11f666d7-1a65-41bc-bf9c-9673520732da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_caja&quot;)</value>
      <webElementGuid>fc72a15d-4be9-4364-83b0-8554fb492b17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_caja']</value>
      <webElementGuid>ad2eaca6-2c86-432a-af8a-917cac9a9fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_caja']/img</value>
      <webElementGuid>6dc24def-730d-4b95-bd73-c0265bb21a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png')]</value>
      <webElementGuid>7482ee03-d10e-42f0-a6ea-43ced1391208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/div/figure/img</value>
      <webElementGuid>f486cfe8-e3ab-4135-93f6-f32df5dc776b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_caja' and @src = 'https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png']</value>
      <webElementGuid>bb903b8c-7836-47be-98a3-fa975616aff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
