<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZONA CLIENTES__password (7)</name>
   <tag></tag>
   <elementGuidId>b6f27d10-299b-4366-ae79-4c9ef418d84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0902ae01-23f8-4769-82ad-894b504c8c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5625a5a0-ef6b-4772-bd40-224180b096ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_password</value>
      <webElementGuid>dd41791f-599e-424a-8c7d-710f3d3e0e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_password</value>
      <webElementGuid>a8b64928-5f38-4907-b055-d6b11f327b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>df8308af-ec80-4c3c-845a-37225ee9ef97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>1a93ac0e-60e5-49bf-9797-dc67dfc6bea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>35bcbdf8-f77e-4a3a-b7f8-b1224f6e5e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_password&quot;)</value>
      <webElementGuid>c6cd9b1c-3c78-4566-9a9a-c1f0a2605a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_password']</value>
      <webElementGuid>e1078934-a061-4375-8125-83c7507e60d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b65878d4-8def-40ae-9968-be529376b070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = '_password' and @name = '_password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>1feca8e7-6212-42b8-8911-eca7d755e399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
