<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZONA CLIENTES__username (18)</name>
   <tag></tag>
   <elementGuidId>a43628a0-9076-48f1-9967-96ff85140409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6aed0b93-2c54-46ab-8078-f1956dc04298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af295e85-1002-49f5-b228-d32fe3707a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_username</value>
      <webElementGuid>d2e21e54-3364-4b94-b481-af8e88d9a839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_username</value>
      <webElementGuid>0d79c3a7-62ad-4e01-b1e1-bb1289247024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cb3b9bce-0106-49e5-bed6-4adb2102eabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>729b2607-e18a-4091-948e-dc103f521f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>777479f7-77b3-440b-8776-7c5cc96a0f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_username&quot;)</value>
      <webElementGuid>bc405b33-ee96-4180-a561-0800f14e27d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_username']</value>
      <webElementGuid>b45f2cef-e0b9-490a-b31c-cad4d38683e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>84511c74-ffb1-48d6-b428-808de800a951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_username' and @name = '_username' and @placeholder = 'Usuario']</value>
      <webElementGuid>538be5ed-c496-4a5a-b919-2360251845a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
