<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CARN EXT_txt_consignado_telefono (4)</name>
   <tag></tag>
   <elementGuidId>fff0a34a-192a-4155-be6a-627020e1e369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_consignado_telefono</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_consignado_telefono']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6585a1e0-28ac-4f5c-9118-cd86f5bf3702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45f67dbf-552e-477f-a7aa-047df007b54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c19126d3-489d-40cb-9893-08e511ac3880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_consignado_telefono</value>
      <webElementGuid>508bccdf-167b-436b-80e9-8f805d33512a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Celular/Teléfono</value>
      <webElementGuid>8283ae59-a54a-4203-991f-5bda2ef892d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-last-name form-control msg_alert_tt</value>
      <webElementGuid>e88bec44-3daa-4aeb-9673-76da3b54257a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>07a42759-75cd-4da1-bcff-21a250b43285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_consignado_telefono</value>
      <webElementGuid>ee8e3f3d-e627-4249-b5ea-53b3256b38d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>9e3ad7e1-fa1d-46ea-8d0a-4f8d84ca280b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>18c8e99c-ee84-4743-9112-df82f7ef601b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_consignado_telefono&quot;)</value>
      <webElementGuid>3b36aa0c-0120-4736-bde2-e51c945d9e60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_consignado_telefono']</value>
      <webElementGuid>283ffbd0-d760-4bf5-9f42-f40517f7e728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_recibe']/div[2]/div[4]/input</value>
      <webElementGuid>c4b5fc83-9ba9-4095-a2e4-000704cf5153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[4]/input</value>
      <webElementGuid>a92fff56-5f5e-4f42-af41-6e96f60e0829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_consignado_telefono' and @placeholder = 'Celular/Teléfono' and @id = 'txt_consignado_telefono' and @title = '.']</value>
      <webElementGuid>fa587331-cfd1-4fd3-b9c3-4cfaf5e3afe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
