<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agregar Direccin Nueva_input-1 (1) (1)</name>
   <tag></tag>
   <elementGuidId>210ac989-e891-40e9-ab0f-2c66df04aa2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5f94f00-631b-4637-9cd4-cc94552a8760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1</value>
      <webElementGuid>a1ee858e-2874-416f-b508-5356bf683594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93a94b6f-bcef-41a6-88b9-6cb5da71bfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre de contacto*</value>
      <webElementGuid>8c2fd965-232d-4fb3-b3e1-bb61db675e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>77ebae18-4cc9-461d-9721-086ce0bdc8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1&quot;)</value>
      <webElementGuid>7a9238ad-79df-4f05-b0ac-91a16bdf48b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1']</value>
      <webElementGuid>0fcfbbc3-b738-4ed7-af71-cf3e4a6098f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__12']/div/input</value>
      <webElementGuid>b4bc1856-f0b3-467f-b2d1-8b48fbd2dbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>4cf1e8d9-8ca1-42f4-9ebf-3e91de3b7ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1' and @type = 'text' and @placeholder = 'Nombre de contacto*']</value>
      <webElementGuid>68013a05-05a2-4950-bbac-642aec1ccc59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
