<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ok_to (5)</name>
   <tag></tag>
   <elementGuidId>f58f7e06-bded-4a98-b638-ed4e5ba4afe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#to</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>736b1e76-4f4c-460b-b286-0f39feddca5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dde358f5-184f-4a6d-b62d-25f55b01854b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to</value>
      <webElementGuid>6ffbe2e1-ff74-487e-92ae-5be420506e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>yyyy/mm/dd</value>
      <webElementGuid>23289f18-e9fc-4646-a0ef-005b2c3cdc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>6090e4ad-cabe-4b22-b80c-31d61eb8c467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to&quot;)</value>
      <webElementGuid>470aaeae-c15f-4729-ae3e-09e040dc331c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to']</value>
      <webElementGuid>f59994b6-9821-4050-adb8-661fd128afa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='eeccform']/div/div[2]/div[2]/input</value>
      <webElementGuid>ae1ea335-11d9-4f2a-b062-3d51dd3f705d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>4957d0d5-f7b3-4f52-87de-57f47cfe31ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'to']</value>
      <webElementGuid>8523f90f-5933-4380-b88b-77defdc52671</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
