<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agregar Direccin Nueva_input-2 (1) (1)</name>
   <tag></tag>
   <elementGuidId>e17885c6-c4f7-4d6e-8735-040f268cc624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3736b43a-9df6-43d6-a927-fd86fdc53c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2</value>
      <webElementGuid>16d677c4-e17d-4b6a-a191-bb9df946805f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>64e6a10e-54f1-46e7-bb84-2d88cb3f9dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Teléfono de contacto*</value>
      <webElementGuid>c5ea3cab-5c79-471b-a825-8f4547a56c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b02d220d-b279-4ae7-bb67-b782fe9a1352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>([0-9]{1,3}[0-9]{3}[0-9]{3,4})</value>
      <webElementGuid>229b4b17-e6d9-4ba5-ad5f-316a36222d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2&quot;)</value>
      <webElementGuid>028de131-e691-42af-8d89-e4333343499e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-2']</value>
      <webElementGuid>2a06b463-42c8-4c4b-bc27-7cfa17ae16ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__16']/div/input</value>
      <webElementGuid>d6b908d1-bc5f-43e6-a7b5-3158fb3063e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/input</value>
      <webElementGuid>ddb899e5-686c-44a8-acd2-3b06efb55c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-2' and @type = 'tel' and @placeholder = 'Teléfono de contacto*']</value>
      <webElementGuid>19d5ea5b-949b-4283-8e30-b84151968ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
