<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agregar Direccin Nueva_input-1 (2)</name>
   <tag></tag>
   <elementGuidId>d2610c68-885e-45c0-b1e8-acba7bd47f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5aa44e2a-1eea-40b1-b4a4-7a5db151abbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1</value>
      <webElementGuid>18e75ec2-b93f-43e9-a89b-31a986a518b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14964f5d-f2c3-475a-9494-11fa89d0b534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre de contacto*</value>
      <webElementGuid>7a1d478c-3735-4f69-a89d-19f9c171908b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>df09b17a-c8d7-4aad-b9ef-305beaaa1618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1&quot;)</value>
      <webElementGuid>bb9ead3c-3899-4934-8683-0a89e932bfa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1']</value>
      <webElementGuid>e5bca190-8c11-4f49-88d1-1830653465f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__12']/div/input</value>
      <webElementGuid>691e3762-9164-4b2e-8130-5b61a09ded9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>441b3a67-5feb-4c3c-bca5-085fc35565fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1' and @type = 'text' and @placeholder = 'Nombre de contacto*']</value>
      <webElementGuid>6def9d58-eef7-4162-bab8-a253faf89d6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
