<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SANTA MARIA DE NIEVA - SANTA MARIA DE_50fc39 (1)</name>
   <tag></tag>
   <elementGuidId>66486829-cf86-40fd-b16a-ce62c07011ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_clave_seguridad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_clave_seguridad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>177cd521-bf8f-4c66-b74c-42d095695995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91b1489d-8a2e-41e5-93d5-6c097eeaaa97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_clave_seguridad</value>
      <webElementGuid>7b47bc98-5a64-412d-932f-a87b9d00f9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Clave de  seguridad</value>
      <webElementGuid>a5a8bb7e-2b47-4138-b921-1c87d34c2e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputRE</value>
      <webElementGuid>fd5853ff-dd3e-4f26-b8f2-5a83ea208053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_clave_seguridad</value>
      <webElementGuid>b2364cc9-cfe3-43c1-b10c-887c55ed0e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Clave de seguridad</value>
      <webElementGuid>b86c6545-0e65-4445-bcb3-8a75c5b0ccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1f6f866-783f-4d2a-a8f1-3c8982d6402c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>86207f3d-b72e-4167-9489-30fef0e433f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>1198715d-f1e6-4762-9592-e1b9de6b97b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_clave_seguridad&quot;)</value>
      <webElementGuid>35d05d3e-310d-4895-adc5-7a1a7ef4dfee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_clave_seguridad']</value>
      <webElementGuid>5cd7c0fa-fd0b-4737-a972-c5bcd70a0eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[7]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>b12e9086-ae26-469f-b204-81dcd6b7c9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>0b0f858b-106b-43aa-b31e-07115582840c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt_clave_seguridad' and @placeholder = 'Clave de  seguridad' and @id = 'txt_clave_seguridad' and @title = 'Clave de seguridad' and @type = 'text']</value>
      <webElementGuid>5173f4c8-e720-436e-ab5a-ed194e75e051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
