<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hola,_txt_email_cliente</name>
   <tag></tag>
   <elementGuidId>93c96190-f976-4575-ad48-f8bc7db691ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_email_cliente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_email_cliente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc84abce-8e43-4156-ad35-e561c5cda77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>21f512d3-1fa8-4009-b675-6aad369851a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2d93cd7a-7509-431d-a7db-8b80dbf374f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_email_cliente</value>
      <webElementGuid>a84c90b5-4fbe-4fda-b1d5-cbb326984670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirma tu email</value>
      <webElementGuid>4e1d29a4-0664-464e-928e-b2bfb544bfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control msg_alert_tt errorValid</value>
      <webElementGuid>8a40f755-237c-4276-ac0b-7a2a52866a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>d2efbd7e-f049-4ce6-aab4-61eac0218856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ba040709-c911-45aa-9fcf-14102235f19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_email_cliente</value>
      <webElementGuid>2b022d19-b30d-4817-8b34-610b9bd8ce57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>52ade0e9-9151-4be6-bf04-d1267800dd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_email_cliente&quot;)</value>
      <webElementGuid>f51a2b5a-91a9-42cf-ba06-7110de4c6a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_email_cliente']</value>
      <webElementGuid>0939e7ef-a2c4-451f-93dc-9cb825bf4f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[3]/div[3]/input</value>
      <webElementGuid>3bceace3-bc1f-4177-8669-429e2f5014c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>dd1e924d-708b-47d8-a750-af5f1e081f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'txt_email_cliente' and @placeholder = 'Confirma tu email' and @title = '.' and @id = 'txt_email_cliente']</value>
      <webElementGuid>529b8076-3066-4b7b-87d6-fc4520c6a294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
