<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referencia_reference</name>
   <tag></tag>
   <elementGuidId>626ace6a-f38b-4cb2-86f4-82806c90f565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reference</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c29e43a-3b49-4b0a-9e19-f653ec62c49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>de0ff05d-e06c-493a-b3e5-b7de56ae23c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4fbdb0e8-9e4c-4c0a-bb4d-7a0be37151bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09606077-3cfc-4ac6-8bb3-4037c306c2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ejem: Entre Av. Argentina y Av. Universitaria</value>
      <webElementGuid>c50a768b-4b32-4de6-bddc-360aac8e8852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b760f61b-e8ed-4c8b-b06e-f7584d0abab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference&quot;)</value>
      <webElementGuid>dd0a3bd2-0779-4de9-96b6-4f94b9c322e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Aceptar_iframe_response</value>
      <webElementGuid>bc6c877b-be13-49e5-9552-30bdd4d28ad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference']</value>
      <webElementGuid>880c2546-bbbb-4bf9-8491-52682c8bd9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__080381___BV___']/div/input</value>
      <webElementGuid>32d5eadf-190d-4776-b409-fbb0821eadd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>24be288d-070c-48e2-a2d8-5a88e810e470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference' and @type = 'text' and @placeholder = 'Ejem: Entre Av. Argentina y Av. Universitaria']</value>
      <webElementGuid>fb875d1e-4955-492c-8ece-3943958709bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
