<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Guardar Direccin_input-2 (1)</name>
   <tag></tag>
   <elementGuidId>a8c8cc67-4b90-42e2-bdfb-7604ec7d4357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9136ed4-57f4-46e9-ba57-bf129ae17793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2</value>
      <webElementGuid>942fbf6c-31c0-42e7-97fe-ee367a8200a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e8379e7c-f800-4b8e-9756-67265437c2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Teléfono de contacto*</value>
      <webElementGuid>b6116e50-a3b3-4e80-97d6-6acda7425779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4ca29798-f02f-4c83-a1b5-4598355f583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>([0-9]{1,3}[0-9]{3}[0-9]{3,4})</value>
      <webElementGuid>f79f22be-a43b-4d14-b54f-e7bbb4e548ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2&quot;)</value>
      <webElementGuid>993c9a0d-7472-4d23-8594-91901967b1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-2']</value>
      <webElementGuid>4fcbff6e-29d1-455e-98d3-b83cfe0dabab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__16']/div/input</value>
      <webElementGuid>cb65cde7-f119-4639-9636-d622b02cfafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/fieldset/div/input</value>
      <webElementGuid>089a3f9c-20b6-46b0-ae31-1b8eb39aab0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-2' and @type = 'tel' and @placeholder = 'Teléfono de contacto*']</value>
      <webElementGuid>260b8b58-6977-44e9-a709-a49a55d81690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
