<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ok_from (2)</name>
   <tag></tag>
   <elementGuidId>7ba558a8-b47a-4ec2-8994-31d6d5d9563a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c5d15a9-eaff-4493-a3f6-1601e6d11741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e106545c-d60d-4523-8b3c-31e48022618d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from</value>
      <webElementGuid>11a430a5-50f9-4540-a2d2-4f9240f842f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>yyyy/mm/dd</value>
      <webElementGuid>d636e9ac-a85e-4c7a-8278-6b0ac058907c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>601a2661-08c8-4f96-a0be-759d6e15e331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from&quot;)</value>
      <webElementGuid>b30dad9c-319e-4713-a044-4a0dbf618728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from']</value>
      <webElementGuid>710f673c-ba34-4bdd-b371-47c9d556796c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='eeccform']/div/div[2]/div/input</value>
      <webElementGuid>2b07bfce-f28f-4c17-8e78-cc12ed066ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>57c8eef9-11db-401f-b279-af101cbc0906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'from']</value>
      <webElementGuid>003092e3-31e7-4b8f-a4a8-0c751939f691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
