<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_cantidad856 (1)</name>
   <tag></tag>
   <elementGuidId>c40fa3a3-a169-49d5-8b4b-a8bb35340dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cantidad[856]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cantidad[856]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>754ff906-d5a9-46a9-b98f-8fd394510f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0373ed0-ca19-4031-91f4-4bcaa78a69c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidad[856]</value>
      <webElementGuid>e46847ce-8e1a-4bfc-8f85-10359a577183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cantidad-paquetes  input-key</value>
      <webElementGuid>c7acdb08-15b4-41b2-b308-221c73fbead1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>873b636e-10f5-41ae-a579-dca305b49ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b227fe3f-ad01-4c53-bacc-f01081aaffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paquetes&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 item_cajas&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;input-group input-cantidad&quot;]/input[@class=&quot;form-control cantidad-paquetes  input-key&quot;]</value>
      <webElementGuid>008a21db-5237-490b-819e-285c2d57a417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cantidad[856]']</value>
      <webElementGuid>46110e1f-1b74-4f57-ba9f-18150ea14a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paquetes']/div[2]/div[2]/div[6]/div[4]/input</value>
      <webElementGuid>afbd6943-b4e1-43f8-935f-2ad53e4cb64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]/input</value>
      <webElementGuid>9d0a76e2-aef3-4093-875f-dbc27cead241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cantidad[856]']</value>
      <webElementGuid>844a002c-2e38-42bb-969f-f64940c4ce37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
