<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ok_from (6)</name>
   <tag></tag>
   <elementGuidId>ba69d6d8-2499-4d31-a3f8-2786b426d414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b99d5fd4-0f44-47aa-9bfc-3a34e9859a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fd5b704-4ed1-47b1-b743-0d0cd091258b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from</value>
      <webElementGuid>6707192f-6a5e-4fc8-9469-1a131cf1f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>yyyy/mm/dd</value>
      <webElementGuid>a1d5a0b3-f257-4c97-97f7-9eb67a9ebecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>7c446cfe-fe99-43b4-b01a-85745e1258b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from&quot;)</value>
      <webElementGuid>e191d66e-ea90-487d-ac92-7ae567ca2304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from']</value>
      <webElementGuid>71d73376-fc18-4b34-b7ca-38f79fe7ce9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='statisticsform']/div/div/div/input</value>
      <webElementGuid>a08ac9c0-019d-4640-aca6-0b8588ca091f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>38a31f47-8345-43dc-b40a-094f48a1655d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'from']</value>
      <webElementGuid>61d987c3-7d25-4e5c-a78d-dcaba168d72d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
