<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_cantidad960 (1)</name>
   <tag></tag>
   <elementGuidId>e37abb34-4799-4a18-93b6-2ccf8f9838aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cantidad[960]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cantidad[960]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cbdadb0-c244-4971-9c2d-93e9b0fbea38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d6179fd-e755-4326-87fc-64b5161a9dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidad[960]</value>
      <webElementGuid>11b77a07-c03e-49cd-8b05-011f9cf6cdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cantidad-paquetes  input-key</value>
      <webElementGuid>f8fcbc76-a4ec-4a6f-b393-eba28b658e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>c887cc90-bc20-49b2-ae22-c715f472517f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f5c252f-769b-4a7e-9b60-4d1ac51be7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paquetes&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 item_cajas&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;input-group input-cantidad&quot;]/input[@class=&quot;form-control cantidad-paquetes  input-key&quot;]</value>
      <webElementGuid>365188df-2187-404c-b60a-8ca7f987b797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cantidad[960]']</value>
      <webElementGuid>ffd5654a-63b4-4f03-af6c-8eb1d6bf4bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paquetes']/div[2]/div[2]/div[2]/div[4]/input</value>
      <webElementGuid>68e10f63-52cc-409a-ac9a-eb7cad062cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>428631e0-97f5-4be0-93ea-cb1fb0bf1efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cantidad[960]']</value>
      <webElementGuid>d8e884be-3784-41da-892d-84a7fe65a678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
