<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QUINTA___BVID__54</name>
   <tag></tag>
   <elementGuidId>f518d1ee-d098-4efe-a8fa-98e8a20d49a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__54</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__54']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ae16dcd-d603-4881-a5a1-2a7153adad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e3de6a4-f3e5-45c7-a0a1-f668c69c3bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre de via</value>
      <webElementGuid>48a10ad3-776d-4f78-b8b3-773a82b6974c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9f889a39-c42d-411d-bb32-28be4db746e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__54</value>
      <webElementGuid>f9f1ab51-2ed6-4d67-b247-2aabc70c25d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__54&quot;)</value>
      <webElementGuid>e1dcd67d-3b59-4574-81cd-ac5db9e935e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__54']</value>
      <webElementGuid>7b63565b-a9ac-4b1e-99ec-883d097d5148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__53']/div/input</value>
      <webElementGuid>5dd6af54-218a-4f64-9349-918aa6c3f7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div[2]/div/div[2]/fieldset/div/input</value>
      <webElementGuid>249fdf92-944c-47e1-8d6a-a62c9f48fb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nombre de via' and @id = '__BVID__54']</value>
      <webElementGuid>35aeef48-20bd-48ad-886f-2ce5f8514e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
