<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_input_856</name>
   <tag></tag>
   <elementGuidId>c4076c07-1378-4885-ad21-444712710675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_856']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_856</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef3c88d3-acb6-4bc5-a35d-db03817b9cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be8a6d9b-8c90-45e6-8429-c6481133ce52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-empaque-856 input-key2</value>
      <webElementGuid>f4fe5c85-0a7d-424f-9109-a91d35329752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_856</value>
      <webElementGuid>052e3055-07d2-4286-8062-8358bdad99b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>195</value>
      <webElementGuid>c306e724-0b2b-404a-ad50-f5b7dfe28166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>appCajasJS.clickChange(this);</value>
      <webElementGuid>003233fc-501a-45ea-b8b2-3fc212ea1779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_856&quot;)</value>
      <webElementGuid>29771a75-8474-4cf6-b7b6-08c47533e542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_856']</value>
      <webElementGuid>2cf1b84c-f7f6-4c43-be71-0ecca5cf4ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='blueTable']/tbody/tr[6]/th[5]/div/input</value>
      <webElementGuid>5590df58-3575-4018-8481-5ccdf84a6287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/th[5]/div/input</value>
      <webElementGuid>620ddd61-0ea7-4768-b6a3-285e455520ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_856']</value>
      <webElementGuid>1a0b61d3-d6de-4d2f-bc5d-2a4cbb6cee7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
