<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZONA CLIENTES__password (9)</name>
   <tag></tag>
   <elementGuidId>61da2434-b10b-4a90-8e51-4804e66ce32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c99663d1-73d8-4cd1-abd1-87fb5bbd0e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3c9e2ebc-dc54-4a49-a1b6-683b7179efde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_password</value>
      <webElementGuid>5c7cc059-4971-4555-83b9-8f5fd1d8604d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_password</value>
      <webElementGuid>99933062-6eac-4ecc-97da-b78b34169648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>61322490-2255-4e2c-8efc-695fed3ccfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>e19d7f55-99e6-440a-8ccf-480d84d7e034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3abf37a1-6527-4249-a0c9-3971cc4fc296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_password&quot;)</value>
      <webElementGuid>952dfac5-8ee9-404e-911e-8bf6e90f01b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_password']</value>
      <webElementGuid>aff2fd13-f9f6-411b-8249-1b662a12266d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f529d5b5-a440-4f8b-ac75-e2fa4e50f5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = '_password' and @name = '_password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>2d52fd9f-067b-4492-b8e7-383564dff4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
