<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mximo 20Kg___BVID__94</name>
   <tag></tag>
   <elementGuidId>d24b8844-98c3-4786-b9fc-68bd7a81c7b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__94</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__94']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ced60a93-5aa2-4da4-bd55-bb27051cc259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f1098aef-e693-45be-8c21-d3c021bfb9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alto* (cm)</value>
      <webElementGuid>b36458c0-541e-4ac1-8aad-a3712faba56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb4713ec-6b5b-4e38-bd4b-97503e02da9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4216b34b-b812-4bdd-8250-a7cd1aa7b29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>0f9928a8-ad08-43a5-8fe1-76e1f9d812eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e0c05eac-c9c1-4e98-81ab-e6416d57a9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__94</value>
      <webElementGuid>5210b46e-851a-40e3-934e-824fb9dfc995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__94&quot;)</value>
      <webElementGuid>99fdb348-cb10-4699-951e-4f99632998be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__94']</value>
      <webElementGuid>f57f9e1f-b836-4190-85b1-b7f2cb120d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__93']/div/input</value>
      <webElementGuid>1ade5583-2f74-4687-98fe-d0b0b2ccd8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div[2]/fieldset/div/input</value>
      <webElementGuid>b0f4b5ac-697b-44b0-8437-5bf93ed11197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Alto* (cm)' and @id = '__BVID__94']</value>
      <webElementGuid>7ae172f6-093b-48fa-99a4-45f9a33b8f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
