<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agregar Direccin Nueva_input-99 (1) (1)</name>
   <tag></tag>
   <elementGuidId>cbab821a-1b27-49df-9059-4a3fcc2b237b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-99</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-99']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7e8907d-edc8-43ec-8c00-bb5df2c47d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-99</value>
      <webElementGuid>cae2899e-c722-4c93-b5f5-d93cf4d7770d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9dd013ba-51ff-40dd-a56c-aa21af84181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email*</value>
      <webElementGuid>cd01b329-1964-4a15-b6a1-21aa09f7c291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a6ff6a8-0dfc-4cbb-9a5a-72d342d7e02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-99&quot;)</value>
      <webElementGuid>4dc03a16-7d4c-4c5d-bacb-4131474fcf3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-99']</value>
      <webElementGuid>c5105ff5-d4b2-4259-b3ce-70fe32dd1e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__14']/div/input</value>
      <webElementGuid>3cb4b4a1-2bf6-4128-b0b8-9751cfc0f64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/input</value>
      <webElementGuid>2d307f6b-25d5-4222-9657-b2198dbd4922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-99' and @type = 'email' and @placeholder = 'Email*']</value>
      <webElementGuid>13309898-527c-424b-9bad-06789b0361df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
