<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_input_858</name>
   <tag></tag>
   <elementGuidId>3acc0737-1b39-403e-8f9c-f2ac0d3ebec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_858']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_858</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7516bcd1-e114-4213-804d-6b0d408b8837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0746cd41-7ff1-4fc9-9d52-d5ecadd4c705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-empaque-858 input-key2</value>
      <webElementGuid>9fed980b-5080-4de5-bab2-a3b6fb4098aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_858</value>
      <webElementGuid>96306f84-a324-4149-929e-2c04de2b2285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c9b141bd-775b-4c5f-82f7-6fc5a4fe8634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>appCajasJS.clickChange(this);</value>
      <webElementGuid>5a79e9ae-9a1c-43fa-b0d1-c9e211af71ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_858&quot;)</value>
      <webElementGuid>13d408ff-0ec2-44a0-8e87-f80357690193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_858']</value>
      <webElementGuid>03f2a352-644e-4a83-846b-293d82e62c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='blueTable']/tbody/tr[5]/th[5]/div/input</value>
      <webElementGuid>aa4acfcf-54a1-4fa3-9e88-1693baa77057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/th[5]/div/input</value>
      <webElementGuid>16ff8b34-7cf3-4e18-a2c5-123a00d1079f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_858']</value>
      <webElementGuid>70e1da27-165c-4c68-9d6c-f333c6d51722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
