<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VALIJA-DOCUMENTOS___BVID__36 (2)</name>
   <tag></tag>
   <elementGuidId>15ae43c4-3cba-4ede-a387-48950c17ca19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__36']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__36</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76b89f90-1c9e-4a58-bd62-11a84c05a59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdfd9797-7f01-4f35-a46b-66dbcba8eb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>observaciones</value>
      <webElementGuid>fc4024cc-ef48-4f07-8ddc-b69c17eaa58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e32027a4-4caf-4925-87ce-58a3912e33b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__36</value>
      <webElementGuid>4c343ff2-5417-4d5e-9d72-6a730b9d810d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__36&quot;)</value>
      <webElementGuid>7e5c6eef-d237-43be-89fe-0650103707c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__36']</value>
      <webElementGuid>987e498a-7ddc-40ed-8ae1-28c278fa2364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__35']/div/input</value>
      <webElementGuid>87842c2c-1695-4cd9-9227-b1677643f46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/fieldset/div/input</value>
      <webElementGuid>c54efa47-dd11-44ab-b7d2-5e93c0fbc636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'observaciones' and @id = '__BVID__36']</value>
      <webElementGuid>6f9d2e40-b33a-42e0-b298-fd2046b9aa59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
