<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZONA INDUSTRIAL___BVID__64 (3)</name>
   <tag></tag>
   <elementGuidId>1c796ea5-f345-4b8f-8391-b58a55c6b130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__64</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__64']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b30ddb37-5bfa-4722-be2a-ba44cf0f5610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c49771de-1223-48b7-9f41-3e601cbecf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lote</value>
      <webElementGuid>23152462-7f89-44cd-989d-b38449d9de5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3ac7da7a-1960-400f-be0a-8765d08ad9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__64</value>
      <webElementGuid>0fc0d8e9-3fc1-4133-8d48-cf336be6279e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__64&quot;)</value>
      <webElementGuid>9dfa6557-d668-4708-bcdf-8aa3fc11365c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__64']</value>
      <webElementGuid>f85b1f33-ef9c-467f-833d-a9ef32dc4feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__63']/div/input</value>
      <webElementGuid>6b6308f2-8a35-4e47-ab6a-ddfa21d6d5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[3]/fieldset/div/input</value>
      <webElementGuid>8c1d5dbb-93d2-40ef-9cc6-c89c6f5ac4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Lote' and @id = '__BVID__64']</value>
      <webElementGuid>cf31b324-0fcb-4b13-8d02-292acba29d31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
