<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_cantidad855 (1)</name>
   <tag></tag>
   <elementGuidId>f67423ce-4cd3-47e2-a078-bffdb5e6613d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cantidad[855]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cantidad[855]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>659bd673-5b1e-411b-8146-b509c2d60182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15897103-37f9-420f-bb5e-1f2ba2af693f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidad[855]</value>
      <webElementGuid>98aeb569-fdef-49e1-bcba-44b7c1c26547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cantidad-paquetes  input-key</value>
      <webElementGuid>d487252f-38c9-4f8f-9760-009d07d95324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>68e89117-a74e-4cbe-9485-c33e3375826a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ab6359d-e8a8-4b3d-9516-b6d61b28a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paquetes&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 item_cajas&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;input-group input-cantidad&quot;]/input[@class=&quot;form-control cantidad-paquetes  input-key&quot;]</value>
      <webElementGuid>40f6e232-58bf-465b-81ee-269f05b3b953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cantidad[855]']</value>
      <webElementGuid>60e180a8-620a-48e5-b9d9-3943e93f9180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paquetes']/div[2]/div[2]/div[3]/div[4]/input</value>
      <webElementGuid>7b8a53bb-03f8-4971-b78c-def4d2c7cdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/input</value>
      <webElementGuid>f93c2833-3737-450e-9093-848676d95770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cantidad[855]']</value>
      <webElementGuid>75945274-cea7-49bb-8f43-74800dc743de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
