<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agregar Direccin Nueva_input-1 (5)</name>
   <tag></tag>
   <elementGuidId>66f63305-0a4d-4e4a-8c9b-600c195d6607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1beee44b-8d58-4046-a9da-50b666d380f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1</value>
      <webElementGuid>d5256912-97bf-49d5-8d1d-7ef412c8489f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2166fe3a-3014-486d-af6e-fdaccdc026af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre de contacto*</value>
      <webElementGuid>26cb737a-0b99-45c7-9bba-5e6ac355a016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f18788f5-ce32-4ab9-8420-830fce2ff625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1&quot;)</value>
      <webElementGuid>627b9a02-b799-4a0d-81e4-e02647d65b24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1']</value>
      <webElementGuid>895833bb-50ea-447e-bf36-2fc86dff5c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__12']/div/input</value>
      <webElementGuid>b3ece76c-8683-4e24-8ba1-41f734db4bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>aef53479-dd08-4659-b5b1-e19c5f5b239a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1' and @type = 'text' and @placeholder = 'Nombre de contacto*']</value>
      <webElementGuid>4ac7ef7a-630e-4e5e-b2f5-b555d6cb9d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
