<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UTILES DE OFICINA_txt_paquete_valor (2)</name>
   <tag></tag>
   <elementGuidId>71cd6960-8142-4ed0-b2b8-998657ca61cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_paquete_valor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_paquete_valor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9df0e420-f99d-452f-bbeb-dc093118b28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0f988706-9c81-47f9-aa0f-272aca4b6652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>446d773e-37c8-4bc7-8f37-6687578248f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>20ccdc86-fcb4-457b-bf20-c7a575d93456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);</value>
      <webElementGuid>02b672bf-59d3-40fe-ae21-32a50fb81363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>360fab2b-6f0d-4d74-b794-f3b1978abe4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_paquete_valor</value>
      <webElementGuid>41a6494a-3e16-4478-b522-3f19d0342f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_paquete_valor</value>
      <webElementGuid>7ab56cf8-b6ff-41ca-b7af-8c2fe8b4a75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Valor S/</value>
      <webElementGuid>a6da997d-3c4c-4b1a-a0f4-ab9dc7ad7d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt</value>
      <webElementGuid>02a8290d-3aeb-4a02-bc3c-432b2d1223e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Recuerde colocar el valor del producto real, en caso de pérdida o robo este será el monto a gestionar</value>
      <webElementGuid>b01609ab-5e7d-42dd-9e7c-048281a1c3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_paquete_valor&quot;)</value>
      <webElementGuid>fb4d92b6-9388-4043-9961-ba0d9f7fe2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_paquete_valor']</value>
      <webElementGuid>732bbc36-5211-45da-8d6d-2c531b4b5106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[2]/div[4]/input</value>
      <webElementGuid>9ced45f0-c7bb-4d4c-bf4b-677e476c9889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[4]/input</value>
      <webElementGuid>53acf3d8-848d-4e75-976f-d886c658a843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'txt_paquete_valor' and @id = 'txt_paquete_valor' and @placeholder = 'Valor S/']</value>
      <webElementGuid>01f3de28-ed88-478b-ba78-357b045f518b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
