<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agregar Direccin Nueva_input-2 (4)</name>
   <tag></tag>
   <elementGuidId>41dd3cb1-a990-454d-9169-416fc291d79c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8f1a1f9-33d5-46da-bcc9-90d5dbe5d3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2</value>
      <webElementGuid>a5c013c8-5a46-4c38-98d4-d2ee4381ae1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>b6f6b18f-2316-4030-97b3-0dea5f9c3235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Teléfono de contacto*</value>
      <webElementGuid>75d8f12a-5100-4fe9-a3f7-553549298a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a196c08e-533b-4cb9-bb84-16e2007b3f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>([0-9]{1,3}[0-9]{3}[0-9]{3,4})</value>
      <webElementGuid>838c506f-1eb7-4a84-a8d6-903cd34391fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2&quot;)</value>
      <webElementGuid>e5311420-3f3a-4cc6-a60a-575715b8eb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-2']</value>
      <webElementGuid>3a8b6cf2-863a-4243-8809-2eb6ab0ba241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__16']/div/input</value>
      <webElementGuid>6bb4382d-6950-416d-ae17-6dd5d58b7ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/input</value>
      <webElementGuid>086d2bcb-c99b-475c-9651-edafc896cbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-2' and @type = 'tel' and @placeholder = 'Teléfono de contacto*']</value>
      <webElementGuid>977276a7-ab12-4307-9870-cd45a31b2e16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
