<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZONA CLIENTES__username (5)</name>
   <tag></tag>
   <elementGuidId>cb2b5c01-c7a5-41de-ae9e-7d7f0145b049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb55113f-b9bb-4145-9bfc-9657cc4b4095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3390b832-bbee-48f0-b878-464288969a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_username</value>
      <webElementGuid>0e642e66-c805-4fc7-9a39-427ed7e711c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_username</value>
      <webElementGuid>1082806a-6fe1-440f-b43e-abdad0e54a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>63406841-7e5b-4d52-9af0-a79908fec1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>39d1446a-c9c7-4d40-9dc1-54dc12413411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eeb09d84-e0c1-486d-94f5-a997eb262a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_username&quot;)</value>
      <webElementGuid>10777458-a4a8-4443-9d5a-a44268eea28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_username']</value>
      <webElementGuid>5b9b082a-1e68-4d14-a7d1-e1139b4e801c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>423d0ce3-2dd2-467e-9b6c-47adb36b34f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_username' and @name = '_username' and @placeholder = 'Usuario']</value>
      <webElementGuid>db1178e5-21eb-44e0-a81a-4a786297e98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
