<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_El apellido ingresado debe ser igual _544e76 (1)</name>
   <tag></tag>
   <elementGuidId>29c2e2a4-47de-4a91-b385-486883902a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_digito_verificador</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_digito_verificador']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b314eaf8-f79d-4789-be4d-b702e6ba7fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value> text</value>
      <webElementGuid>d6d0a2c9-b34a-4878-947a-c28c418ad275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dfd1b449-df56-496a-aaa5-0381349cb2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>05a39bc4-6297-4722-bbdf-b29013ee39d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>26805dad-e837-42bd-8bcc-e47c0525cfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>INGRESE PRIMER APELLIDO</value>
      <webElementGuid>d053938a-207a-4e68-9ae3-e5e749031b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_digito_verificador&quot;)</value>
      <webElementGuid>9c3708fd-31ec-468a-890d-4ff2ef489ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_digito_verificador']</value>
      <webElementGuid>23df9446-a275-40c0-af63-a4469b8c7f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoDigitoVerificador']/div/div/div[2]/div/div[2]/input[2]</value>
      <webElementGuid>608dbc5f-506f-407d-b0fd-2f7ad21c138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input[2]</value>
      <webElementGuid>f4019bca-5b8b-41ef-b4d3-40426e397660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = ' text' and @id = 'txt_digito_verificador' and @name = 'txt_digito_verificador' and @placeholder = 'INGRESE PRIMER APELLIDO']</value>
      <webElementGuid>dddc31a4-549e-4c05-a7e3-4d50faaac70d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
