<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OLVA ALMACEN - AV. ARGENTINA 4458 - C_1e1a8d</name>
   <tag></tag>
   <elementGuidId>cbe51ae5-88fe-4540-b542-37a4eb092579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_clave_seguridad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_clave_seguridad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b34f32b1-5b8b-4b63-9d6d-4fe8651c0037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e168cd2f-d177-46e7-ac00-040416698d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_clave_seguridad</value>
      <webElementGuid>ec498fa5-61b1-4a57-be77-31848c6be7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Clave de  seguridad</value>
      <webElementGuid>d0940879-f36b-4c83-96ef-4287b0cecc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputRE</value>
      <webElementGuid>588d4ed4-b08c-4af1-bfcd-6ed03b44d139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_clave_seguridad</value>
      <webElementGuid>13971ef9-c451-4836-bd1d-e51d7fbb7c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Clave de seguridad</value>
      <webElementGuid>d7a79e78-65f3-4360-9e80-a44cd72a8f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1362956d-af03-4532-81fa-d3ecfd16b46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6ece6cc8-a9dc-4b68-b0f5-061a5d2021f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>2220e853-0bda-4a4a-a19c-d14e5da4aef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_clave_seguridad&quot;)</value>
      <webElementGuid>5f6f8858-05b9-426a-b4d6-9aabfd396609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_clave_seguridad']</value>
      <webElementGuid>33fe389d-4527-4449-9be7-5b933806d3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[7]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>f091eac0-6f6f-4265-a4be-44a56e233fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>a7edbdfc-3d31-42d8-aaed-ba7a82e3812b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt_clave_seguridad' and @placeholder = 'Clave de  seguridad' and @id = 'txt_clave_seguridad' and @title = 'Clave de seguridad' and @type = 'text']</value>
      <webElementGuid>0c4e70d9-2223-488e-a8f0-8a9c9f38e985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
