<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_frmListGuiasTransp_numero</name>
   <tag></tag>
   <elementGuidId>a9e8ee78-5976-4290-b9da-a2fcc0fcaa76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmListGuiasTrans:p_numero']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f3eb1b8-8d15-415f-8bb7-8719b868e84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmListGuiasTrans:p_numero</value>
      <webElementGuid>3f1dc162-f0a8-4880-beb9-d2cbd99cc6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmListGuiasTrans:p_numero</value>
      <webElementGuid>e10ce541-a11c-49fe-8b8d-fd3ad9da719d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c14e2d8-e92a-4d55-98d7-247d247b9d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>guiaDespachoJS.saltaBotonBusquedaAvanzada(event)</value>
      <webElementGuid>5ef3a98a-43d3-4df7-9ed6-59699add91c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>e956bd16-d435-4c29-8806-5eb2c032ddac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>53af7903-13ae-4ed6-80b4-ed0a40f8f82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fd41634-ed3e-4335-9a7c-4172a84d4618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c43c8b6-417e-4b75-8313-34ba5f95d2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmListGuiasTrans:p_numero&quot;)</value>
      <webElementGuid>07709b02-1d88-4ed0-9313-1f6c0ddf25bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Georreferenciacin Manual_iframePrincipal</value>
      <webElementGuid>e4305a39-9108-491f-a07f-0f7219218e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmListGuiasTrans:p_numero']</value>
      <webElementGuid>1b36ce2e-54d7-4a59-bb38-25d56fa8d340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='frmListGuiasTrans:j_idt11']/div/table[2]/tbody/tr/td[4]/input</value>
      <webElementGuid>f236d4f0-f7ae-4aaa-a2c1-e6ee3006249e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>17f5be9c-8617-4552-b3b4-78fd4ff1601f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmListGuiasTrans:p_numero' and @name = 'frmListGuiasTrans:p_numero' and @type = 'text']</value>
      <webElementGuid>641e7610-d9ef-4266-944a-2094c91bce8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
