<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Fecha del recojo (2)</name>
   <tag></tag>
   <elementGuidId>f220bb44-dbb5-462d-b020-aadefba912ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__23__value_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='__BVID__23__value_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8e1653f3-4e25-4cf3-afe0-74dd7a7096bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-break text-wrap bg-transparent h-auto text-muted</value>
      <webElementGuid>f9b3ce05-bd8e-4c73-aa69-8d37f48fbfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__23__value_</value>
      <webElementGuid>625b1a99-53e8-41f3-ab89-87490ed03ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>__BVID__23</value>
      <webElementGuid>747ec5fb-a473-4386-be44-8b52061a86ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha del recojo*</value>
      <webElementGuid>b860e1c8-36c2-4f1c-869e-825a6878456a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__23__value_&quot;)</value>
      <webElementGuid>a21e3a2f-a0ed-4439-b582-0621a1f2d026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='__BVID__23__value_']</value>
      <webElementGuid>cd5ea114-4b50-4557-9703-036e9c10cad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__23__outer_']/label</value>
      <webElementGuid>410dd65c-913e-429e-aa6b-cb1103ddfd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿A qué hora se hará el recojo?'])[2]/following::label[1]</value>
      <webElementGuid>954f90fc-6dd9-4845-903a-88ff95330500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mm'])[2]/following::label[1]</value>
      <webElementGuid>ba423a69-d068-42b5-b856-db78a331c005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué dia se hará el recojo?'])[1]/preceding::label[1]</value>
      <webElementGuid>b164c2f9-87a3-40b2-8603-2a9f3150a4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Contenido Fragil?'])[1]/preceding::label[1]</value>
      <webElementGuid>25588291-3e74-4ffd-9614-237fe77559c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fecha del recojo*']/parent::*</value>
      <webElementGuid>bf1ba4ff-1ea9-437b-9f44-65e5716f6519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/fieldset/div/div/label</value>
      <webElementGuid>9505a796-6737-439b-93d3-897a022ab2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = '__BVID__23__value_' and (text() = 'Fecha del recojo*' or . = 'Fecha del recojo*')]</value>
      <webElementGuid>7114f0db-8f9d-467b-baf7-416d19e03852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
