<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Fecha del recojo (1)</name>
   <tag></tag>
   <elementGuidId>eef74cd1-5f04-42f2-891f-75fd94170346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__23__value_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='__BVID__23__value_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>014e4f8c-ddd2-4335-8908-e3cc048fc9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-break text-wrap bg-transparent h-auto text-muted</value>
      <webElementGuid>292977c7-1d29-4373-b96e-23e0167297ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__23__value_</value>
      <webElementGuid>68827da0-89f5-45ee-b73e-8e306ce96e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>__BVID__23</value>
      <webElementGuid>c84013c5-a7b4-4c2e-8972-a64c9e94aadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha del recojo*</value>
      <webElementGuid>452c4af7-9e97-4e56-aba4-10a38d4b925b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__23__value_&quot;)</value>
      <webElementGuid>8490ab3a-6b83-4d87-b2d2-82543e18fa18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='__BVID__23__value_']</value>
      <webElementGuid>d1deff94-64dd-4cdd-b04e-b111846da588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__23__outer_']/label</value>
      <webElementGuid>dac1c125-11a8-4f1e-87d4-360f9d4da251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formato 909808707 / 16113000'])[1]/following::label[1]</value>
      <webElementGuid>d02a2b3e-3908-48e3-946f-b8dcc400b242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar Dirección'])[1]/following::label[1]</value>
      <webElementGuid>2d9c7ada-09ff-4cf6-a044-d7ae3c620a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué dia se hará el recojo?'])[1]/preceding::label[1]</value>
      <webElementGuid>0d0a76be-1477-421f-addf-116c7c4da9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Contenido Fragil?'])[1]/preceding::label[1]</value>
      <webElementGuid>0e49081f-f248-4813-9c07-a4052da21470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fecha del recojo*']/parent::*</value>
      <webElementGuid>ab86adb8-cf5f-4f23-959f-a909425348d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/fieldset/div/div/label</value>
      <webElementGuid>42746b1d-399c-4751-92da-25bab2a13f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = '__BVID__23__value_' and (text() = 'Fecha del recojo*' or . = 'Fecha del recojo*')]</value>
      <webElementGuid>2b413d35-09fb-42f4-bf40-f03db7783824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
