<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label (2)</name>
   <tag></tag>
   <elementGuidId>c752671f-81e7-4adc-8d8a-460a62c8a7c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='op_forma_pago_tienda']/ul/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8d414fe1-c974-4280-b813-345a843a35f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ckbTerms</value>
      <webElementGuid>1dc12ec0-792a-40fa-a504-073374f0364a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;op_forma_pago_tienda&quot;)/ul[@class=&quot;buttons&quot;]/label[1]</value>
      <webElementGuid>aa130fff-5084-45ce-a5b9-1f7dc9cb1ba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='op_forma_pago_tienda']/ul/label</value>
      <webElementGuid>7a176e92-20be-4520-8743-5be1729b4bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c2b212f4-7c14-4f2d-8401-bb1fd1e4a18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
