<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>416c5519-283e-4adc-afe9-d2e8aa1d99c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='op_forma_pago_tienda']/ul/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>736c8333-eaca-4330-a7bf-e4e6c1a9626e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ckbTerms</value>
      <webElementGuid>4b433198-395c-472a-9b6c-cbb2fbdc12e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;op_forma_pago_tienda&quot;)/ul[@class=&quot;buttons&quot;]/label[1]</value>
      <webElementGuid>dd9707f1-301b-40eb-9fdc-f859642b701e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='op_forma_pago_tienda']/ul/label</value>
      <webElementGuid>ea352e0c-9ad6-48e2-b224-5bcfd702d8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d5c9a2f5-7713-4e35-b8de-8d2bcddb2e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
