<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_GUIA DE REMISION REMITENTE</name>
   <tag></tag>
   <elementGuidId>6586c556-a997-4655-bd06-917e13ad8424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmListGuiasTrans:cbotipoguia_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2b99994e-ec85-4036-b745-cfb1f0c305dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>5e45d84d-84b2-4dbc-aa50-ce1c1b8579bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>GUIA DE REMISION REMITENTE</value>
      <webElementGuid>a4dc5017-8a0a-4ba7-9a75-74c503d7844a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e831584a-a648-4d27-b398-59a9cac4449c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8105c93c-48f5-4c4c-8dd1-f1148a17053e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmListGuiasTrans:cbotipoguia_1</value>
      <webElementGuid>0bd08e3e-f3c2-4d0e-ae95-617a638a70a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GUIA DE REMISION REMITENTE</value>
      <webElementGuid>4c1225f8-ef41-4d3d-9ce3-4d7ef2cb0232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmListGuiasTrans:cbotipoguia_1&quot;)</value>
      <webElementGuid>a5c7f83f-2e54-4a94-82d9-6ae1d50f95cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Georreferenciacin Manual_iframePrincipal</value>
      <webElementGuid>bd6b8fe8-6af8-4e74-b69e-84a6be8deb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmListGuiasTrans:cbotipoguia_1']</value>
      <webElementGuid>58ee25ba-6dce-44c7-a4c9-b3a553e1d44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmListGuiasTrans:cbotipoguia_items']/li[2]</value>
      <webElementGuid>10ac6a9b-6b8c-43a0-be3f-01630b875aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Seleccione tipo]'])[3]/following::li[1]</value>
      <webElementGuid>a0954f0f-7830-456a-9ca2-71bd28bdd541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::li[2]</value>
      <webElementGuid>49c6591a-3052-4473-a129-18342af842f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GUIA DE REMISION TRANSPORTISTA'])[2]/preceding::li[1]</value>
      <webElementGuid>ad5549a0-32b7-489e-8011-f0962f8d5bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::li[2]</value>
      <webElementGuid>72be2072-e24a-48d6-aaa1-e99dff887ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>c947a338-c6f0-41c8-9c75-c76608d56e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmListGuiasTrans:cbotipoguia_1' and (text() = 'GUIA DE REMISION REMITENTE' or . = 'GUIA DE REMISION REMITENTE')]</value>
      <webElementGuid>c3136e5e-56f4-4505-872e-7117ef6092d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
