<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Nota Credito  Debito</name>
   <tag></tag>
   <elementGuidId>a5af1ee6-9148-4458-b89b-724072ee2f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmPrincipal:tree:0_0_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1f8accd0-74c7-4397-84e7-ce46fcf4cc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_0_3</value>
      <webElementGuid>d9657b8b-faca-4319-9415-e4b53eae9cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowkey</name>
      <type>Main</type>
      <value>0_0_3</value>
      <webElementGuid>f9c318f0-efc1-499c-bafd-82002dfb39ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nodetype</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>2b9e3e0f-696f-495a-8edf-de7c2f0cd68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-treenode ui-treenode-leaf ui-treenode-unselected</value>
      <webElementGuid>85c393d6-1773-4179-8b69-9a782d3ce8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nota Credito / Debito</value>
      <webElementGuid>d42fd863-debb-4b85-aacd-3fcb05a5a7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_0_3&quot;)</value>
      <webElementGuid>00330604-b388-40ef-8f8a-d049e2761a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_0_3']</value>
      <webElementGuid>d2d5b56e-6c14-4b74-a4a3-700d85fe1d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_0']/ul/li[4]</value>
      <webElementGuid>5e91619f-264a-4468-8977-5dd0e02c3833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venta'])[2]/following::li[1]</value>
      <webElementGuid>8d6ffe04-d3ae-43dd-bf1a-68f6d51608ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporte'])[1]/following::li[2]</value>
      <webElementGuid>a0eef2d3-fbc7-47ed-ae80-ceb2d95b56a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edicion Tracking'])[1]/preceding::li[1]</value>
      <webElementGuid>db8b8a56-0366-4f6b-ab1c-a479eb495d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[4]</value>
      <webElementGuid>625f3c0f-94f2-4ab4-af72-6b782a35a3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmPrincipal:tree:0_0_3' and (text() = 'Nota Credito / Debito' or . = 'Nota Credito / Debito')]</value>
      <webElementGuid>97a7faf0-507b-4dfa-a6ec-1cde51e6624b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
