<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EneroFebreroMarzoAbrilMayoJunioJulio_dc5537 (2)</name>
   <tag></tag>
   <elementGuidId>6f825564-86e0-4df5-8f34-556ab1000797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.datepicker-select.orig-select-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datepicker-title-cp']/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dbc696e1-7a78-40c1-b725-684e609b53c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-select orig-select-month</value>
      <webElementGuid>b1f2978e-248d-4e66-be39-03d3997469a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2696ff87-ad16-4cd9-9d64-e0dde4539893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EneroFebreroMarzoAbrilMayoJunioJulioAgostoSeptiembreOctubreNoviembreDiciembre</value>
      <webElementGuid>f202d8c9-92ce-4fff-a3df-3a0b191c5086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-title-cp&quot;)/div[@class=&quot;selects-container&quot;]/div[@class=&quot;select-wrapper select-month&quot;]/select[@class=&quot;datepicker-select orig-select-month&quot;]</value>
      <webElementGuid>012b26be-4648-4a55-bd87-6660dbf595c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker-title-cp']/div/div/select</value>
      <webElementGuid>af49da54-237f-4229-bf2e-43839dd24dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar, Jul 25'])[1]/following::select[1]</value>
      <webElementGuid>bdc2fa4f-9d08-4f60-8918-67876b1c7e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[2]/following::select[1]</value>
      <webElementGuid>23222f71-c619-492a-a641-b540533247ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[1]/preceding::select[2]</value>
      <webElementGuid>1a1263bb-23c4-4841-88aa-cfc1494e2276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/preceding::select[2]</value>
      <webElementGuid>81afb347-752c-448c-b5db-c5f06b3ff2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b36f7ee3-3ce0-43cb-85bd-c0331896ab5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'EneroFebreroMarzoAbrilMayoJunioJulioAgostoSeptiembreOctubreNoviembreDiciembre' or . = 'EneroFebreroMarzoAbrilMayoJunioJulioAgostoSeptiembreOctubreNoviembreDiciembre')]</value>
      <webElementGuid>ed598d0e-595e-4dce-a283-19beff416591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
