<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_panorama_fish_eyeSeguimiento de envos (1)</name>
   <tag></tag>
   <elementGuidId>5f9232fb-0f25-4d63-be64-90355514f035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='slide-out']/div/ul/li[3]/ul/li/div/ul/li[2]/a/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>e944abe2-9112-42e5-88c1-e30190f5d1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>panorama_fish_eyeSeguimiento de envíos</value>
      <webElementGuid>464d9a68-e6ae-482b-86c2-e5f060e7bfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide-out&quot;)/div[@class=&quot;top-list&quot;]/ul[@class=&quot;collapsible expandable&quot;]/li[3]/ul[@class=&quot;collapsible expandable&quot;]/li[@class=&quot;active&quot;]/div[@class=&quot;collapsible-body&quot;]/ul[1]/li[2]/a[1]/small[1]</value>
      <webElementGuid>241c306a-da09-457f-8503-991a093f966d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='slide-out']/div/ul/li[3]/ul/li/div/ul/li[2]/a/small</value>
      <webElementGuid>9457e8d6-59b4-43cc-85a3-352e714df6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='panorama_fish_eye'])[3]/following::small[1]</value>
      <webElementGuid>7a066963-3e6e-457f-850e-617c65470189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seguimiento de envíos']/parent::*</value>
      <webElementGuid>b226a291-8615-4c7a-91a1-e23caeb8e4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/div/ul/li[2]/a/small</value>
      <webElementGuid>2feef46e-b159-42c6-b0e3-32b03d1645bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'panorama_fish_eyeSeguimiento de envíos' or . = 'panorama_fish_eyeSeguimiento de envíos')]</value>
      <webElementGuid>fc8162ab-5b16-4ce8-92b4-c5e331bc3188</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
