<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Servicios (1)</name>
   <tag></tag>
   <elementGuidId>df4467fa-1d68-4eae-8af7-6e16bbff0462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>small.facturacion.menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='slide-out']/div/ul/li[2]/ul/li/a/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>9b06f99c-7a72-4829-8f57-2c6e558027c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>facturacion menu-title</value>
      <webElementGuid>98cdcab1-9bc2-443f-9316-84bd42789081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Servicios</value>
      <webElementGuid>2ca46792-c772-4bb6-b76c-8c0a5bc1c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide-out&quot;)/div[@class=&quot;top-list&quot;]/ul[@class=&quot;collapsible expandable&quot;]/li[2]/ul[@class=&quot;collapsible expandable&quot;]/li[1]/a[@class=&quot;collapsible-header&quot;]/small[@class=&quot;facturacion menu-title&quot;]</value>
      <webElementGuid>e13a9eef-16d4-4082-ae9e-2d5fcf2ca42c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='slide-out']/div/ul/li[2]/ul/li/a/small</value>
      <webElementGuid>6e2a109b-fefa-4331-a106-32e7bdf6ab2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::small[1]</value>
      <webElementGuid>74591a72-6a6c-4b91-80e7-2912ea7f76e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[1]/following::small[2]</value>
      <webElementGuid>562fc8c2-e8cc-473b-a54b-be81a648b641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::small[1]</value>
      <webElementGuid>c4e6dde1-0f3d-429d-a487-a6ed9663403b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Servicios']/parent::*</value>
      <webElementGuid>2cfd2d1c-f1ec-4251-98c5-22f76000a363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a/small</value>
      <webElementGuid>80bd9273-5662-4977-a304-e3c0a8fa29c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Servicios' or . = 'Servicios')]</value>
      <webElementGuid>e1b6e072-8d3d-4197-b6eb-f29c6261e41d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
