<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Host (1)</name>
   <tag></tag>
   <elementGuidId>88c81f3c-6a3b-400b-a5ae-3db1104ce65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmPrincipal:tree:0_3:lblNode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77a2fc30-eded-42a4-83ec-3131f1b12579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_3:lblNode</value>
      <webElementGuid>8febd1f1-c982-4f03-8699-7336a0f402e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Host</value>
      <webElementGuid>9629a2ea-eb8a-49f7-ac5c-39a6f90fd022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Host</value>
      <webElementGuid>669031f4-1372-4262-8dce-d80835d277a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_3:lblNode&quot;)</value>
      <webElementGuid>fb30ee97-34c1-4b5c-ba43-2dff51ea7223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:tree:0_3:lblNode']</value>
      <webElementGuid>02055a98-e2b4-40e3-a61e-0bfbad1487fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_3']/span/span[3]/span</value>
      <webElementGuid>afae78b6-6424-4691-a8eb-955228156860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuración Sedes'])[1]/following::span[5]</value>
      <webElementGuid>88121c0d-73ec-482b-a344-d00c52a3073c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descuento Paquete Tarifario'])[1]/following::span[10]</value>
      <webElementGuid>92b89707-d244-4789-ba8a-5f7586faf85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticketera'])[1]/preceding::span[3]</value>
      <webElementGuid>833a9472-7a3a-4cc1-bb99-16d81afb89ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobantes'])[1]/preceding::span[8]</value>
      <webElementGuid>d1a1449b-c9cb-4873-9277-6dd625067a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Host']/parent::*</value>
      <webElementGuid>de174c7c-6b80-459a-991c-3dcb2d2f2aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span/span[3]/span</value>
      <webElementGuid>e5c0f9fc-fff3-4638-aba0-a1d0243cc420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmPrincipal:tree:0_3:lblNode' and @title = 'Host' and (text() = 'Host' or . = 'Host')]</value>
      <webElementGuid>646134e7-671d-4c8a-81bc-07bea496a0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
