<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HH091011121314mm0030 (4)</name>
   <tag></tag>
   <elementGuidId>f2c45c34-c344-4914-826b-7bd8256c74cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.vue__time-picker.time-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='__BVID__18']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b70e667-701b-42c3-bb2c-f091fca80a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vue__time-picker time-picker</value>
      <webElementGuid>26932029-7ed2-4f6a-a467-cd3d50d2ef50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HH091011121314mm0030</value>
      <webElementGuid>a56d4265-7469-45bc-9af3-223950fce08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__18&quot;)/div[@class=&quot;bv-no-focus-ring&quot;]/span[@class=&quot;vue__time-picker time-picker&quot;]</value>
      <webElementGuid>54658f14-8686-45e9-8cc5-ac10eff40288</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__18']/div/span</value>
      <webElementGuid>f4d7c1c2-7237-4088-9862-d8d78b6e07d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formato 909808707 / 16113000'])[1]/following::span[1]</value>
      <webElementGuid>41267879-3bf0-47be-80d4-50d7a38b042c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar Dirección Nueva'])[1]/following::span[1]</value>
      <webElementGuid>4620b324-1818-4d88-a359-5a10132b3d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/span</value>
      <webElementGuid>ecac5fa6-cc63-4921-a399-a80a477300f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'HH091011121314mm0030' or . = 'HH091011121314mm0030')]</value>
      <webElementGuid>1a00ff93-0b5b-431c-addd-55665601dc87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
