<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Venta (6)</name>
   <tag></tag>
   <elementGuidId>4b300ae5-0c6f-4af4-b35d-6f908ffc2ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmPrincipal:tree:0_0_2:lblNode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d8ad484-b888-4db0-952b-58d837097166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_0_2:lblNode</value>
      <webElementGuid>db22efbf-6e1e-4354-a846-dad2b81e9fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Venta</value>
      <webElementGuid>f8c3cf29-89ad-42a9-9c81-a55962410187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Venta</value>
      <webElementGuid>b9273542-b0be-486d-8932-01119b5a2607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_0_2:lblNode&quot;)</value>
      <webElementGuid>b385a34c-eeb3-4e6c-8810-139a04264759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:tree:0_0_2:lblNode']</value>
      <webElementGuid>fecdbe79-34b5-4445-889c-62dddb28fcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_0_2']/span/span[3]/span</value>
      <webElementGuid>6976f5cb-c686-4bd6-92d8-0ffaf3a94cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporte'])[1]/following::span[5]</value>
      <webElementGuid>aa083e54-fb98-4f35-92f4-8712b0b2acd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anular / Modificar'])[1]/following::span[10]</value>
      <webElementGuid>f483bd59-db94-4734-a0ab-dd9d50a650f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nota Credito / Debito'])[1]/preceding::span[3]</value>
      <webElementGuid>3a180bf4-5e6a-4f9e-b137-00b066c5d8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edicion Tracking'])[1]/preceding::span[8]</value>
      <webElementGuid>588e8833-56b9-48e9-8d9c-3967e1c45705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[3]/span/span[3]/span</value>
      <webElementGuid>0f887c4b-0865-497f-9f5c-4e99c5e5d7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmPrincipal:tree:0_0_2:lblNode' and @title = 'Venta' and (text() = 'Venta' or . = 'Venta')]</value>
      <webElementGuid>f1e62b7e-15cf-4a11-b7ff-10e8d9d1d900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
