<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Venta</name>
   <tag></tag>
   <elementGuidId>ecfa0f2b-b0df-4985-b554-30dd390b09e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmPrincipal:tree:0_0_2:lblNode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e7068cb-5330-4bd6-9031-a0d88a7314c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_0_2:lblNode</value>
      <webElementGuid>b1381de2-3b66-445c-a382-97c3bd50688a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Venta</value>
      <webElementGuid>98aaff1a-2e7c-4636-a2f9-2f9239872aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Venta</value>
      <webElementGuid>8816b32d-69af-43fe-a8b4-9a2fc659ce8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_0_2:lblNode&quot;)</value>
      <webElementGuid>3fdb4d8f-d9ea-43e8-8877-8c5e1683e1bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:tree:0_0_2:lblNode']</value>
      <webElementGuid>59aea75b-b13f-4e8f-a7bc-a17ddd88c8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_0_2']/span/span[3]/span</value>
      <webElementGuid>8261caa5-e555-4177-a8d9-31c948ba0d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporte'])[1]/following::span[5]</value>
      <webElementGuid>9c25ff3e-134f-4084-96a9-9e5667004062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anular / Modificar'])[1]/following::span[10]</value>
      <webElementGuid>b059496e-9c28-4369-8df1-2aa0c770930b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nota Credito / Debito'])[1]/preceding::span[3]</value>
      <webElementGuid>03238c43-8ad5-4c6f-a4d7-fecf49827ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edicion Tracking'])[1]/preceding::span[8]</value>
      <webElementGuid>d65d3640-0fb4-4a88-bed2-b27697da82ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[3]/span/span[3]/span</value>
      <webElementGuid>ef1ad427-9a28-4532-beee-4c360e653066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmPrincipal:tree:0_0_2:lblNode' and @title = 'Venta' and (text() = 'Venta' or . = 'Venta')]</value>
      <webElementGuid>17772ec0-e796-4e45-8b2e-c8ea9f860f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
