<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Oficinas (1)</name>
   <tag></tag>
   <elementGuidId>eaf17c2b-abb9-42bd-b314-efac0809d598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmPrincipal:tree:0_9:lblNode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>005d60cd-8784-41f4-aae2-9a73925fe78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_9:lblNode</value>
      <webElementGuid>d72b7c94-1ca2-489a-8174-d3001f612fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Oficinas</value>
      <webElementGuid>12cfa811-220b-4228-849a-51518e0c37db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oficinas</value>
      <webElementGuid>fbc19235-a933-4730-a5a6-30f929d014e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_9:lblNode&quot;)</value>
      <webElementGuid>f37cf80e-f12a-45b0-8fd3-61e18b5aa551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:tree:0_9:lblNode']</value>
      <webElementGuid>de028cac-207e-4d2f-ac3e-87a55310b228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_9']/span/span[3]/span</value>
      <webElementGuid>35bbb0b7-4909-4734-b473-63704116db7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articulo Cod 50'])[1]/following::span[5]</value>
      <webElementGuid>e430eba6-9dce-4c41-81ac-5f9986397cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contenedor'])[1]/following::span[10]</value>
      <webElementGuid>8704f03e-0603-464e-9524-162c01b3029a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicios Complementarios'])[1]/preceding::span[3]</value>
      <webElementGuid>564b5c48-1d2a-406c-be9e-14250f3cca2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zonas'])[1]/preceding::span[8]</value>
      <webElementGuid>b8af84ad-7687-456f-9432-82dd4538d4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/span/span[3]/span</value>
      <webElementGuid>14f5c0ad-b537-49be-a2c8-391cefea6754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmPrincipal:tree:0_9:lblNode' and @title = 'Oficinas' and (text() = 'Oficinas' or . = 'Oficinas')]</value>
      <webElementGuid>34ef94ac-f040-40de-8e2c-491aa8ae6a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
