<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OLVA ALMACEN - AV. ARGENTINA 4458 - CA_913efa</name>
   <tag></tag>
   <elementGuidId>1099f703-6270-4eac-adec-bcb486f4af94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='fieldset_paso1']/div[4]/div/div[2]/div/div/div/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7ab0853-bbab-48a2-b679-eaa56280e176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d5905d4-6646-4f9f-a7c6-2d19ea3cdace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OLVA ALMACEN - AV. ARGENTINA 4458 - CALLAO - CALLAO - AV ARGENTINA NRO 4458 </value>
      <webElementGuid>6cd3a689-947c-411e-870d-3991f3fd74ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldset_paso1&quot;)/div[@class=&quot;ver_si_tienda_caja&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-sm-12 col-xs-12 cls_element_item espacio_vista_xs_2 m-code&quot;]/div[@class=&quot;col-md-8 col-sm-12 col-xs-12&quot;]/div[@class=&quot;btn-group bootstrap-select form-control msg_alert_tt dropup open&quot;]/div[@class=&quot;dropdown-menu open&quot;]/ul[@class=&quot;dropdown-menu inner selectpicker&quot;]/li[2]/a[1]/span[@class=&quot;text&quot;]</value>
      <webElementGuid>d30f97e2-81db-46bb-bdac-61832ba781a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[4]/div/div[2]/div/div/div/ul/li[2]/a/span</value>
      <webElementGuid>67eac079-ebb9-4668-8673-e3ff92f4e4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[3]/following::span[2]</value>
      <webElementGuid>77da6f00-f97d-439c-9661-e0354f7300ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[2]/following::span[4]</value>
      <webElementGuid>902abf17-a08b-41fb-ba09-c21b9b83f080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA CANTA CALLAO - CALLAO - AV OFICINA OLVA CANTA CALLAO S/N URBANIZACION SAN JUAN MASIAS'])[2]/preceding::span[2]</value>
      <webElementGuid>e8cf9d31-521b-4331-8a19-e14d5cbed5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA VENTANILLA - CALLAO - CA OFICINA VENTANILLA MZ O5 URBANIZACION LOS LICENCIADOS'])[2]/preceding::span[6]</value>
      <webElementGuid>227d973d-813b-458b-8a6e-b2d3d9402f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/ul/li[2]/a/span</value>
      <webElementGuid>cc18fb31-46ca-48ee-afcf-55a4f44856f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'OLVA ALMACEN - AV. ARGENTINA 4458 - CALLAO - CALLAO - AV ARGENTINA NRO 4458 ' or . = 'OLVA ALMACEN - AV. ARGENTINA 4458 - CALLAO - CALLAO - AV ARGENTINA NRO 4458 ')]</value>
      <webElementGuid>54d1b339-b67f-4109-b667-255ee519ece9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
