<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_He ledo y acepto los_checkmark (2)</name>
   <tag></tag>
   <elementGuidId>e11edf59-cf7e-4d44-82eb-ec47b690341f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_tipo_envio']/p/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6055a81b-3150-4a13-8608-38f99297f85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>cb0ad043-72e6-409a-bd21-cc8fe2e11904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_tipo_envio&quot;)/p[@class=&quot;terms&quot;]/label[@class=&quot;container-check&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>9f4996d8-3510-41c8-819e-5d107ff6f06d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/p/label/span</value>
      <webElementGuid>1c485a96-f9f3-43cb-848f-fe7152b9558a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>bd97dc17-3a9e-42f8-bca0-8b2537e2d1c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
