<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Devolucin (3)</name>
   <tag></tag>
   <elementGuidId>3ea8a684-5207-43c6-80f4-0bdc67cc59ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmPrincipal:tree:0_4_0_2:lblNode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>11bc7693-118d-4b4b-a5d4-4e255ba56276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_4_0_2:lblNode</value>
      <webElementGuid>7a1f1437-0905-4f55-be80-94289ef5e04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Devolución</value>
      <webElementGuid>c41d4f17-c68a-492a-988b-3afe55fffb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Devolución</value>
      <webElementGuid>7d737fe1-a903-4b56-82c1-1755e425956a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_4_0_2:lblNode&quot;)</value>
      <webElementGuid>0e3a17da-b178-4a80-864d-10da4c9381d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:tree:0_4_0_2:lblNode']</value>
      <webElementGuid>765b813e-9615-4b08-825f-79340463771f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_4_0_2']/span/span[3]/span</value>
      <webElementGuid>0fb0a4da-d11b-468d-be90-ab98a9b760c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coordinación'])[1]/following::span[5]</value>
      <webElementGuid>646a7e85-e367-4d5e-9574-adcd7aec0488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PreDevolución'])[1]/following::span[10]</value>
      <webElementGuid>686f98c2-3e10-484b-8026-60ddf8d19705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Postergado'])[1]/preceding::span[3]</value>
      <webElementGuid>19e19995-5cde-4ba3-bc6c-7c63cfe00203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Devolucion Masivo'])[1]/preceding::span[8]</value>
      <webElementGuid>e0bb929d-8b35-4086-8217-19d01c470a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/ul/li[3]/span/span[3]/span</value>
      <webElementGuid>f82308a6-5e55-44d3-82c8-ad863703ef53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmPrincipal:tree:0_4_0_2:lblNode' and @title = 'Devolución' and (text() = 'Devolución' or . = 'Devolución')]</value>
      <webElementGuid>c3e876fe-27e4-4e44-9ee8-f512b88980d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
