<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X</name>
   <tag></tag>
   <elementGuidId>216544ff-a733-4dd2-a3c7-7fc3ff18c4ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='closeModal()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.button-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>591c6884-f671-4474-b331-96aa61c66e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-close</value>
      <webElementGuid>59882fde-50c3-4cd4-bbc2-1efe21953587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeModal()</value>
      <webElementGuid>443421ce-7af9-4003-b054-6cc0ccff821d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>8ea9e4c3-0207-43e1-a1ec-4117cad95c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-container&quot;)/span[@class=&quot;button-close&quot;]</value>
      <webElementGuid>4771c0d0-62ef-4e00-91ce-8b19d64b4cca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='closeModal()']</value>
      <webElementGuid>2bd5bda5-ff3c-4ae6-8220-b3ca13d2cfdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-container']/span</value>
      <webElementGuid>513b85de-6c04-4b8e-8fd7-b6b1c2ef67d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DÉJALO EN TIENDA'])[1]/preceding::span[1]</value>
      <webElementGuid>78a6fe17-4fd0-46cf-9fee-7458c79d1770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>65ec667e-e810-4a4c-94bd-5a80ef95d482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>438b5073-aeda-4056-a9fe-9edb29de95d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'X' or . = 'X')]</value>
      <webElementGuid>0d744b1b-6186-4f3d-b785-9682cff714a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
