<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_S.206.20 (S.342.40)</name>
   <tag></tag>
   <elementGuidId>cb40cabf-2688-462f-a898-3f8a0922e0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='comprobante']/tfoot/tr/th[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>723aff1e-7c94-45f0-93b6-5e5591e9c9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ffae0129-17a5-4b02-b6cc-bdc85b3f5d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>91b46117-df2a-40ed-90ba-c4143875a4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S/.206.20 (S/.342.40)</value>
      <webElementGuid>474d20d2-8817-4b8f-89bb-d29bf0a0e284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comprobante&quot;)/tfoot[@class=&quot;col l12&quot;]/tr[1]/th[6]</value>
      <webElementGuid>4daeaf9d-b7b6-4cad-88fc-d122530a0e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='comprobante']/tfoot/tr/th[6]</value>
      <webElementGuid>01ce1715-da5c-4595-a575-b23ef57155c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar Comprobante'])[1]/following::th[7]</value>
      <webElementGuid>0d41213a-c7e2-47ab-aa3c-21549ef80952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[4]/following::th[8]</value>
      <webElementGuid>7e5e58eb-3941-4f22-bd27-421189dcf7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOLETA'])[1]/preceding::th[4]</value>
      <webElementGuid>a806aa16-39c9-4d64-84bc-eccae82cd697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B304'])[1]/preceding::th[4]</value>
      <webElementGuid>0f2b91a7-8cd4-4001-9d93-1e2a68e8b3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='S/.206.20 (S/.342.40)']/parent::*</value>
      <webElementGuid>c04fad3b-54ca-4aa0-9b07-5bfe9249c06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tfoot/tr/th[6]</value>
      <webElementGuid>59775ce5-1658-4f3a-aba8-19c4a3ff1943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'S/.206.20 (S/.342.40)' or . = 'S/.206.20 (S/.342.40)')]</value>
      <webElementGuid>697df64e-5d96-41e2-8782-38bb910cda23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
