<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_peso_consignado</name>
   <tag></tag>
   <elementGuidId>4936bd6d-4f83-4c2a-8698-136ec0fab86f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@data-ng-model,'envio.pesoConsignado')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9f2ed27a-a4ee-4fec-957f-c10a241a7e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>09619023-32a9-4518-9e5f-ee9731597dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.600</value>
      <webElementGuid>fde4e223-05da-48f3-9920-0c9eed23f3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewEnvio:articuloTbl_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even&quot;]/td[7]</value>
      <webElementGuid>bdcd37bc-e167-43d1-abe8-523438574fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inicio/Page_Atencin al Cliente/Page_Meet - pvd-uiyo-xob/Page_Principal - Olva Courier/ifram</value>
      <webElementGuid>372f0296-d0e4-4aa3-88ab-96ff66ff9f42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='frmNewEnvio:articuloTbl_data']/tr/td[7]</value>
      <webElementGuid>007a016e-4c56-407c-8611-2de182c6e98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOBRE'])[2]/following::td[4]</value>
      <webElementGuid>0ce48613-1361-40dc-af18-4b9b16ad3594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Artículo'])[1]/preceding::td[1]</value>
      <webElementGuid>2669a5ab-8dfe-44b4-9a16-f87c8cbc5f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[1]/preceding::td[1]</value>
      <webElementGuid>d9275c78-f976-4f4b-a38b-6d1193db6b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2.600']/parent::*</value>
      <webElementGuid>dea751bc-db29-4bb0-9d5e-307b64e13b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/div/div/div[2]/table/tbody/tr/td[7]</value>
      <webElementGuid>163faf33-406f-47e2-8b2b-0797802d3f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '2.600' or . = '2.600')]</value>
      <webElementGuid>acf95c54-e0cb-4b09-97fc-ed2f13d3e328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
