<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ACEPTAR - COOKIES</name>
   <tag></tag>
   <elementGuidId>470bd472-7d18-4bcf-beed-e6633fec99c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;onetrust-accept-btn-handler&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_aceptar_tipo_envio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecdd9fac-3348-4c2b-ac1b-250c3464aa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_aceptar_tipo_envio</value>
      <webElementGuid>8c177c0d-f777-49e0-ba00-25c1f7a6e56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c07df275-69ea-41ad-9c9a-42763d8aeffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>245c9f86-f755-49ae-885c-e88334110ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>149c257e-2c1c-44bd-bff5-287aaf00fa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_aceptar_tipo_envio&quot;)</value>
      <webElementGuid>7ac506a1-8ae8-4e01-85d5-2d787ef90eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_aceptar_tipo_envio']</value>
      <webElementGuid>9d710575-4d49-49af-9efb-26f4ee6e8155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/button</value>
      <webElementGuid>6d754162-33f8-4951-b245-e0fcfaff90fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVÍOS DE TARJETAS, AGENDAS Y CAJAS NAVIDEÑAS'])[1]/preceding::button[2]</value>
      <webElementGuid>1fb18a1d-0271-4fdb-8331-dc5a6f5e0689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUAR']/parent::*</value>
      <webElementGuid>6763d890-5ff4-4a44-b2cc-692eadf62420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fb734122-c72a-4708-9eed-04d242de2648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_aceptar_tipo_envio' and @type = 'button' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>4ff6badd-a553-4784-bb86-d581097851ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
