<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal_1</name>
   <tag></tag>
   <elementGuidId>4b5761fa-f483-452c-b2bd-0c19e38419de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>edc659f6-54b1-4e54-a9eb-01f49f9b7e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>2963763e-f37f-4539-94a1-2a251b0632eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>d50409d2-f975-4518-a3ec-4da91fbaf376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/reportes/ventas/reportePreVentas.xhtml?nodeTree=Reporte Pre-Ventas&amp;codeTree=070113&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NTgwMTcyMCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNjcwOGQwNGQtMmRiNy00Yjk3LThlYWUtNzViNjJjYjJkNjZmIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.k1wdva0VEZqYRSPv74GOFOG3DMIV53kNK53Oo_g_32Y</value>
      <webElementGuid>081c0314-0595-4e3c-a84b-d77a3f0b4426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>d13f68cb-3a44-48ec-9324-5432d9388ff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>7e781604-adb8-4570-b051-2391912145d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>53f99a78-fd26-417b-8ee2-a7e41bb1c391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0023fe34-a343-4480-a1c1-5cc541ba9e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/reportes/ventas/reportePreVentas.xhtml?nodeTree=Reporte Pre-Ventas&amp;codeTree=070113&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NTgwMTcyMCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNjcwOGQwNGQtMmRiNy00Yjk3LThlYWUtNzViNjJjYjJkNjZmIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.k1wdva0VEZqYRSPv74GOFOG3DMIV53kNK53Oo_g_32Y']</value>
      <webElementGuid>0e358bdc-beaa-4794-b0e8-aa9d5651ee13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
