<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Importacin General_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>e0572355-03da-4f6e-9ad6-3fa84ca326f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6e9e750f-7b3b-4c6b-a1b4-aa65ccae054e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>28b48015-b54b-433f-a487-b992e49f2751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>13f56281-042f-411e-85d5-13ea41a7e31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/envio/consultaEnvio.xhtml?nodeTree=Consulta Envio&amp;codeTree=0309&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NTgwMTcyMCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNjcwOGQwNGQtMmRiNy00Yjk3LThlYWUtNzViNjJjYjJkNjZmIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.k1wdva0VEZqYRSPv74GOFOG3DMIV53kNK53Oo_g_32Y</value>
      <webElementGuid>f05d3212-4607-4d03-acbb-2393ec4e238a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>bb1abf11-55e9-4328-b7aa-574a9e1a312d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>e16c3fbb-0da2-4b00-aa50-dd9f7cddf1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>dc5f15b4-ef58-4c89-b57d-c1d5d1d50743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c2495337-fd54-477a-a2fe-86bf6ee37740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/envio/consultaEnvio.xhtml?nodeTree=Consulta Envio&amp;codeTree=0309&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NTgwMTcyMCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNjcwOGQwNGQtMmRiNy00Yjk3LThlYWUtNzViNjJjYjJkNjZmIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.k1wdva0VEZqYRSPv74GOFOG3DMIV53kNK53Oo_g_32Y']</value>
      <webElementGuid>e2a12da9-5528-4590-89c1-9f0d84d76548</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
