<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Consulta Envio</name>
   <tag></tag>
   <elementGuidId>09915c48-e903-492a-9dc5-334e42006265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmPrincipal:tree:0_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b78dc2eb-e8b5-458d-825a-1ccba53bf712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_8</value>
      <webElementGuid>4d9acda0-7073-42b9-beba-a80d2d1d15d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowkey</name>
      <type>Main</type>
      <value>0_8</value>
      <webElementGuid>967f6038-d866-4ade-bffd-39fae8017287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nodetype</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5dbd0ce1-ba8f-4b07-b557-f51512b2e5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-treenode ui-treenode-leaf ui-treenode-unselected</value>
      <webElementGuid>500be0a1-cb52-44f5-bbd2-b48ae6257766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consulta Envio</value>
      <webElementGuid>1b88ec4e-b918-4289-8f24-4509a04fdc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_8&quot;)</value>
      <webElementGuid>34917fc2-4398-4c7b-9710-4d999f363d98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_8']</value>
      <webElementGuid>234798df-b55f-42e7-887e-b65b7ee4b106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0']/ul/li[9]</value>
      <webElementGuid>ee902f65-a865-4a1c-a331-3d715e23d4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guia Transportista'])[1]/following::li[1]</value>
      <webElementGuid>299580f0-21e7-4c82-ab02-a37aa7b7160d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guia de Despacho'])[1]/following::li[2]</value>
      <webElementGuid>0b645fab-abdf-4b58-8984-12327e556ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes Despachos'])[1]/preceding::li[1]</value>
      <webElementGuid>32c84624-28b1-4c3b-aedc-15e47fef98b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]</value>
      <webElementGuid>8b4681ff-76a0-48e7-8805-7fd4d9421105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmPrincipal:tree:0_8' and (text() = 'Consulta Envio' or . = 'Consulta Envio')]</value>
      <webElementGuid>bc3dd16d-fe5a-4c2d-937b-a505a51df2ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
