<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_El RUC debe tener 11 dgitos (1)</name>
   <tag></tag>
   <elementGuidId>107666f8-1cb4-4fb5-90fa-668a92ba5c13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(.,'El RUC debe tener 11 dígitos')])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c220f0cc-b469-4de1-8cfa-2129f61ec2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente_msg</value>
      <webElementGuid>a404e882-2ca2-4ebd-bfaf-8035b1390928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error col-md-offset-1</value>
      <webElementGuid>41bbd20b-f3d0-4dc9-9726-0813232cf74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El RUC debe tener 11 dígitos</value>
      <webElementGuid>f70863ad-fbf9-441e-88b3-9829e6bbba5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente_msg&quot;)</value>
      <webElementGuid>8220c28d-6c6c-4c87-bd05-5fc4c769f6bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_documento_cliente_msg']</value>
      <webElementGuid>e8d8ff2b-f772-462a-944b-8576cbe60222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/div</value>
      <webElementGuid>45895a7a-bd28-4c40-bf42-92f1ef2f95e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[2]/following::div[3]</value>
      <webElementGuid>b2813796-8237-4954-b51d-2c1190b71296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[3]/following::div[3]</value>
      <webElementGuid>0d829111-d91d-4146-ba06-0c93c2a02e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola,'])[1]/preceding::div[4]</value>
      <webElementGuid>6773de38-cd12-49dc-9a3c-7ce4c63c3282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona origen de tu envío'])[1]/preceding::div[10]</value>
      <webElementGuid>2bf3de57-a5cc-4bb4-9070-4f8a222f34c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='El RUC debe tener 11 dígitos']/parent::*</value>
      <webElementGuid>eefe185d-d52a-4175-ae8d-679aab124ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>cfdebb54-4918-400c-8d20-e0393b3f91de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_documento_cliente_msg' and (text() = 'El RUC debe tener 11 dígitos' or . = 'El RUC debe tener 11 dígitos')]</value>
      <webElementGuid>92409db5-6f32-4625-abb6-badfa3ff0501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
