<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cerrar_iframe_response</name>
   <tag></tag>
   <elementGuidId>51fe2dcc-9dbb-4a5c-8818-2b8c7a860ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframe_response</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe_response']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>58dcd8b7-9c9c-4a75-a9ea-c501c231d40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe_response</value>
      <webElementGuid>fdcfc39f-31b7-4958-8040-e9cd35d38a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>78010605-bca5-463c-8a56-924116bb8513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://girley.herokuapp.com/search?origin=https://registro.olvacourier.com/registrar_envios_cargo_adjunto/nuevo-envio</value>
      <webElementGuid>52a91064-30cd-47f4-aedc-db4e6f2871ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c3d8cb88-ff7b-4a0b-a62f-b0ba5c8936a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe_response&quot;)</value>
      <webElementGuid>98ffe5c6-8514-4c38-bf52-31269dbd66d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe_response']</value>
      <webElementGuid>f2653cf9-2624-4d21-9ba8-63a027b9d5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetDireccionEntrega']/div/div/div[2]/iframe</value>
      <webElementGuid>dca343e3-cacf-4a97-992f-a9bfe08df00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar'])[2]/following::iframe[1]</value>
      <webElementGuid>86bd1755-3e9c-4d49-9bd9-650851ad3f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[3]/following::iframe[1]</value>
      <webElementGuid>16faa602-a092-4e2c-8dfb-77b4e784bc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::iframe[1]</value>
      <webElementGuid>1b5c8d7a-558e-4f40-8c5d-2219f49abe31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando Dirección ...'])[1]/preceding::iframe[1]</value>
      <webElementGuid>39ef8190-74c2-47b1-86bf-d2750720451c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>51617468-bfb5-43b1-b6e5-66a164b2785b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe_response' and @src = 'https://girley.herokuapp.com/search?origin=https://registro.olvacourier.com/registrar_envios_cargo_adjunto/nuevo-envio']</value>
      <webElementGuid>7d8f70cd-c32a-424f-adb1-5bfb084ebdb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
