<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_direccion_domicilio - CA</name>
   <tag></tag>
   <elementGuidId>429109d3-f7da-41f7-b361-2c7122c2e48c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_direccion_entrega</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'txt_direccion_entregaCA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9d156e0-aa87-4fe8-a92f-f207e909d4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2887af1a-7e24-4bb2-835c-e8a90992da2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b30500f2-5cac-4a88-bfc4-b2307f1a0ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_direccion_entrega</value>
      <webElementGuid>b3e7e842-69a0-475f-b80f-8064f3fd30e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dirección de entrega</value>
      <webElementGuid>a2ce0239-485b-4169-99d6-b825adcd7412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado</value>
      <webElementGuid>03365003-7ab7-4e41-8680-2b2e16414be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>2ecd7331-b24c-41c1-a938-178a5063d319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_direccion_entrega</value>
      <webElementGuid>4f93adea-f9d5-451b-90ac-7f669c946e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>04a8e33f-75bc-42d9-b7ae-5853667b68d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_direccion_entrega&quot;)</value>
      <webElementGuid>b5e4fc1c-8a10-457e-90f6-5f9ca9d06059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_direccion_entrega']</value>
      <webElementGuid>ecebeef6-5c19-42c6-a201-84a68c45ebf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[6]/div/div[2]/input</value>
      <webElementGuid>51d9c119-b8dd-4d4f-a5af-a51f8a5ff301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/input</value>
      <webElementGuid>18462ba3-6d8b-434a-b419-f618b7f2867f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_direccion_entrega' and @placeholder = 'Dirección de entrega' and @id = 'txt_direccion_entrega' and @title = '.']</value>
      <webElementGuid>dfdea792-8d1c-4bef-94e0-40b9c76579a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
