<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UTILES DE OFICINA_txt_paquete_largo</name>
   <tag></tag>
   <elementGuidId>9435fedb-0d31-4316-a84e-d3a558749e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_paquete_largo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_paquete_largo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90499935-f5fe-457a-829b-182e83ff279f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ffe7d083-6e87-4bf2-8705-85de5b509e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63c7e643-a9ec-4334-801f-e4a2afe4a0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_paquete_largo</value>
      <webElementGuid>dabc32e3-e659-4bfc-962d-fe7b7aded269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_paquete_largo</value>
      <webElementGuid>0366b5a0-9a4d-4c46-bfbd-e2bac0b6d702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Largo</value>
      <webElementGuid>808e2f06-79f5-497e-91ed-bbb1e8dae015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name input-name place-color</value>
      <webElementGuid>c9c0b637-054f-4de1-acd5-93abe5b2721e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>0211aa6f-8a55-4d43-9fcc-99bd28206312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>349b45bc-1deb-4633-ae01-2988361c70e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_paquete_largo&quot;)</value>
      <webElementGuid>f80bacbf-8ae0-4286-a29e-81d17e2699ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_paquete_largo']</value>
      <webElementGuid>08cf6004-757e-492f-af30-620c8485462b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_paquete_largo']/div/input</value>
      <webElementGuid>45145555-82fc-4bc3-b914-29fbd15bcc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>e34a8112-c370-42c6-b20d-dc9b52638b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_paquete_largo' and @id = 'txt_paquete_largo' and @placeholder = 'Largo' and @title = '.']</value>
      <webElementGuid>3e59ba94-aaee-4b4f-a4df-924c44bcab5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
