<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cm_txt_paquete_peso</name>
   <tag></tag>
   <elementGuidId>09e8354c-9808-4ccc-ad0b-f23e2d1c2d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_paquete_peso</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_paquete_peso']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b66d2bc2-dc6e-49cd-ae1f-e9cc0513f649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b6803946-70e4-493f-a4df-4fab810bd8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2c37d70-7bf4-4578-abda-03201516a580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_paquete_peso</value>
      <webElementGuid>30c0cd67-a1de-4e90-83b1-dad94d98d4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Peso</value>
      <webElementGuid>6c104919-5f57-461a-959f-48bad1d131af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_paquete_peso</value>
      <webElementGuid>98f4177d-1ccf-479f-8eea-f5b14e72e113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name input-name place-color</value>
      <webElementGuid>974209f5-65be-4be2-aa94-e4b833c4b8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>c12fbde8-25c3-49ed-a0cc-0d65a1b0e54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_paquete_peso&quot;)</value>
      <webElementGuid>a9cf1a02-641a-4ab8-8529-9aa42e9a4750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_paquete_peso']</value>
      <webElementGuid>2b6406d0-e906-4116-b311-dab9645e542c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_paquete_peso']/div/input</value>
      <webElementGuid>71282d94-4658-4baa-9eb4-1311ce17f5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div/div/input</value>
      <webElementGuid>bb13e5e0-e9c2-4a90-87ff-1bd672b93a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_paquete_peso' and @placeholder = 'Peso' and @id = 'txt_paquete_peso' and @title = '.']</value>
      <webElementGuid>55c42c62-f265-4786-b27d-0f11f62da0a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
