<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneDNIRUCCARNET DE EXTRANJERIA</name>
   <tag></tag>
   <elementGuidId>87882732-61df-49f1-b929-54d962f5ad20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cbo_tipo_documento' and (text() = 'SeleccioneDNIRUCCARNET DE EXTRANJERIA' or . = 'SeleccioneDNIRUCCARNET DE EXTRANJERIA')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cbo_tipo_documento&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbo_tipo_documento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>abdf8b9d-e654-4831-ad31-482433d5fcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbo_tipo_documento</value>
      <webElementGuid>4a6fadb4-6b94-4daa-86aa-d5f79fed0675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd869884-7ddf-4788-bdc9-46f0d44ca487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneDNIRUCCARNET DE EXTRANJERIA</value>
      <webElementGuid>713f975b-2240-495b-b5a8-6f8cf51a99dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbo_tipo_documento&quot;)</value>
      <webElementGuid>c7677d6d-d940-406b-8759-527f46402925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbo_tipo_documento']</value>
      <webElementGuid>80e288c9-c32e-4443-bd16-277e3375f343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cambioColor']/select</value>
      <webElementGuid>ab960478-ba2c-4eb6-97cb-79e2628099bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Documento'])[1]/following::select[1]</value>
      <webElementGuid>cf389900-e201-49c1-9a3d-2363fb0c8836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JURIDICO'])[2]/following::select[1]</value>
      <webElementGuid>f3576325-481a-49d7-9362-b193535998a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Num. Doc.'])[1]/preceding::select[1]</value>
      <webElementGuid>189b113b-2170-4b59-b87a-586efbf71cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apellidos'])[1]/preceding::select[1]</value>
      <webElementGuid>19315049-69df-44ab-bea9-a369d126e8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/select</value>
      <webElementGuid>f8e6b354-efef-41eb-8254-799db03d08d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbo_tipo_documento' and (text() = 'SeleccioneDNIRUCCARNET DE EXTRANJERIA' or . = 'SeleccioneDNIRUCCARNET DE EXTRANJERIA')]</value>
      <webElementGuid>278e21e4-d9bf-4513-acf9-92629b74b906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
