<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_compras por internet_iconcard</name>
   <tag></tag>
   <elementGuidId>67b53835-a9a9-4849-8de5-2250e3758a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iconcard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='iconcard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8761c986-025b-4049-bac8-7b355f471956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconcard</value>
      <webElementGuid>05f58fb1-32d5-4b13-8d0d-8534c1d76523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-prepend fa card</value>
      <webElementGuid>63b2724e-202c-4059-840c-0ff7247cbec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconcard&quot;)</value>
      <webElementGuid>6a7b0558-1e58-47c3-a4ee-2cbe6f701758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Olva Courier  Medios de pago/iframe_Aceptar_visaNetJS_1</value>
      <webElementGuid>c74daee1-cb8a-498b-9800-dbd4beaab073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='iconcard']</value>
      <webElementGuid>291501ed-a632-41ae-8673-fc9a3d4ff696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='default']/div[3]/div/section/label/i</value>
      <webElementGuid>2f442ce8-bfa1-47b0-9c34-bf5ff076b733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>c374c8d9-2944-4c9f-8c6d-ce0d0c66607f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'iconcard']</value>
      <webElementGuid>d53f810a-1a92-4a58-a3b9-058468e0814e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
