<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tarjeta de crdito y dbito 2</name>
   <tag></tag>
   <elementGuidId>ba864f5f-2e3a-4a6a-bed0-695aad27a406</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pm001</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id = 'pm001' and (text() = 'Tarjeta de crédito y débito')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e4e38c1d-2977-4f1c-8b6a-66ad72e18e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pm001</value>
      <webElementGuid>067787a8-1e6d-46ec-b209-7871945c5c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tarjeta de crédito y débito</value>
      <webElementGuid>c27bcab2-ee9d-484b-a8e3-a6c932801f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pm001&quot;)</value>
      <webElementGuid>eed61905-436b-4605-bf51-442d5cefabc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Olva Courier  Medios de pago/iframe_Aceptar_visaNetJS</value>
      <webElementGuid>feff7f95-06b0-4c2f-b4d6-df308c25e6c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='pm001']</value>
      <webElementGuid>e2b1cdc1-9be4-46d6-88ae-ea8dcc408a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethods']/div/div/section/label/span</value>
      <webElementGuid>5e1b363a-e45f-4c36-9093-9e858c81c79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elige un medio de pago:'])[1]/following::span[1]</value>
      <webElementGuid>bdd157ac-0684-4a5c-b077-f270c5638db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva tarjeta'])[1]/following::span[1]</value>
      <webElementGuid>1e7fee5b-78b0-4a73-a605-43e89502e35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código QR usando tu billetera electrónica'])[1]/preceding::span[1]</value>
      <webElementGuid>b053ed92-30db-4392-8643-17804bf9fa8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tarjeta de crédito y débito']/parent::*</value>
      <webElementGuid>66c3ac2c-7217-42c7-aa8e-6346b76e14dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/label/span</value>
      <webElementGuid>e81987c2-06e0-4abb-86bb-76fb8cec2131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'pm001' and (text() = 'Tarjeta de crédito y débito' or . = 'Tarjeta de crédito y débito')]</value>
      <webElementGuid>3c5ec9fb-2420-475b-9d9d-32b2270af6dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
