<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ifram</name>
   <tag></tag>
   <elementGuidId>d7635a5f-8ae2-4516-a9f3-2aeef96e1d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0b569fb7-caaf-4469-a77b-d8d141689585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>50cfb2a4-cb72-4e26-9d68-d4011eda6670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>08e750c6-3243-4caf-a5b1-9539c43584de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3MDg5OTkxNiwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZDE0ZTRlNjktMGNkZC00ZWE5LWE5YzAtZTllMDIwZWY0YmY3IiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.3cBHUmxnceDYvgZ9ysZqsXF_wEXN0zdT8C2B-5Qq0aw</value>
      <webElementGuid>2f2c1c44-bfa4-44e9-9410-8cf93a58d0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>99fa8b91-5269-4ce2-b889-7cfc22a2f005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>d627db48-3ed4-4d0e-8ac5-180b68769abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>af905045-dbf9-4ccb-a71a-12fa588152b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8272fe22-147d-40be-a63e-2c09fac14cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3MDg5OTkxNiwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZDE0ZTRlNjktMGNkZC00ZWE5LWE5YzAtZTllMDIwZWY0YmY3IiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.3cBHUmxnceDYvgZ9ysZqsXF_wEXN0zdT8C2B-5Qq0aw']</value>
      <webElementGuid>f0062acf-5e6d-414d-b0f5-9a65ed365289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
