<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de documentoscon un peso mximo de__8aba39</name>
   <tag></tag>
   <elementGuidId>653c0ec5-0bb3-4367-bc4e-bf88c8a1d8f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;img_caja&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_caja</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce1db04f-c523-4ac3-94ac-8587f8c54c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_caja</value>
      <webElementGuid>2517c18a-5fc4-451f-8b9e-e9a1c6580dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png</value>
      <webElementGuid>da0418c2-844c-4047-b9e7-539091b4a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>db6e3e37-fbbc-4e36-9650-6dd01684a7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4091d704-aa0c-4685-9e9e-ed6de96d5e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>c253b5e2-c07d-43c0-8b13-657788310aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_caja&quot;)</value>
      <webElementGuid>7b2444f1-5f2b-4f9a-9de0-ac310d18bf05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_caja']</value>
      <webElementGuid>98922ea6-f982-44ff-8e09-901926ffc8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_caja']/img</value>
      <webElementGuid>0a56354d-2d47-47f2-9fca-8fa28cd86011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png')]</value>
      <webElementGuid>690d3809-3c5b-45c0-ac97-e11f5938799b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/div/figure/img</value>
      <webElementGuid>b7b933ad-1330-407f-b136-db0e3604e166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_caja' and @src = 'https://registro.olvacourier.com/registrar_envios_cajas/assets/img/compra_cajas.png']</value>
      <webElementGuid>1dbbb897-fa49-4040-8b05-05c3c49bf433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
