<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PROVINCIA</name>
   <tag></tag>
   <elementGuidId>cecc90e4-950f-454b-850b-911a6437c049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_provincia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_provincia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1a05cdf-d161-48cf-8b36-17ebed0c5fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-size</value>
      <webElementGuid>3f47b8cf-74c5-44c8-ac39-cb719bb3402c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_provincia</value>
      <webElementGuid>613703a6-c5da-432e-a16e-faff912d2eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROVINCIA</value>
      <webElementGuid>90ee370d-d1db-414e-b0b5-ca9d5ad3edc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_provincia&quot;)</value>
      <webElementGuid>6a1dae8a-9396-421c-a792-f4ad02386827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_provincia']</value>
      <webElementGuid>51cc50d4-7883-4298-9e8b-a5d8f8ff76a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_buttons']/button[2]</value>
      <webElementGuid>2c68aa0c-a696-4586-83b8-fd30f9f7c1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA'])[1]/following::button[1]</value>
      <webElementGuid>360f9be8-d91a-4e49-b714-d907d051fd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Dónde te encuentras?'])[1]/following::button[2]</value>
      <webElementGuid>d5c70ab0-7b9f-4e9e-8658-07b4e90f7a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[2]/preceding::button[1]</value>
      <webElementGuid>fec83ef5-d67d-47c5-9c4f-624a5b0ef320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[3]/preceding::button[2]</value>
      <webElementGuid>21650657-9c2a-41c1-935d-61c3aea9e7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b1bec3e2-c0df-4afc-a4b8-312e2f0d75b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_provincia' and (text() = 'PROVINCIA' or . = 'PROVINCIA')]</value>
      <webElementGuid>cc1aedb1-6f20-44cf-9031-bc19ac150937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
