<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe seleccionar un tipo de documento</name>
   <tag></tag>
   <elementGuidId>257adcf2-7ce7-41a5-ae30-c5d20603b5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbo_iddocumento_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbo_iddocumento_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7591a0af-1985-4db6-90ab-050124e14a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbo_iddocumento_msg</value>
      <webElementGuid>28a5c4d1-14e6-49e9-9f46-e63632fc3b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>aa46186e-dac8-4b2a-b02e-5bf8549ec8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe seleccionar un tipo de documento</value>
      <webElementGuid>7f35d422-994c-4f92-bb9a-1580136586ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbo_iddocumento_msg&quot;)</value>
      <webElementGuid>a33ead08-0d13-4be0-a292-9ba3089c1160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cbo_iddocumento_msg']</value>
      <webElementGuid>4fa76546-4f5f-4844-a1df-65ccad8ccb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_documento']/div[2]</value>
      <webElementGuid>f95ba60c-7302-4f5a-ace3-56a723c89233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[2]/following::div[1]</value>
      <webElementGuid>423bc376-b4bf-4a3f-8152-ea5d5cd2e036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[2]/following::div[1]</value>
      <webElementGuid>c500d987-1243-4185-a720-aa6bdd380073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe Ingresar un Número Documento'])[1]/preceding::div[2]</value>
      <webElementGuid>b7c7a58f-8976-41eb-9c0d-b76472e386ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese 9 digitos'])[1]/preceding::div[4]</value>
      <webElementGuid>3ede3b74-207a-47d7-89b6-fbe1e3464166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>88f32ac7-6eb3-4c45-ab03-c8d9e55ff3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cbo_iddocumento_msg' and (text() = 'Debe seleccionar un tipo de documento' or . = 'Debe seleccionar un tipo de documento')]</value>
      <webElementGuid>6d7a3d75-0194-49c9-a9ba-1d495325c315</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
