<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe seleccionar un distrito destino pa_39940b</name>
   <tag></tag>
   <elementGuidId>1b99a568-4e8b-4def-8a6d-03f09c317a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_descripcion_ubigeo_caja_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_descripcion_ubigeo_caja_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01920aaa-685d-491c-b2e2-3c7ee98448b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_descripcion_ubigeo_caja_msg</value>
      <webElementGuid>322a6cd4-a1e5-42b5-b333-d3b7949dfbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>09d003d2-e0ef-434c-b553-f337f6562b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe seleccionar un distrito destino para continuar</value>
      <webElementGuid>727a12e1-55ab-4059-89af-f0a53d784705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_descripcion_ubigeo_caja_msg&quot;)</value>
      <webElementGuid>94308645-d306-4090-9326-ef4515c2ac14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_descripcion_ubigeo_caja_msg']</value>
      <webElementGuid>5b373915-48b2-4aa1-967e-9d04d9fa0261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-ubigeo']/div[2]</value>
      <webElementGuid>25f9f6f4-3136-4fb5-a0f8-d31c4e877097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PURUS - PURUS'])[4]/following::div[1]</value>
      <webElementGuid>75991bc7-c968-43cd-8be0-f94de572d239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PADRE ABAD - NESHUYA'])[2]/following::div[1]</value>
      <webElementGuid>f980fc10-621b-40ec-ba82-440c8bb9a5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La direccion debe ser mayor a 3 caracteres'])[1]/preceding::div[3]</value>
      <webElementGuid>37b595c7-f6c2-4c53-8d2c-ee6bb5d39e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La referencia debe ser mayor a 3 caracteres'])[1]/preceding::div[8]</value>
      <webElementGuid>52ae49be-8844-4abc-b59b-6b63b1c5af8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe seleccionar un distrito destino para continuar']/parent::*</value>
      <webElementGuid>b0867313-99f3-4357-b9a4-9e886fe09d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div[2]</value>
      <webElementGuid>db8a3682-8be0-4fd1-a539-c9d5eca19c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_descripcion_ubigeo_caja_msg' and (text() = 'Debe seleccionar un distrito destino para continuar' or . = 'Debe seleccionar un distrito destino para continuar')]</value>
      <webElementGuid>1b894073-7ad8-4c2e-a226-e622f190b843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
