<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe Selecionar Provincia</name>
   <tag></tag>
   <elementGuidId>c5f6e964-1682-47e6-8a4e-31d2288a433e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbo_tienda_prov_caja_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbo_tienda_prov_caja_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39208945-f0a7-497b-9e4d-0ee0f9454509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbo_tienda_prov_caja_msg</value>
      <webElementGuid>c5d960ce-87b7-4306-a723-95b79c3403b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>a4b7ec12-81dd-4b28-a5da-504612960ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe Selecionar Provincia</value>
      <webElementGuid>f83c1d68-4da7-480c-9773-5e0d94d672ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbo_tienda_prov_caja_msg&quot;)</value>
      <webElementGuid>4bcfe696-c58c-431f-a3c6-8bffe088e23c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cbo_tienda_prov_caja_msg']</value>
      <webElementGuid>c935939e-1414-4083-80a8-53c033e5984a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[2]/div[3]/div[2]</value>
      <webElementGuid>d4395c6c-8aa7-4505-a21b-95815b2259e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - ATALAYA - ATALAYA'])[2]/following::div[1]</value>
      <webElementGuid>3bb117e4-e6ee-448b-a5c0-a2c1fb2243c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PURUS - PURUS'])[2]/following::div[1]</value>
      <webElementGuid>ce55e702-46b9-4752-a1b1-363519ed8ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[2]/preceding::div[1]</value>
      <webElementGuid>ef22eb54-41ef-4bc4-92f8-1a98e587fdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[3]/preceding::div[2]</value>
      <webElementGuid>bed4d8fb-4334-45a0-a295-bcb02ad3f0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe Selecionar Provincia']/parent::*</value>
      <webElementGuid>51636015-f846-4ae5-9be4-fc3acacda1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]</value>
      <webElementGuid>80da2922-d7ee-44f8-aea5-b13892f37a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cbo_tienda_prov_caja_msg' and (text() = 'Debe Selecionar Provincia' or . = 'Debe Selecionar Provincia')]</value>
      <webElementGuid>b00345ef-801e-492c-978c-ca2e2e6c9f6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
