<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe Seleccionar Tienda</name>
   <tag></tag>
   <elementGuidId>17cfd06a-b018-423a-be72-e9e8684be682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbo_tienda_caja_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbo_tienda_caja_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9d5d680-2b15-476c-b5d2-53844c097a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbo_tienda_caja_msg</value>
      <webElementGuid>540e2f33-903c-455d-b9ad-9f489ab229ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>f53ceb4a-e5b1-4fcc-9089-0155c71fb03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe Seleccionar Tienda</value>
      <webElementGuid>b933151c-6be4-47ed-9307-2875b633f071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbo_tienda_caja_msg&quot;)</value>
      <webElementGuid>18243421-7b20-4600-9d17-c71de18accd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cbo_tienda_caja_msg']</value>
      <webElementGuid>febb1279-efa9-42a8-9248-88123960e31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[4]/div/div[2]/div/div[2]</value>
      <webElementGuid>4e3c5f5d-b420-49f0-958f-f730132a9d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[3]/following::div[1]</value>
      <webElementGuid>7f90a0f1-6f99-433e-bebd-b855b70ba956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[2]/following::div[3]</value>
      <webElementGuid>87a1ca01-ebf2-4dae-bd3f-d483b4c06cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe escribir 4 números'])[1]/preceding::div[1]</value>
      <webElementGuid>86688f4d-342d-428e-a284-9d8a796bd8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::div[7]</value>
      <webElementGuid>b20d3788-1d31-4315-9015-61f989910f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe Seleccionar Tienda']/parent::*</value>
      <webElementGuid>58da1cd0-f14b-4f79-ac86-ea8738815f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[2]</value>
      <webElementGuid>1f0b4711-e7d9-4a63-9b90-9d660e19f04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cbo_tienda_caja_msg' and (text() = 'Debe Seleccionar Tienda' or . = 'Debe Seleccionar Tienda')]</value>
      <webElementGuid>be84009f-0b90-451d-b7ba-d2962f8fae75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
