<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_El DNI debe tener 8 dgitos</name>
   <tag></tag>
   <elementGuidId>845fb5df-85c8-465c-9cbd-eec12120db06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_documento_cliente_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d53f9411-410b-458e-8c21-4bb661cf729d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente_msg</value>
      <webElementGuid>31cfa5d7-185f-45e2-b15f-32c3c651ff4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error col-md-offset-1</value>
      <webElementGuid>dbf5e66d-5970-426f-bf8e-6d101ae3fdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El DNI debe tener 8 dígitos</value>
      <webElementGuid>03242e3b-08c7-4a1a-b78b-0df1308c11ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente_msg&quot;)</value>
      <webElementGuid>cd284e12-11e6-44ba-9755-1d597e5266a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_documento_cliente_msg']</value>
      <webElementGuid>ee4bbceb-77f3-41c6-b3b9-bb1badf47d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/div</value>
      <webElementGuid>30963d79-c144-4a7c-94e0-2d4a525b0148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[2]/following::div[3]</value>
      <webElementGuid>e2ede49d-19e4-447a-a8fd-e2530f9e9193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[2]/following::div[3]</value>
      <webElementGuid>1f5301a6-d869-4cf3-8a36-3f03c8911218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola,'])[1]/preceding::div[4]</value>
      <webElementGuid>e53125a9-2371-4433-89ef-685129ba5da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Dónde te encuentras?'])[1]/preceding::div[10]</value>
      <webElementGuid>988af8fe-2dda-4c02-9d08-15dc0a13d65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='El DNI debe tener 8 dígitos']/parent::*</value>
      <webElementGuid>a23f9852-4a6d-4ec2-8ded-23e545b7fa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]/div</value>
      <webElementGuid>8604faae-8b1c-4f52-9b81-45378af70053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_documento_cliente_msg' and (text() = 'El DNI debe tener 8 dígitos' or . = 'El DNI debe tener 8 dígitos')]</value>
      <webElementGuid>e93ceb0e-fd58-4e1d-91e3-860b42204539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
