<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_La referencia debe ser mayor a 3 caracteres</name>
   <tag></tag>
   <elementGuidId>7e369d76-31ab-4aac-b34a-44fa3037cb15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_direccion_entrega_ref_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_direccion_entrega_ref_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a42ab2b-7b73-46da-811f-d7f7ca8cfa27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_direccion_entrega_ref_msg</value>
      <webElementGuid>a5e652b7-c7bb-41f7-b87d-0cd561e16207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error col-md-offset-1</value>
      <webElementGuid>0c13c0e4-1554-4d4a-abde-7bce2ced0a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>La referencia debe ser mayor a 3 caracteres</value>
      <webElementGuid>7515364e-6b97-47ca-b2f6-db9afe7d5fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_direccion_entrega_ref_msg&quot;)</value>
      <webElementGuid>5158fb83-c2f0-4e2f-950c-319976e7a153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_direccion_entrega_ref_msg']</value>
      <webElementGuid>7729830b-0ac6-43b8-9c68-89880ea37a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[3]/div[2]/div[2]/div</value>
      <webElementGuid>07c928f6-ff64-4fe0-9868-6d2c247aed92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La direccion debe ser mayor a 3 caracteres'])[1]/following::div[5]</value>
      <webElementGuid>f2647a02-9bae-4b56-b25e-6a335e843c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe seleccionar un distrito destino para continuar'])[1]/following::div[11]</value>
      <webElementGuid>bf2459cd-97c5-49f8-af97-7a6003438904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[2]/preceding::div[3]</value>
      <webElementGuid>152df289-fefb-4f17-b185-9f5099f83b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[3]/preceding::div[4]</value>
      <webElementGuid>d46853c7-1a5b-48bf-b78b-5ce8d189338b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='La referencia debe ser mayor a 3 caracteres']/parent::*</value>
      <webElementGuid>1cdfa749-0c4f-4799-98d1-583e082f878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div</value>
      <webElementGuid>7ad6d010-f5d6-4c9d-a160-c78bf23fb7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_direccion_entrega_ref_msg' and (text() = 'La referencia debe ser mayor a 3 caracteres' or . = 'La referencia debe ser mayor a 3 caracteres')]</value>
      <webElementGuid>e53ddc8c-6fe8-476e-98b9-7cdc21ae0a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
