<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpswww.olvacourier.comcalculadora-de-envios</name>
   <tag></tag>
   <elementGuidId>91202877-69b3-4902-bd21-4a645ddae8e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myModal']/div/div/div[2]/p[14]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2acea196-13f3-438f-a8cc-b7245ea9c6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.olvacourier.com/calculadora-de-envios/</value>
      <webElementGuid>0145b200-0f0a-423e-9508-7ebca6574612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.olvacourier.com/calculadora-de-envios/</value>
      <webElementGuid>17105b89-6655-4de8-88b7-af1fe8a10dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/p[14]/a[1]</value>
      <webElementGuid>3ac7657e-ff25-4841-8966-b142118bd569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/div/div[2]/p[14]/a</value>
      <webElementGuid>ad0f6e61-10b7-4c24-b228-8e1818de5e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://www.olvacourier.com/calculadora-de-envios/')]</value>
      <webElementGuid>4a273084-e8d5-48b4-8ac3-303ab155c6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.olvacourier.com'])[1]/following::a[1]</value>
      <webElementGuid>ebaadc13-0f90-450c-ab59-056eb147cd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.olvacourier.com/protocolo-tiendas/'])[1]/following::a[2]</value>
      <webElementGuid>2a759882-232f-4de8-ba9e-fde5aea37f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Devoluciones de envíos'])[1]/preceding::a[1]</value>
      <webElementGuid>735e114b-11ae-4756-824b-022a3004f892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Embalaje de envíos'])[1]/preceding::a[1]</value>
      <webElementGuid>fd224a0e-300c-4372-a036-185ab91ab1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.olvacourier.com/calculadora-de-envios/']/parent::*</value>
      <webElementGuid>cd656b48-4b43-4e70-a18c-64437fc8307e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.olvacourier.com/calculadora-de-envios/')]</value>
      <webElementGuid>eea829f0-d05b-4cb5-b6f2-9aebb692f7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[14]/a</value>
      <webElementGuid>1ad19ea5-29ec-48af-8e2a-b8627238d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.olvacourier.com/calculadora-de-envios/' and (text() = 'https://www.olvacourier.com/calculadora-de-envios/' or . = 'https://www.olvacourier.com/calculadora-de-envios/')]</value>
      <webElementGuid>e83e04c2-f5e1-4143-b160-99280089a9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
