<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsbit.ly3121hxy</name>
   <tag></tag>
   <elementGuidId>91606033-27fe-4748-9a2c-5d54cb3e62f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myModal']/div/div/div[2]/p[10]/b[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64ed17c0-3a9c-4034-a98e-6c535f105f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.olvacourier.com/wp-content/uploads/2020/10/HORARIO-TIENDAS.pdf</value>
      <webElementGuid>34f8e161-db01-4e6a-9ed9-6cb3edb67cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://bit.ly/3121hxy</value>
      <webElementGuid>f3f25281-2976-475f-ad00-ff55e0dfbdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/p[10]/b[2]/a[1]</value>
      <webElementGuid>49b71c3e-7c1b-42e9-8ade-6f6255decfc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/div/div[2]/p[10]/b[2]/a</value>
      <webElementGuid>c51d49f1-32fa-429f-b529-1daf24770583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://bit.ly/3121hxy')]</value>
      <webElementGuid>dff24b65-dc63-4203-8d0a-2fe4bc709a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://bit.ly/TiemposDeEntrega'])[1]/following::a[1]</value>
      <webElementGuid>70384de2-0ab3-44f1-8fe5-104402e16283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Políticas de entrega'])[1]/following::a[2]</value>
      <webElementGuid>4f3259f8-24bd-4a8a-b57c-cfa3f6383a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.olvacourier.com/protocolo-tiendas/'])[1]/preceding::a[1]</value>
      <webElementGuid>edc74c14-e8a7-42cc-8cde-fb90f0a276f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.olvacourier.com'])[1]/preceding::a[2]</value>
      <webElementGuid>68fd93a0-17fd-4399-810c-45bc8d6755b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://bit.ly/3121hxy']/parent::*</value>
      <webElementGuid>d0ee7b54-5953-4787-828b-74bace2ffebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.olvacourier.com/wp-content/uploads/2020/10/HORARIO-TIENDAS.pdf')]</value>
      <webElementGuid>68c4a626-50c2-46ac-b227-2e07be12b3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/b[2]/a</value>
      <webElementGuid>0a5ca18e-c1b9-408e-9dae-a5c66235c1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.olvacourier.com/wp-content/uploads/2020/10/HORARIO-TIENDAS.pdf' and (text() = 'https://bit.ly/3121hxy' or . = 'https://bit.ly/3121hxy')]</value>
      <webElementGuid>96ee76e6-c7a7-4a13-9296-bdfc8dd7f24c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
