<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_COD.POSTAL</name>
   <tag></tag>
   <elementGuidId>ece1a66b-55f9-4a49-ad00-222abe37f1a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'frmUbigeoDestino:fltCodPostal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6591c9ed-e673-4c9d-bfa0-c6fd0d1994b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmUbigeoDestino:fltDestino</value>
      <webElementGuid>8310bda9-029b-4ff3-94e6-eef9f83e2372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmUbigeoDestino:fltDestino</value>
      <webElementGuid>c5acc4a9-8dc1-49f5-b7d7-dee429d05708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>274b67aa-5b23-4112-91fa-4e398117fc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aaeb8d03-0d2c-4ba9-bd41-7587ebc51437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DESTINO</value>
      <webElementGuid>e5860cb4-2531-4070-bfcf-cc797880ed37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>ab7e6094-fe92-41e1-96bb-61a38642a684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                                              btnFltDestinoUbg();                                              return false;                                          } else {                                              javascript:recorrer(event, 'tabDivDst', 'ubigeoWdg', '#frmUbigeoDestino\\:ubigeoTbl');                                          }</value>
      <webElementGuid>a9b9e07e-8cc8-43b1-b125-50f99acaa329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>3f5f5ad7-d2c3-4ff5-a54e-d6310239130a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1dfd92f2-afef-43e4-b8de-a1e1c473c93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30c3cdee-48f0-407e-b70c-921bf38e2749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f0adb955-a158-4cbe-ab08-e63effeee472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmUbigeoDestino:fltDestino&quot;)</value>
      <webElementGuid>2e1bf56f-fe24-439e-bed4-5c56ad54dc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/despacho/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>b0806597-86f4-45e2-ac06-49eeaec06d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmUbigeoDestino:fltDestino']</value>
      <webElementGuid>c04e18b2-9e7b-4f71-8f42-643ddd6e6294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmUbigeoDestino:pnlUbigeo_content']/input</value>
      <webElementGuid>2f18e893-9dba-498a-abbb-b7d9091344f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/form/div/div/input</value>
      <webElementGuid>be9c9d66-dadb-4b05-a8ae-06189d30aa7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmUbigeoDestino:fltDestino' and @name = 'frmUbigeoDestino:fltDestino' and @type = 'text' and @placeholder = 'DESTINO']</value>
      <webElementGuid>fcdf1b15-48cc-4d93-8895-362ba8f10323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
