<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ARTICULO_frmNewEnvioarticulo - Digitacion</name>
   <tag></tag>
   <elementGuidId>421aa3fd-6b45-479f-85e3-cf4b58293a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[contains(@class,'ui-button-icon-left ui-icon ui-c ui-icon-search')])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>714d39a2-6dde-465c-8bf1-8094bb40cf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmNewEnvio:articulo</value>
      <webElementGuid>23fb5f9b-9198-4dbc-bd4d-c31b7ff21cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmNewEnvio:articulo</value>
      <webElementGuid>e0885702-13c8-4f53-924a-824509ab20d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02694c37-2771-4d4e-aa0c-fc41f191492c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DOCUMENTOS</value>
      <webElementGuid>148552cf-f535-4356-b001-31f5e70163ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>673d0d90-39b6-4136-920d-5a761cfca9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9ea52638-92ad-47c9-ac87-eddf5bc42a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>17627aa8-ee39-4ca6-9822-931d03f60957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>envio.articuloComplete</value>
      <webElementGuid>fc9db3cd-41b4-44e1-81da-52579e25cd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                                                                  focusChange('#frmNewEnvio\\:contenedor');                                                                  if (jQuery('#frmNewEnvio\\:articulo').val().length >= 4) {                                                                      return false;                                                                  } else {                                                                      btnSearchArt();                                                                  }                                                              }</value>
      <webElementGuid>59bcdf2b-a362-4d6d-ad23-4b5367f24b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ng-pristine ng-untouched ng-invalid ng-invalid-maxlength ui-state-hover ui-state-focus</value>
      <webElementGuid>93f0e431-ebb3-41f8-a99f-4a0bd514cdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>932f0824-63d4-4a56-8b87-4c1753952453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>826753ae-6a4d-44c2-a7c7-9dffbf989393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1772cece-c8a7-4249-99be-9c4aff532a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewEnvio:articulo&quot;)</value>
      <webElementGuid>8e285528-6fdf-43b6-98eb-0915f6840e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>dac75fce-cc98-44ef-8e40-a684a172ce00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/despacho/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>15b11a28-4d53-4423-9a15-864509e53223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmNewEnvio:articulo']</value>
      <webElementGuid>dfd32df5-7e9e-41ec-8f9e-8ffdfe1a9284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmNewEnvio:pnlArticulo']/tbody/tr/td[4]/input</value>
      <webElementGuid>30e1b731-5d26-40ab-910d-e76f6473563e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/form/div/div/table[4]/tbody/tr/td[4]/input</value>
      <webElementGuid>48c521b8-59a8-45f6-ad6e-fd6b4db221aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmNewEnvio:articulo' and @name = 'frmNewEnvio:articulo' and @type = 'text']</value>
      <webElementGuid>cec2238c-1c0e-43f4-99db-96fbbd9645ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
