<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nro PiezasArticuloCont. Art.P. RealP. V_8591d6</name>
   <tag></tag>
   <elementGuidId>b75c148e-db99-4e04-8163-347b8f05958b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmNewEnvio:articuloTbl']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4bcba313-40e4-4637-b1d0-2514eb9de410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datatable-scrollable-body</value>
      <webElementGuid>445a9357-8e82-4051-a2c1-f73b22b69203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>46213fbd-4cb9-43f0-88d7-e2b251673a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nro PiezasArticuloCont. Art.P. RealP. VolumenDim. (AL - AN - LA)P. Consignado#Nro PiezasArticuloCont. Art.P. RealP. VolumenDim. (AL - AN - LA)P. Consignado#No records found.</value>
      <webElementGuid>9c195666-a4c0-4b60-920f-b01e7eac5c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewEnvio:articuloTbl&quot;)/div[@class=&quot;ui-datatable-scrollable-body&quot;]</value>
      <webElementGuid>dc91cee8-ac12-4a22-93a9-1ef63e935a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>899e16a1-b215-4ecb-86bc-e6e7b1b7e66d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmNewEnvio:articuloTbl']/div[2]</value>
      <webElementGuid>fdc0205a-8868-4f8c-be23-c5f4fd954971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[6]/following::div[1]</value>
      <webElementGuid>4a96b0d8-741d-4b0d-a352-12c1c8b3eb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P. Consignado'])[1]/following::div[1]</value>
      <webElementGuid>75c96223-c50d-48ce-908f-0c8e60e7d874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/div/div[2]</value>
      <webElementGuid>b44652c2-09b7-464f-96c6-6927ae4285c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nro PiezasArticuloCont. Art.P. RealP. VolumenDim. (AL - AN - LA)P. Consignado#Nro PiezasArticuloCont. Art.P. RealP. VolumenDim. (AL - AN - LA)P. Consignado#No records found.' or . = 'Nro PiezasArticuloCont. Art.P. RealP. VolumenDim. (AL - AN - LA)P. Consignado#Nro PiezasArticuloCont. Art.P. RealP. VolumenDim. (AL - AN - LA)P. Consignado#No records found.')]</value>
      <webElementGuid>fcb59383-ea5e-42ce-bc03-ed3e7d43e2fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
