<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte Destajo por Operador_iframePrincipal1</name>
   <tag></tag>
   <elementGuidId>f45dba9e-57db-4304-814a-0711e9005919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b15702ca-50a3-431f-a41a-bd2494077578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>0ed1c045-978a-45d6-a246-0cd6cdb7d236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>eed30164-f4a5-468e-ab57-7d14a071cf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/distribucion/liquidacion/frmLiquidacion.xhtml?nodeTree=Liquidación&amp;codeTree=040602&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc</value>
      <webElementGuid>de2f18c6-84de-493e-9e55-cc3955550707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>963e0de6-3ce4-4159-b5a1-96e74242e696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>6f0a7540-62e4-4e1a-997e-7926c0164e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>4997ec5b-b11d-42d1-9289-785fbe5ee584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c30b31e6-9b72-49a8-b6eb-c21b7a639c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/distribucion/liquidacion/frmLiquidacion.xhtml?nodeTree=Liquidación&amp;codeTree=040602&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc']</value>
      <webElementGuid>ea8731e8-3dd8-41cc-8c23-4f5a5c343166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
