<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal (2)</name>
   <tag></tag>
   <elementGuidId>bcf89ec3-2afd-462e-bab1-a371186591a5</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ba38de00-227a-4d5d-b3b6-a0d67c69a5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>956436a2-ede4-4b2c-9dcd-50b3330e3eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>6155eeaf-1062-49ec-88bb-a6d6d7ba08bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NjI3NTc3OCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNjY1MjA3YjctODVjNS00NTI4LTg0ZDQtZWMxZTFlNWVkYjNlIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.zPiMG8n0jmN5QdqEwGJv4IYnfTDQd-ed14jEfjKU3Hc</value>
      <webElementGuid>bc981dbf-3f5e-406d-886b-974fae093ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>0d99a040-b109-4f5a-bddd-b3ce2571c894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>70487ba4-7834-4509-89c3-70c23ed62fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>c1599c0b-3874-4892-8060-d46ccfff6998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>91f32ed3-103a-485f-a9df-7cf39f24a6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2NjI3NTc3OCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiNjY1MjA3YjctODVjNS00NTI4LTg0ZDQtZWMxZTFlNWVkYjNlIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.zPiMG8n0jmN5QdqEwGJv4IYnfTDQd-ed14jEfjKU3Hc']</value>
      <webElementGuid>5b4d66cb-fa5c-4487-869e-e2f9281680fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
