<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte Destajo por Operador_iframeP_aa3353 (2)</name>
   <tag></tag>
   <elementGuidId>2cfecdf8-7461-41df-8742-4edfdfa897aa</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>27a522cc-cdad-492a-afdb-b21975f74280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>ce65bb0d-e296-4200-ae41-38964774ade6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>cee4776f-6add-4f8a-b203-1fecb180b70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/distribucion/liquidacion/frmLiquidacion.xhtml?nodeTree=Liquidación&amp;codeTree=040602&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc</value>
      <webElementGuid>13b846e2-a203-4ca1-9bd6-efe9d8d6799b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>76d5a355-1f3c-4704-9a00-eaf908af4c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>a70e7dd9-2fe7-4147-8a75-a51772383e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>38d10810-edcc-4dea-8ea2-494a7cd5a3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4cbc1b83-f363-4b4e-84af-236362a88aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/distribucion/liquidacion/frmLiquidacion.xhtml?nodeTree=Liquidación&amp;codeTree=040602&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc']</value>
      <webElementGuid>ca737244-6dc2-4e39-a083-e583ba86d061</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
