<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte Destajo por Operador_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>b3cf4a86-5ee6-4402-a160-77a675974557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8d78fc1c-bf0d-4311-bafa-05d28d38a0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>101266e6-2e30-4820-ba7d-5cf36c677915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>da79ebc1-ad74-43bf-a0cd-9059ac38d3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/distribucion/liquidacion/frmLiquidacion.xhtml?nodeTree=Liquidación&amp;codeTree=040602&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc</value>
      <webElementGuid>6b007abf-cc44-4a8f-b063-d3ca9017affd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>6961b265-dbb0-49a6-ab93-59c3f0b50fcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>60e73749-d6fc-4ae5-97b1-bd69e1104d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>b12603bd-628f-4ebf-bfc6-c6b23ecaa9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6a209d8f-c93e-4e77-9bb5-13ada27439a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/distribucion/liquidacion/frmLiquidacion.xhtml?nodeTree=Liquidación&amp;codeTree=040602&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc']</value>
      <webElementGuid>41f9e8d0-e4c0-46c3-a4d8-566ba04f336f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
