<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal (1)</name>
   <tag></tag>
   <elementGuidId>432ec119-ac34-4194-aff8-e65786a04250</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f1aa22c0-8ec2-4591-97ae-d3b9cbd5e18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>7fc9b844-3275-4ef6-a7ff-bcb344203724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>9ab59349-12a7-422a-8a94-b5f9cadd0288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc</value>
      <webElementGuid>71315d48-3eea-4c6d-9125-6b5145c91c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>5f4b139b-258a-4f21-8a4d-24980065cbc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>cc175470-7d68-4eee-9333-135163bbd41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>9abeb76e-4bc4-4530-8071-4318e41dc6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3ed4a9e3-9bab-4b71-8621-fcd150378107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente/nuevo.xhtml?nodeTree=Venta&amp;codeTree=070104&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY2MDI2Nzg3MCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiN2FmYTBkZmMtNGM5Mi00ZWFmLTlkNGUtNDdhMTIwNmIzOTEwIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.YXQYH9rN5CepETNKOmMAY4OD-qlIkzQSn8WyW9Cmjvc']</value>
      <webElementGuid>9943f540-2d02-4b68-9ad2-e4d1a9bf792c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
