<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CODIGO DE BARRAS_frmAsignaciontxtCodi_2f39f3</name>
   <tag></tag>
   <elementGuidId>5a0401a7-81e7-4b65-8c03-a2d46b4e1f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'frmLiquidacionEnvio:codigoBarras')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea5dfa0e-0d94-4031-8289-a6f191b4e0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAsignacion:txtCodigoBarras</value>
      <webElementGuid>70943e6b-8972-44a8-bc95-cc37b67ff31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmAsignacion:txtCodigoBarras</value>
      <webElementGuid>09f89496-ea59-494c-bdf2-b1d34d890c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>696070c7-9503-4d5f-9dfe-ac147ba9d40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6645624d-fbec-4b85-979c-f890cee62acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>d63a4ff9-0d6d-4718-9e28-d1527e50ef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                                                                  if (this.value === '') {                                                                      PF('growlFrmAsignacionMsg').renderMessage({'summary': '', 'detail': 'INGRESE VALOR.', 'severity': 'warn'});                                                                  } else {                                                                      if (!isRemitoAsignado(this.value)) {                                                                          sendCodBarras(this.value, '1');                                                                      } else {                                                                          if(checkAsignarAuto){                                                                             sendCodBarras(this.value, '1');                                                                          }else{                                                                             PF('growlFrmAsignacionMsg').renderMessage({'summary': '', 'detail': 'EL ENVIO YA FUE ASIGNADO.', 'severity': 'warn'});                                                                          }                                                                      }                                                                      $('#frmAsignacion\\:ihnValueCodigoBarras').val(this.value);                                                                      this.value = '';                                                                      console.log('remito oculto: '+$('#frmAsignacion\\:ihnValueCodigoBarras').val());                                                                  }                                                                  return false;                                                              }</value>
      <webElementGuid>f5a188f2-48f1-43a9-95af-3ca369288af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all codigoDeBarras ui-state-focus ui-state-hover</value>
      <webElementGuid>cd65e8b9-9320-4fdd-8b71-74d6e0cc1989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fe2fe8b4-69f0-4aaa-bee9-e75a343b66a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca0d75a9-89f7-46f3-8489-b0e17290e4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b11a9c4-0e10-46f1-b230-db9bac49b716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAsignacion:txtCodigoBarras&quot;)</value>
      <webElementGuid>54c8552e-e668-4aca-be2f-3e255b5913d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte Destajo por Operador_iframeP_aa3353</value>
      <webElementGuid>67549910-037b-430d-a181-6b63132bd18d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmAsignacion:txtCodigoBarras']</value>
      <webElementGuid>a1ed99d6-7a77-4963-a7a6-2d3349ae9b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmAsignacion:j_idt14']/tbody/tr/td/table/tbody/tr[3]/th[2]/input</value>
      <webElementGuid>e782c778-83e8-4d67-8bd0-89074745b118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th[2]/input</value>
      <webElementGuid>d0dc627a-c28e-42d6-aa70-bfa515b0ffa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmAsignacion:txtCodigoBarras' and @name = 'frmAsignacion:txtCodigoBarras' and @type = 'text']</value>
      <webElementGuid>1bad3a28-4f26-41f9-808d-8347edeaa2aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
