<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Seleccionar_cliente</name>
   <tag></tag>
   <elementGuidId>e5bf3c16-5229-4004-881b-711aea71c7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Seleccionar' or . = 'Seleccionar') and @ref_element = 'Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='ui-button-text ui-c'][contains(.,'Seleccionar')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2023a728-e234-433f-ad42-6d46ac16cf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>99d11f24-6c4a-40a3-b154-b0e2eb9536b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccionar</value>
      <webElementGuid>7bb16347-09b6-45c0-a8f7-5b38e01e3a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPCSearch:tblPCSearch:btnSelectCliente&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>0b64b1f4-b67b-4382-8c8d-2a677d1b36f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>e0de4045-4ba1-453f-83e6-4dbcf642e19c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmPCSearch:tblPCSearch:btnSelectCliente']/span[2]</value>
      <webElementGuid>fdfe93b0-4233-44ed-835e-79c2b02fa53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[5]/following::span[2]</value>
      <webElementGuid>54ebd91d-bbfa-4b98-a9cb-f200459ba29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DNI'])[28]/following::span[2]</value>
      <webElementGuid>4ea91a12-0318-4ac1-82bc-2f63838ad7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[3]/preceding::span[2]</value>
      <webElementGuid>6df4cae1-2b32-42c6-be3f-64d2f19c93ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear Persona'])[1]/preceding::span[3]</value>
      <webElementGuid>b4970224-2b4d-4e78-a6ca-57039182b181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]/button/span[2]</value>
      <webElementGuid>f7aa3daa-b95d-4428-b19a-507dbcbb2e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Seleccionar' or . = 'Seleccionar')]</value>
      <webElementGuid>b9565da0-fb96-4d60-bd43-3c1c634aba16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
