<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ENVIO YA FUE ASIGNADO</name>
   <tag></tag>
   <elementGuidId>298f6e8a-223c-4b30-906a-5f92f58e7ebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(.,'ENVIO YA FUE ASIGNADO')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>750a032b-90e9-4722-b008-d2e95b3acc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>5c96119e-2bd1-4510-87d1-a2f98ed16725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ENVIO YA FUE ASIGNADO</value>
      <webElementGuid>4200b9d1-b3fe-4ee3-b5c5-c769aba75049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pistoleoDatos&quot;)/tbody[1]/tr[1]/td[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>4ae7a9c7-3c75-42c4-a593-77cf38ee94c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte Destajo por Operador_iframeP_aa3353</value>
      <webElementGuid>1f57d291-2887-493a-bac9-9bec78a179ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pistoleoDatos']/tbody/tr/td/span</value>
      <webElementGuid>2c251d73-3d96-499a-84b3-56158df4d754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CODIGO DE BARRAS:'])[1]/following::span[1]</value>
      <webElementGuid>4aed558c-82ce-4c2f-b281-6cce9e89f75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASIGNACIONES POR SALIDA'])[1]/following::span[1]</value>
      <webElementGuid>f7ca96a4-6d35-4c72-b426-34d70e9fdc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COD OPER. :'])[1]/preceding::span[1]</value>
      <webElementGuid>fbceb60b-205e-4ff4-aedd-cd9eeb3333c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPERADOR :'])[1]/preceding::span[1]</value>
      <webElementGuid>f68a6441-6f60-43ba-a054-aaf982302707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ENVIO YA FUE ASIGNADO']/parent::*</value>
      <webElementGuid>a3575bee-8db3-4ce2-a6d6-292a2a42bbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>cec27146-72e7-49fa-9e17-1cac3b281a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ENVIO YA FUE ASIGNADO' or . = 'ENVIO YA FUE ASIGNADO')]</value>
      <webElementGuid>75ac1deb-7d14-4b00-b1d6-8d0e223ee936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
