<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Asignar automaticamente_ui-chkbox-icon ui-icon ui-icon-blank ui-c</name>
   <tag></tag>
   <elementGuidId>ac1cec6b-6678-40f6-8e66-c3b55a4b0778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-chkbox-icon.ui-icon.ui-icon-blank.ui-c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAsignacion:j_idt28']/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3cc44721-b74c-4b0c-a591-7d060317867d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-icon ui-icon ui-icon-blank ui-c</value>
      <webElementGuid>ef31cbff-6cd2-481a-baf1-99b57d3a1e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAsignacion:j_idt28&quot;)/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-chkbox-icon ui-icon ui-icon-blank ui-c&quot;]</value>
      <webElementGuid>bcee561c-d840-4e58-9d82-d353a9346871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Olva Corp/Page_Principal - Olva Courier/iframe_Reporte Destajo por Operador_iframeP_aa3353</value>
      <webElementGuid>40c3b263-3908-4547-a883-2ee0d870acdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAsignacion:j_idt28']/div[2]/span</value>
      <webElementGuid>aa2c8e6a-c009-4bf8-9021-fd3120c237bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>ecf55851-1f4f-4a18-b789-bdc23d6a459d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
