<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ifram</name>
   <tag></tag>
   <elementGuidId>33cc0a3c-33ee-445a-864d-f9e3a7e0258f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe_response']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe_response</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0ba11b8c-a9a0-48d4-b3db-b70c8f9ee9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe_response</value>
      <webElementGuid>4e76790f-328f-40e0-851f-caf0b3c5575b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>60e385cd-fbe6-4851-8f39-ad58d27ddd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://girley.herokuapp.com/search?origin=https://registro.olvacourier.com/registrar_envios_promo/nuevo-envio</value>
      <webElementGuid>6edd31da-f431-4936-ab69-475a9977850c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77ff0cac-c66c-4e45-921e-4aaa61bbc636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe_response&quot;)</value>
      <webElementGuid>259a7b0a-ac6d-461c-bd22-4c04ff87f260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe_response']</value>
      <webElementGuid>d1c432fa-7742-4dcc-86ab-7ea9bbc1788e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetDireccionEntrega']/div/div/div[2]/iframe</value>
      <webElementGuid>4d600eae-d6c0-4940-8256-8cbe24108ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar'])[2]/following::iframe[1]</value>
      <webElementGuid>9f3bd7f2-8b7b-4913-a1e8-2f4a7a4223d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[3]/following::iframe[1]</value>
      <webElementGuid>1a3969cc-17ae-44c3-b03e-94bafe362582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::iframe[1]</value>
      <webElementGuid>ef7bf2fb-f0bf-49fd-a595-ea663ea506ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando Dirección ...'])[1]/preceding::iframe[1]</value>
      <webElementGuid>cda35625-cea0-49b2-9ac2-3f143db331a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2c27118c-da9b-4aea-b085-c4e3d668d841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe_response' and @src = 'https://girley.herokuapp.com/search?origin=https://registro.olvacourier.com/registrar_envios_promo/nuevo-envio']</value>
      <webElementGuid>34dca303-1991-46aa-a172-54ef0154cc0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
