<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cerrar_iframe_response</name>
   <tag></tag>
   <elementGuidId>9e834b09-1fba-42af-b639-7dfed78b06ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframe_response</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe_response']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>185c6b7f-2d1a-42c9-9c04-7909ac765eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe_response</value>
      <webElementGuid>9988d6af-1dc6-4b6b-842c-570530492745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>26230984-4979-42f8-838a-17f604ae3c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://girley.herokuapp.com/search?origin=https://registro.olvacourier.com/registrar_envios_cargo_adjunto/nuevo-envio</value>
      <webElementGuid>28d71679-5c12-48f9-a640-66f88ace8a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac056593-3c17-465c-8805-7dff4ad55d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe_response&quot;)</value>
      <webElementGuid>54ad8ce6-6814-47a1-b798-3c1232a8a1c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe_response']</value>
      <webElementGuid>bebf086e-603a-4c71-b22d-bd878edc7678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetDireccionEntrega']/div/div/div[2]/iframe</value>
      <webElementGuid>ed193f38-c5d5-454b-8f71-10bb65f6f8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar'])[2]/following::iframe[1]</value>
      <webElementGuid>fcc7333e-2174-4607-9b68-2fe156ddd14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[3]/following::iframe[1]</value>
      <webElementGuid>48cff91b-4559-43ea-87bc-aa7fc42d5623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::iframe[1]</value>
      <webElementGuid>2e04a0f2-8918-4d79-9ee9-84e0069c30f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando Dirección ...'])[1]/preceding::iframe[1]</value>
      <webElementGuid>0d695286-fa62-4da6-8812-0da0d47702ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>28cd3977-3108-40a1-b493-cd49322f5f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe_response' and @src = 'https://girley.herokuapp.com/search?origin=https://registro.olvacourier.com/registrar_envios_cargo_adjunto/nuevo-envio']</value>
      <webElementGuid>07d27985-cfdf-4bf2-90b6-dcd610c10174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
