<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referencia_reference_new</name>
   <tag></tag>
   <elementGuidId>76391785-57c5-41fa-9588-ea6c185039d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reference_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83d21216-9278-4f74-8c79-26eca4a595bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference_new</value>
      <webElementGuid>ac0e9030-8373-45cf-bc29-28bcbfd7bc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d382a5d6-2dfa-4407-ae2b-a91b1d388978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>885947c8-c826-4439-89dd-b26a69d40997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ejem: Entre Av. Argentina y Av. Universitaria</value>
      <webElementGuid>de7b94f4-71cd-4770-b541-4a5012d4f90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6b25bc25-ae11-4d52-84cf-02c9e40d1c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference_new&quot;)</value>
      <webElementGuid>a360ad0d-403f-4ad0-bb5b-b242730d3e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Olva Courier  Datos Personales/iframe_Cerrar_iframe_response</value>
      <webElementGuid>bf1c7868-57be-4432-980c-8eb4dae6bce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference_new']</value>
      <webElementGuid>890f1f52-079f-4137-a65c-d9f344f71444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__993356___BV___']/div/input</value>
      <webElementGuid>c3072f47-2cdd-4c41-8227-03da6f14f0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ee649398-cd44-4078-98c1-fc1cbcf0637c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference_new' and @type = 'text' and @placeholder = 'Ejem: Entre Av. Argentina y Av. Universitaria']</value>
      <webElementGuid>2e65e326-0452-4626-b27c-6ec4bf6b20b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__926712___BV___']/div/input</value>
      <webElementGuid>ef9e9702-27a1-4283-8a24-a98796e39f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
