<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin de Entrega_direccion_new</name>
   <tag></tag>
   <elementGuidId>3c86f2d2-9726-4330-81fb-5c5c6eb977dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#direccion_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='direccion_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b2188af-d5cf-479a-8fea-7a195807638e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direccion_new</value>
      <webElementGuid>2740590f-60fb-46e8-9750-1977802abb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4db6c48-c338-4b7c-8db9-594fc13cdfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4a510ae-8e77-48f7-9ffd-a42bef43ed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa una dirección</value>
      <webElementGuid>b90dced9-441f-430a-ae28-9bd3d71586c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3835d7a1-0c24-4ab2-8c1a-784524a511c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direccion_new&quot;)</value>
      <webElementGuid>0d99eafb-8213-4b6c-9b6e-66d0a5e81ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Olva Courier  Datos Personales/iframe_Cerrar_iframe_response</value>
      <webElementGuid>41564898-5dd1-4887-bfc4-f9494d354eba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='direccion_new']</value>
      <webElementGuid>73f45245-f743-4f6d-bbc6-0a91846bf55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__048406___BV___']/div/input</value>
      <webElementGuid>604ad2c9-37c0-450b-bfce-40b995a9c694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>9c1d535e-7ea8-4c90-b28c-41aa47be5658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'direccion_new' and @type = 'text' and @placeholder = 'Ingresa una dirección']</value>
      <webElementGuid>3649e724-1e7c-45c7-b2c6-987ad807db4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__497078___BV___']/div/input</value>
      <webElementGuid>a6b29bdb-7fe8-44b2-8ba5-9a9708c04516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
