<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Map_local</name>
   <tag></tag>
   <elementGuidId>67494bef-97ec-4035-9df5-3df5dece44a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;map&quot;]/div/div[1]/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.map.rounded.leaflet-container.leaflet-touch.leaflet-grab.leaflet-touch-drag.leaflet-touch-zoom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6895a76-a49f-4218-b777-ae9b0c8af8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>map rounded leaflet-container leaflet-touch leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>6cc4a52b-b36d-47a6-8829-5aec3f381c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96a06e42-3589-49fd-984e-432cb892e00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+- Leaflet</value>
      <webElementGuid>dbc70c51-320d-46b0-83ff-5167cc2c6fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__892470___BV___&quot;)/div[1]/div[@class=&quot;map rounded leaflet-container leaflet-touch leaflet-grab leaflet-touch-drag leaflet-touch-zoom&quot;]</value>
      <webElementGuid>6570a07e-c4b2-4b5c-adff-0a9db4bfb19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Olva Courier  Datos Personales/iframe_Cerrar_iframe_response</value>
      <webElementGuid>6c0c2073-2335-4cf6-8440-25a3184259d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__892470___BV___']/div/div</value>
      <webElementGuid>6f273b39-d33d-4998-981a-c73a268ee0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✖'])[1]/following::div[2]</value>
      <webElementGuid>fae91572-fc22-4c06-a2c3-c97b880ad51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirección de Entrega'])[1]/following::div[3]</value>
      <webElementGuid>8489d859-f18c-4ca9-9498-60abd2d1d42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mz, Lote o Referencia'])[1]/preceding::div[19]</value>
      <webElementGuid>2973f41b-91b8-4254-bd78-c301dd81107f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div</value>
      <webElementGuid>24ab1549-1e7a-487b-b532-4e3f28bad183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '+- Leaflet' or . = '+- Leaflet')]</value>
      <webElementGuid>ccf7928f-2f1a-4ffc-b3e1-2039babd9977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
