<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aceptar_visaNetJS</name>
   <tag></tag>
   <elementGuidId>4919a293-bf06-46ac-aaed-dc5f7d77e86b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visaNetJS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='visaNetJS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>868d7cf3-733a-4361-9865-0ac0a2e74d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visaNetJS</value>
      <webElementGuid>009e79e8-eb31-497a-a532-90e22a5c1eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6bc2d31a-a1e6-41e4-9cef-4e7440fd6809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47a2f7d0-1894-4434-b2e1-d161ed5227a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-content-qas.vnforapps.com/v2/visanet.html?0.6158475565947887&amp;qa=true</value>
      <webElementGuid>73e1e1e4-ff57-483b-8d0b-c49a85b7b2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visaNetJS&quot;)</value>
      <webElementGuid>f69702e2-0c8a-41aa-8234-1a2c06cec846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='visaNetJS']</value>
      <webElementGuid>dec866be-b148-46fb-a487-ba1af42459d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visaNetWrapper']/iframe</value>
      <webElementGuid>5d87a7b0-c348-4e0d-af0a-d624b2844eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>0fbdede1-5a93-4949-bab6-7f5025686a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'visaNetJS' and @src = 'https://static-content-qas.vnforapps.com/v2/visanet.html?0.6158475565947887&amp;qa=true']</value>
      <webElementGuid>27a33dd0-5afd-417f-a7f4-c77a81c117b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
