<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buscar</name>
   <tag></tag>
   <elementGuidId>2fdb8e67-b66d-4c4a-a97c-e616a8e55029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buscar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;buscar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75fd2ac9-c3e5-41a4-89e1-1d12912875c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buscar</value>
      <webElementGuid>7bf47511-cff8-4851-95cc-ccd68580da91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-small</value>
      <webElementGuid>668a5ac1-d1f7-42c2-85f9-733ab8771b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Buscar</value>
      <webElementGuid>b9fcde4e-867d-4710-9dd2-2f630d0d4a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario&quot;)/div[@class=&quot;span12&quot;]/div[@class=&quot;control-group&quot;]/div[@class=&quot;controls&quot;]/button[@id=&quot;buscar&quot;]</value>
      <webElementGuid>fae7a9ba-2f4a-4315-8429-fd10a1a5287f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buscar']</value>
      <webElementGuid>2bd1373a-cbdc-473f-a8b4-f54cbbe253f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formulario']/div/div/div/button</value>
      <webElementGuid>f368b3fc-372b-4111-a85f-47f050f291a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>6bacbbe3-206f-433f-bde9-29f35ff169b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>086b9a2e-5b4f-41f9-a1bc-1b11801e45ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buscar' and (text() = ' Buscar' or . = ' Buscar')]</value>
      <webElementGuid>67f19419-e8bb-487a-a167-57d0d39c59ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
