<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buscar (1)</name>
   <tag></tag>
   <elementGuidId>f8eab9d0-363f-431b-ae99-ff81acf70ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;buscar&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buscar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d75b763-a4e2-4f30-bf25-23972e72d076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buscar</value>
      <webElementGuid>08526fa0-c101-4699-9443-dc84b12fa746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-small</value>
      <webElementGuid>12d62760-683a-419f-b114-41b27ed64eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Buscar</value>
      <webElementGuid>fe6c8b44-3d0b-48e4-9506-f3238eab37cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario&quot;)/div[@class=&quot;span12&quot;]/div[@class=&quot;control-group&quot;]/div[@class=&quot;controls&quot;]/button[@id=&quot;buscar&quot;]</value>
      <webElementGuid>5838d406-5bed-4fc4-ae43-ffe1b1d31f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buscar']</value>
      <webElementGuid>d922fa7f-1b02-4e3f-8934-fab64aa00a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formulario']/div/div/div/button</value>
      <webElementGuid>c263f348-4d87-466a-8b1e-4dd1910f535e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>75cf4aca-161d-4189-b04c-a20fd844b15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5b6777bc-41e5-4061-93a4-1e0ba4a9ad61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buscar' and (text() = ' Buscar' or . = ' Buscar')]</value>
      <webElementGuid>5a427695-4b95-434d-9119-7b8fbeae51c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
