<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Inicio_fecha_inicio (1)</name>
   <tag></tag>
   <elementGuidId>7de37a99-a0f5-4254-9402-6e8079d81ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fecha_inicio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@type,'text')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f86935e6-363f-4a66-82f4-6e325104fb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>778ef7c8-8305-4c4e-a73d-b303f7b40ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small hasDatepicker</value>
      <webElementGuid>f02c0e74-6f39-4021-b866-a97520231b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fecha_inicio</value>
      <webElementGuid>d6d93cff-f93c-474a-828f-6ee9bea4b1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fecha_inicio</value>
      <webElementGuid>54eca238-0762-4346-bf5a-e0401e1d1e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17/09/2022</value>
      <webElementGuid>5853c9af-5729-44be-90a5-e5ca1098007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fecha_inicio&quot;)</value>
      <webElementGuid>fa930cc2-4938-4461-9103-24b0e4a37b64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fecha_inicio']</value>
      <webElementGuid>45279507-cc59-4fd5-b4c7-0d88d7abc65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formulario']/div/div/div/input</value>
      <webElementGuid>f5188668-a9d4-44c4-9152-d6f91126fb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2b9bf439-86fc-41be-84e6-a1e666f8d78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fecha_inicio' and @name = 'fecha_inicio']</value>
      <webElementGuid>edc38f17-1be7-4baf-9b87-2a14f23b7cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
