<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Fin_fecha_fin</name>
   <tag></tag>
   <elementGuidId>936db8d3-3cb7-477a-a5a5-a500050c22a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fecha_fin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fecha_fin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d33ac6bd-7e36-44c9-b80d-09c034fb856f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09473e15-024c-4666-8d8e-64374f74a2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small hasDatepicker</value>
      <webElementGuid>d4b8c3e3-53d9-44be-b1a1-b5bcdcbd59a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fecha_fin</value>
      <webElementGuid>2f7c05b2-60a9-46d5-bae1-a14366e70a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fecha_fin</value>
      <webElementGuid>2fb13aa7-d45f-486a-80d3-02bd9262f2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17/09/2022</value>
      <webElementGuid>f599849b-ed67-4f12-b9f4-800944f362ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fecha_fin&quot;)</value>
      <webElementGuid>081b0c6b-3b7e-47f1-be8a-9ff3472a9969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fecha_fin']</value>
      <webElementGuid>4d7a7030-081f-4400-bb55-6d12bfafc73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formulario']/div/div/div/input[2]</value>
      <webElementGuid>d3566c27-f472-48ac-97c1-29f1799d00fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>dff36ff7-e341-4a98-8e77-28e94a60c34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fecha_fin' and @name = 'fecha_fin']</value>
      <webElementGuid>171e02c5-937f-42e0-8254-466ec2068e03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
