<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_html1body1</name>
   <tag></tag>
   <elementGuidId>3520503e-f574-4da1-abfa-62bec95d67b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>45d3401f-7ec0-4cea-ba4f-34cd456aa1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>cf1c08a3-2648-4c96-aca5-80bae9f9b0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>9d170ea6-92c0-4b95-ada1-1d6ae505dfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_- Servicio de Intranet OLVA -  Confirm_1c32e7/iframe_Your        web browser doesnt alow _98a391</value>
      <webElementGuid>0ab3d19d-3210-4eb5-ade2-5f6f6c661291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>7098648c-900b-4dbe-be9b-6f0e8a547fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = '/html[1]/body[1]' or . = '/html[1]/body[1]')]</value>
      <webElementGuid>066c7e9a-6d9b-49ca-adac-0ebba2204a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
