<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hasta_txtHasta</name>
   <tag></tag>
   <elementGuidId>2b487c38-2ec6-42a9-ae86-f39d06da6085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtHasta&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table[2]/tbody/tr/td[3]/b</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/form[1]/table[@class=&quot;simple_text&quot;]/tbody[1]/tr[1]/td[4]/input[1][count(. | //input[@name = 'txtHasta' and @size = '10' and @onclick = concat(&quot;muestraCalendario(&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;fcalen&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;txtHasta&quot; , &quot;'&quot; , &quot;)&quot;)]) = count(//input[@name = 'txtHasta' and @size = '10' and @onclick = concat(&quot;muestraCalendario(&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;fcalen&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;txtHasta&quot; , &quot;'&quot; , &quot;)&quot;)])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77f34aad-514e-4e36-b0bb-1c93d27a2408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtHasta</value>
      <webElementGuid>653606dd-fcdc-4195-8448-0919d764b8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>cf982451-b01b-4629-b4dc-a6ae4ebcd188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>muestraCalendario('','fcalen','txtHasta')</value>
      <webElementGuid>531af370-f676-4478-959b-be4e4dd39fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[@class=&quot;simple_text&quot;]/tbody[1]/tr[1]/td[4]/input[1]</value>
      <webElementGuid>491417be-3a74-40a5-b82d-8d0bcad86f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtHasta']</value>
      <webElementGuid>76c23990-a12c-4078-bb01-8efb34a6ce5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>c8d1e7c5-658e-46eb-b24b-ca6ce6e22bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtHasta']</value>
      <webElementGuid>75118652-876d-4f51-9fd4-c52725642a6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
